### ISSUE TITLE
minor bug in link fn for glm.families.Poisson

### ISSUE THREAD

**Issue by jonsedar** [pymc-devs/pymc#1100]
Bumped into this when creating a poisson regression model: 

Existing: the current glm.familes.Poisson class uses a log link function

Expected: I think it ought to be an exponential link function, as per various docs e.g. [wikipedia](https://en.wikipedia.org/wiki/Poisson_regression)

Suggest: changing:

line 20 to `exp = theano.tensor.exp`, and
line 97 to `link = exp`

**Comment by twiecki** [comment]
Fixed by #1102.

**Comment by krz** [comment]
why was this changed? The linked wikipedia article says that the canonical link function is the log.

**Comment by twiecki** [comment]
CC @jonsedar

**Comment by jonsedar** [comment]
The current form of the distribution families in `glm/families.py` (Normal, Binomial etc) is to estimate the `y` directly, hence (and I may be wrong here, never rule that out) the link function should be `exp`.

Try it for yourself and see how a `log` link function fails to handle `y <= 0`.

I was unsure of it at the time, so created this notebook comparing a manually-specified and also `glm`-specified model: seems to all work nicely: https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GLM-poisson-regression.ipynb

**Comment by twiecki** [comment]
Yes, that should be correct. We want a transform that converts R -> R+.

**Comment by jonsedar** [comment]
Heh thanks - much more succinct ;) I need to get down with my stats notation...

**Comment by krz** [comment]
thanks for the explanation, I did make a quick example to confirm it's correct: https://gist.github.com/krz/f7a0dd933de3e5765f651cfbfc634280

**Comment by jake-westfall** [comment]
It seems to me that the issue here is terminological at its root, and is the result of confusing the "link function" and the "inverse link function." What you are calling here the link function is in fact the inverse link function.

To be more precise, If Y is the response and D is an exponential-family distribution with location parameter Theta, then traditionally we say that we're specifying the linear model

f(Theta) = b0 + b1*X + ...

where f() is the link function. Another way to express this, and in practice the way we implement it in Bayesian software, is to say

Y ~ D(g(b0 + b1*x + ...))

where g() = f^-1() is the inverse function of f().

In the case of Y ~ Poisson, the link function f() is log, and the inverse link function g() is exp. So exp is indeed the function that should be applied to the right-hand-side of the regression equation, but referring to exp as the "link function" in the package is not strictly correct (it's the inverse link function) and will only lead to confusion.

**Comment by twiecki** [comment]
Thanks for the clarification @jake-westfall. Not quite sure what the best solution is. Calling a link-function log but internally it's exp seems odd, but maybe it's fine if we explicitly say it's the inverse link function that's  required.
