### ISSUE TITLE
Cauchy and HalfCauchy producing too many extreme values

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1203]
I think that both the Cauchy and HalfCauchy are producing extreme values too often. Moreover, the output of `pm.HalfCauchy` does not match the absolute of `pm.Cauchy`. It tends to produce even more/larger extreme values:

``` python
import pymc3 as pm
import matplotlib.pyplot as plt


with pm.Model() as model:

    x = pm.Cauchy(name='x', alpha=0, beta=1)
    y = pm.Deterministic('y', abs(x))
    z = pm.HalfCauchy(name='z', beta=1)
    trace = pm.sample(20000)
    pm.traceplot(trace)
    plt.savefig('test.png')
```

![test](https://cloud.githubusercontent.com/assets/9464950/16245175/9dc90bb4-37cd-11e6-8397-532a2479f25a.png)

**Comment by twiecki** [comment]
This is pretty vague. Cauchy is supposed to produce extreme values. The differences you're seeing might just be different scaling due to different large values you're sampling. To make this more substantiative, plot the actual Cauchy/HalfCauchy on top of it to show that it's not sampling from the same distribution. We have tests for all of that though so I think it's probably correct.

**Comment by twiecki** [comment]
Closing this, feel free to reopen when you have a more quantitative test.
