### ISSUE TITLE
Stick-breaking multidimensional mixture

### ISSUE THREAD

**Issue by krz** [pymc-devs/pymc#1260]
Hi,

I extended the Dirichlet stick-breaking example from the docs, where the distribution parameters of two Gaussians are estimated to a setting that includes covariates. So I want the parameter estimates of two Gaussians and the "ideal" number of mixture components. So basically I have a mixture
f_mix = alpha \* N(a + b1 \* x1 + b2 \* x2, s) + (1- alpha) \* N(c + d1 \* x1 + d2 \* x2, s).

Here is the code:
https://gist.github.com/krz/1a5b1313e9fe57c35109f724735692e3

When I sample from this model I only get constant values, obviously no proposal is accepted.

**Comment by twiecki** [comment]
Are you on current master?

**Comment by krz** [comment]
Yes I just performed a git install today. I use current anaconda with python 3 on an ubuntu system.

**Comment by twiecki** [comment]
It's possible that stickbreaking just doesn't work for higher dimensions. @taku-y do you have any insight?

**Comment by taku-y** [comment]
@krz In your code

```
    K0_int = pm.Normal('K0_int', 0., sd=10, shape=K)
    K1_int = pm.Normal('K1_int', 0., sd=10, shape=K)
    int_ = pm.Normal('int', K0_int, K1_int, shape=K)
```

The 3rd arg of `pm.Normal` is `tau`, the precision of the distribution, but I think `K1_int` can be negative.

**Comment by krz** [comment]
thanks @taku-y , I changed that to a HalfNormal, but it's still not working. Actually @AustinRochford , the creator of the stick-breaking example in the docs, tried something similar and did not get it to work either (only constants in the sampling, no proposal accepted).

**Comment by taku-y** [comment]
I modified your code and made an notebook (https://gist.github.com/taku-y/3c6481c52c6d72076da6ad5fe664d8ab). `NUTS` did't work because of an error of scaling value, so I used `Metropolis`. In addition, instead of `Metropolis` for `component`, I used `ElemwiseCategorical`. 

I'm not sure the result is reasonable, it looks that two of the five components are selected more than other three components (top panel of the traceplot). Could you tell me the problem on the result if any?

**Comment by krz** [comment]
amazing, thanks. It works. The estimates are not yet close to the true values but I'll experiment a bit with the priors and add add more n_samples. Can be closed.
