### ISSUE TITLE
Resuming a MCMC run

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#143]
I noticed that various discussion threads have requested the ability to continue a MCMC run.  By continue, I mean that after calling sample(), one could call sample again and append the results to generate a longer chain.  

I realize that there is the "interactive" sampler, but to me it would be nice for all sampling to have a hot restart / append capabilities.  

Feel free to close this if this has already been discussed and deemed undesirable.

**Comment by fonnesbeck** [comment]
Hey Kyle,

You cannot resume a chain with `sample()`, but you can sample additional chains that will be started where the last chain left off when using `sample()` serially, then simply concatenating the chains together. PyMC3 will run multiple chains in parallel by default, which can then be treated as a single sample if desired for inference. 

I will add the enhancement tag to this issue, so that restarting is universal for PyMC3.

**Comment by jsalvatier** [comment]
we have this now
