### ISSUE TITLE
feature: alternatives to gaussian kde in traceplot

### ISSUE THREAD

**Issue by majidaldo** [pymc-devs/pymc#1434]
i find the gaussian kernel misleading sometimes. a nice feature to have it to be able to pass kwargs to scipy.stats.kde or just a histogram.

hmm maybe i'll do it.

**Comment by aloctavodia** [comment]
In my experience one reason the KDE can be misleading is because the SciPy implementation does not include any correction for boundary effects, and hence a distribution like an exponential does not look good close to zero. I tried to fix this problem adding a (maybe naive) correction method to the SciPy implementation, but my PR (https://github.com/scipy/scipy/pull/6114) is still waiting for approval (after months), probably someone could do a better PR.

BTW, @majidaldo I think what you are proposing could be nice!

**Comment by majidaldo** [comment]
is it the opinion of management to not have seaborn as a dependency?

**Comment by fonnesbeck** [comment]
If it provides something we need that is difficult to replicate ourselves, then it can be justified. However, we can probably make our plots look better without seaborn, I should think. What did you have in mind?

**Comment by twiecki** [comment]
I'm fine with using seaborn if it just saves us code. Its pretty well packaged.

**Comment by fonnesbeck** [comment]
It depends on how we use it. I know that simply importing seaborn clobbers the default settings for matplotlib, which we would not want to inflict on our users.

**Comment by aloctavodia** [comment]
I think seaborn is very nice from the user point of view (I use it all the time, and I could use it even more!), because provides very nice ready-to-use plots, that otherwise will take several lines of code. But from the perspective of the developer I am more in line to @fonnesbeck's  opinion. 

Anyway, to avoid changing the default (or user) settings for matplotlib do  `import seaborn.apionly as sns`

**Comment by twiecki** [comment]
@majidaldo At this point we don't have a strong proposal of where and how it would help us currently. If you want to demonstrate its usefulness in either (a) making the plots nicer, or (b) saving us code to maintain, we will certainly consider it, but note that there is a hurdle in adding new dependencies.

**Comment by fonnesbeck** [comment]
Closing this. Feel free to work on a PR if this is something worth pursuing.
