### ISSUE TITLE
Tensorflow instead of Theano

### ISSUE THREAD

**Issue by arose13** [pymc-devs/pymc#1650]
Is there a possibility for `PyMC3` to use TensorFlow instead of Theano for it's math? It would make deploying less complex and I would need `sudo` to run the python scripts due to `PermissionErrors`.

I also believe that TensorFlow will surpass (if it hasn't already) Theano in terms of speed and functionality.

**Comment by fonnesbeck** [comment]
It is not, except [via Edward](https://github.com/blei-lab/edward/blob/5afba38eef7a6ffff1824f6c373d3499d5e416e5/examples/pymc3_beta_bernoulli.py).

**Comment by arose13** [comment]
Are you saying using Edward means that PyMC3 can run without the need for sudo?

**Comment by fonnesbeck** [comment]
You should not need to be superuser when running Theano, particularly if you use Anaconda, which installs everything in your home directory.

**Comment by kyleabeauchamp** [comment]
For the long-term, I think we should continue to monitor the relative benefits of Theano vs Tensorflow.  Tensorflow has rapidly improved in its performance, ease-of-use, and ubiquity.  See slide from their YC talk: 

![image](https://user-images.githubusercontent.com/1900459/29243605-c335d224-7f57-11e7-9b17-7b573e0bd4e8.png)

**Comment by aseyboldt** [comment]
I agree that we should monitor this, but personally I don't think using tensorflow is an option right now. It is optimised for working with very large datasets, and as far as I can tell it tends to be very slow on smaller models with a large number of ops. It doesn't have any stable op fusion at the moment. (there seems to be [xla](https://www.tensorflow.org/performance/xla/), which might change this in the maybe not so distant future).
Also, there is no way we could make such a transition without breaking backward compatibility, so we should think about it very carefully. On the other hand, I think we might be able to use a transition like that to fix a couple of internal problems (like our dependance on test vals, or the general messy shape handling).
I implemented a very minimal outline of how a pymc3 implementation using tensorflow could look like, mostly as an exercise for learning tensorflow:
https://gist.github.com/aseyboldt/1054cf6d6b871041914c601c1efa11ae
Note the very large number (900μs) at the very bottom. I hope that that is because I'm doing something stupid, that really wouldn't be acceptable otherwise.
Otherwise, I have to say tensorflow seems to be pretty nice to work with.

**Comment by kyleabeauchamp** [comment]
Yeah, my main argument for brining this up is that I think we're kinda squeezed between Stan and Edward for many uses, so we need to be smart about maintaining an advantage on both of them.  

FWIW, I implemented a bunch of models in Edward and I didn't like the syntax as much (too much boilerplate) and I suspect it also had issues with the MAP/Jacobian.  That said, it seemed to be performing pretty well for my applications.

**Comment by aseyboldt** [comment]
Out of interest, what datasets / sizes / algorithms are you working with?

**Comment by kyleabeauchamp** [comment]
It's basically using an (NxM) matrix to fit (MLE) two parameter vectors of size (N) and (M), respectively, where N and M are in the hundreds.

I was unable to get BFGS working because the ML people apparently forgot about 30 years of optimization research ;), so I played with several of the SGD variants available.

**Comment by aseyboldt** [comment]
Sounds like that should work, yes. From what I can tell tensorflow has a very large per-op overhead. I fear that in low dimensional problems that will just kill the performance. Theano has a lot of problems, but it does usually generate reasonable code for stuff like that, and the compiler does the rest.
But I really are intrigued about XLA, it sounds pretty much exactly like what we need.

**Comment by stonebig** [comment]
On theano-dev google groups there is a post about the end of Theano active support by Montreal Institute https://groups.google.com/forum/#!topic/theano-dev/gCBAhE3Sb_8

**Comment by junpenglao** [comment]
thanks @stonebig, we are starting to experiment with different backend in https://github.com/pymc-devs/pymc4_prototypes, contribution welcome!

**Comment by jolespin** [comment]
It seems like it was already discussed but theano won't be under active development anymore:
http://deeplearning.net/software/theano/
![image](https://user-images.githubusercontent.com/9061708/31625763-1fd352fe-b25c-11e7-9e3e-af4f6a30b462.png)

**Comment by junpenglao** [comment]
@jolespin more discussion see our discourse: https://discourse.pymc.io/t/tensorflow-backend-for-pymc4/409/
