### ISSUE TITLE
Step size adaptation in NUTS

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1697]
The algorithm implemented for step size adaptation in pymc3 differs from the algorithm described in the paper about nuts and from the stan implementation. The algorithm in the paper (algorithm 6) adaptes epsilon very quickly for the first 1000 iterations, while keeping some average epsilon around. After these 1000 iterations it stops the adaptation and only uses the average epsilon. pymc3 sticks to the first epsilon all the time, and also uses a slightly different way to update it (`log(e)' = mu - m ** k / gamma H_bar` instead of `log(e) = mu - sqrt(m) / gamma H_bar`). Is this intentional? The docstring doesn't say anything about this.

**Comment by twiecki** [comment]
Hm, good catch. @jsalvatier originally implemented this and then @ColCarroll refactored it.

@aseyboldt Want to do a PR on this? At some point we'd also want to implement the new multinomial sampling version of NUTS.

**Comment by jsalvatier** [comment]
Nope. Looking at the [paper](http://www.stat.columbia.edu/~gelman/research/published/nuts.pdf) now, it looks to me like I initially implemented Robins and Monroe adaptation (equation above equation 5) and never replaced it with primal-dual adaptation. 

Oops. 

Looks like I should have written more TODOs. 

We should definitely try out primal-dual adaptation, since it looks like it should do a better job. 

A PR would be great.
