### ISSUE TITLE
ADVI should fail on nan generation

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1714]
We should probably have `advi` exit the first time a `nan` is generated. There seems to be no utility in continuing the optimization.

**Comment by ferrine** [comment]
We can add some tips for user) 
I've also thought about global logp scaling (e.g. divide by provided number) to avoid overflow nans with large scale problems.

**Comment by taku-y** [comment]
Would it be better to raise an exception when we get nan?

**Comment by twiecki** [comment]
@taku-y Probably. We should also add dynamic stopping when convergence is reached.

**Comment by taku-y** [comment]
@twiecki I see. I will work on it tomorrow.

**Comment by espears4sq** [comment]
@ferrine Was there ever any follow-up on [your comment](https://github.com/pymc-devs/pymc3/issues/1714#issuecomment-275268216) above?

I am noticing for a large-scale logistic model that is correctly specified, ADVI cannot be used because the large number of parameters leads to overflow/underflow issues immediately, even when ensuring that the `test_point` for the model is fine prior to starting sampling.

Are there any existing settings with ADVI that can be used to avoid this? I get `FloatingPointError: NaN occurred in optimization` immediately when using ADVI on [this problem](https://github.com/pymc-devs/pymc3/issues/3132). It seems to just be a function of how many parameters there are.

**Comment by twiecki** [comment]
Does sampling work? Most likely your model is misspecified.

**Comment by espears4sq** [comment]
@twiecki Thanks for your reply. I posted more details [linked here](https://github.com/pymc-devs/pymc3/issues/3132).

I think the model is well-specified since it is an extremely simple logistic regression with Gaussian priors on the parameter components. From the toy data I generate, many other libraries like sklearn, statsmodels, etc., are able to converge to accurate solutions and diagnostic plots look fine.

When I sub-sample the toy data to reduce the problem size, I can get Metropolis sampling to work with a gigantic number of slow iterations (and I don't know why they are so slow, since it's just draws from a multivariate Gaussian with no correlation terms, and calculating a very simple log-likelihood from the standard logistic model).

With NUTS, I can't get anywhere. Whether reducing the problem size or not, the sampling rate is too slow to even come close to an adequate number of samples.

My overall goal is to figure out if there is a configuration or setting for any variational algorithm, or for NUTS or plain Metropolis, to allow efficiently sampling from the model with the full data set (~1.5 million observations and ~500-dimensional parameter vector).
