### ISSUE TITLE
ADVI results are affected by adding unobserved variables in a simple graphical model

### ISSUE THREAD

**Issue by perov** [pymc-devs/pymc#1805]
Good time all.

I am trying a very simple script which samples from the Dirichlet distribution:
 
```
with pm.Model() as model:
    mu = pm.Dirichlet("mu", np.array([1, 1, 1]), shape=(1, 3))
    a = pm.Normal('value_alpha', mu=mu[0][0], sd=0.0001)
    # b = pm.Normal('value_beta', mu=mu[0][1], sd=0.0001)
    # c = pm.Normal('value_gamma', mu=mu[0][2], sd=0.0001)
 
with model:
    trace = pm.variational.advi(n=100000)
   
print(trace)
```
 
 
I would expect that the code above should result in the variation inference approximation, where variable a is approximately equal to 0.33 in expectation (thus the mean of their VI’s approximation is close to 0.33).
 
However, I do not get that with those two lines commented. What I get is as follows:

``` 
ADVIFit(means={'mu_stickbreaking_': array([[-0.23575004,  0.00713217]]), **'value_alpha': array(0.2835169591396134)**}, stds={'mu_stickbreaking_': array([[  5.67761924e-04,   1.84546166e+00]]), 'value_alpha': 0.00011044813450787451}, elbo_vals=array([ -5.42656242e+06,  -4.05624255e+07,  -3.13703489e+06, ...,
        -9.49310028e+00,  -2.76510004e+01,  -1.66405331e+01]))
```
 
If I uncomment those two lines, everything becomes as expected:

``` 
ADVIFit(means={**'value_beta': array(0.3268432058968142)**, 'mu_stickbreaking_': array([[ 0.0533034, -0.0018499]]), **'value_alpha': array(0.34531620330530427), 'value_gamma': array(0.3276778201392476)**}, stds={'value_beta': 0.0001121428789802522, 'mu_stickbreaking_': array([[ 0.00040552,  0.0004908 ]]), 'value_alpha': 0.00011536300100290127, 'value_gamma': 0.00011072099316618015}, elbo_vals=array([ -9.31043899e+07,  -1.11549792e+08,  -1.02925050e+08, ...,
        -1.48132166e+01,  -1.57313692e+01,  -1.44984877e+01]))
```
 
To tell the truth, I do not understand why that might be happening. That is, those two lines should not anyhow affect the model, to the best of my understanding. They just should add two more unconditioned variables to the model, right?.. If anybody can advise why this might be happening, that would be very helpful.
 
Thank you,
Yura Perov

**Comment by twiecki** [comment]
CC @taku-y.

**Comment by taku-y** [comment]
@perov Thanks for your report. I'm not sure whether it is a bug or mathematically correct. 

It is probably related to the weighting of the uncertainty of RVs based on the hierarchical prior. To check this, could you test different concentration parameters of Dirichlet like `pm.Dirichlet("mu", np.array([1e3, 1e3, 1e3]), shape=(1, 3))` or `pm.Dirichlet("mu", np.array([1e-3, 1e-3, 1e-3]), shape=(1, 3))`? If one of these parameters results in value_alpha close to 0.33, it might be worth to write down ELBO objective for your model in order to understand how the Gaussian terms of unobserved RVs affects the weighting of the objective.
