### ISSUE TITLE
Regression test fail: sample_ppc 'size' param seems to no longer work correctly

### ISSUE THREAD

**Issue by jonsedar** [pymc-devs/pymc#1897]
Using `sample_ppc` with `size = n` (i.e. not `None`) leads me to a broadcasting error. Possibly related to issue #1529

e.g. with 466 datapoints, `sample_ppc(trained_model, samples=100, size=10)` leads to 
`ValueError: cannot reshape array of size 4660 into shape (10,)`

i.e. each of the 466 datapoints has lead to a new PPC distribution, from which 10 draws are taken. I'll take a dig around, it seems to be incorrect expectation of the shapes in:

```python
# distributions/distribution.py

def reshape_sampled(sampled, size, dist_shape):
    dist_shape = infer_shape(dist_shape)
    repeat_shape = infer_shape(size)

    if np.size(sampled) == 1 or repeat_shape or dist_shape:
        return np.reshape(sampled, repeat_shape + dist_shape)    ## <- this line
    else:
        return sampled


### this is having been reached via:

# distributions/distribution.py
def generate_samples(generator, *args, **kwargs):
...
return reshape_sampled(samples, size, dist_shape)  ## <- this line

```

There's a lot of reshaping gymnastics going on here, and I'm not sure why... I'll see if I can figure out the logic and make a fix

**Comment by jonsedar** [comment]
@AustinRochford it looks like you made a change to this code in commit d2b8efdf32955671a899f1b13edd3e38babc7909...

Could you help me understand the logic here? I'm not even sure I need to reshape at all:

I've found that for my purposes of `sample_ppc`, I can simply do 

```python
# distributions/distribution.py
def generate_samples(generator, *args, **kwargs):
...
return samples   ## <- don't even bother to reshape
```

**Comment by AustinRochford** [comment]
You can see what led up to this change here:

https://github.com/pymc-devs/pymc3/issues/1695

`sample_ppc` was failing when both `repeat_shape` and `dist_shape` where empty tuples.

**Comment by jonsedar** [comment]
Do you remember which tests were failing? Since for my case (a simple LM) the array was already in the (ndatapoints, draws) shape that I needed. The `generate_samples` call seemed unnecessary...

**Comment by AustinRochford** [comment]
Here is the unit test I added that failed before my change https://github.com/pymc-devs/pymc3/pull/1698/commits/22527e541c9d9b69b487883cd3e7ff00fddca530.  Also, the PPC section of the logistic regression example had been failing as well, IIRC.

**Comment by jonsedar** [comment]
Hmm interesting - I see that test doesn't have njobs > 1, that might make the difference perhaps. I don't have time to think more about this today but will follow up soon - perhaps adding a test for njobs > 1

J

**Comment by AustinRochford** [comment]
Yes, that could definitely do it!

**Comment by slygent** [comment]
I think I am facing a similar issue, but not because of njobs. This is my model:

```
with pm.Model() as model:
    probs = pm.Beta('probs', alpha = 0.1, beta = 0.1, shape = (number_of_categories, number_of_outcomes))
    outcomes = pm.Bernoulli('outcomes', p = probs[np.array(categories)], observed = outcomes_df)
    step1 = pm.Metropolis(vars = [probs])
    trace = pm.sample(3000, tune=1000, step = step1)
```

The inputs are `categories`, a Series of 3015 integer values between 0 and 99 inclusive, and `outcomes_df`, a 3015 by 39 DataFrame of 0s and 1s. The idea is that for every category and every outcome, there will be a different Beta distribution for the resulting value.

The model trains well, but `sample_ppc` doesn't give the expected result. `with model: post_pred = pm.sample_ppc(trace, samples=500)` gives `post_pred['outcomes'].shape` equal to `(500, 3015, 39)` instead of the expected `(500, 39)`. Trying to give a size parameter to `sample_ppc` fails for any value, e.g. `with model: post_pred = pm.sample_ppc(trace, samples=500, size = 1)` triggers the error `ValueError: cannot reshape array of size 117585 into shape (1,)`, which seems to indicate it's including the original sample (and indeed changing the samples parameter doesn't change the error).

**Comment by slygent** [comment]
This also happens with the following simpler model:

```
with pm.Model() as model:
    probs = pm.Beta('probs', alpha = 0.1, beta = 0.1, shape = number_of_categories)
    outcomes = pm.Bernoulli('outcomes', p = probs[np.array(categories)], observed = np.array(outcomes_df['outcome1']))
    step1 = pm.Metropolis(vars = [probs])
    trace = pm.sample(3000, tune=1000, step = step1)
```

Then `with model: post_pred = pm.sample_ppc(trace, samples=500)` leads to `post_pred['outcomes'].shape` to be equal to `(500, 3015)` instead of the expected `(500,)`.

**Comment by TMorville** [comment]
I have this issue as well. Any progress?

**Comment by mmajewsk** [comment]
+1

**Comment by jsevo** [comment]
+1

**Comment by GtheSheep** [comment]
Not sure if I've got the right end of the stick here, but isn't this due to the `size` param as opposed to `n_jobs`? And the failing is coming from `reshape_sampled` being called with a `size`, but for `Continuous` distributions the `dist_shape` is an empty bumpy array? Whereas if you wanted to juggle these repeat sizes then either `size` or `dist_shape` has to carry that information through to `reshape_sampled`?

I.e. allowing the already cast from `[]` to `()` `dist_shape`, now called `prefix_shape` to be used. One, kind of grim way to do it:
```
# distributions/distribution.py
def generate_samples(generator, *args, **kwargs):
...
        if size is not None:
            samples = replicate_samples(generator,
                                        broadcast_shape,
                                        repeat_shape + prefix_shape,
                                        *args, **kwargs)
            return reshape_sampled(samples, size, prefix_shape + broadcast_shape)
        else:
            samples = replicate_samples(generator,
                                        broadcast_shape,
                                        prefix_shape,
                                        *args, **kwargs)
    return reshape_sampled(samples, size, prefix_shape)
```
would pass the following test:
```
    def test_sample_ppc_size(self):
        x = np.random.normal(size=100)
        y = x + np.random.normal(scale=1e-2, size=100)

        x_pred = np.linspace(-3, 3, 200)

        x_shared = theano.shared(x)

        with pm.Model() as model:
            b = pm.Normal('b', 0., 10.)
            pm.Normal('obs', b * x_shared, np.sqrt(1e-2), observed=y)

            trace = pm.sample(1000, init=None, progressbar=False)

            x_shared.set_value(x_pred)
            pp_trace = pm.sample_ppc(trace, 1000, size=10)

        np.testing.assert_allclose(x_pred, pp_trace['obs'].mean(axis=0).mean(axis=0), atol=1e-1)
```
I'm sure there's a nicer way for the shapes to flow through, but just wanted to check this was the case first.
Apologies if I've totally misunderstood the premise of `sample_ppc` here 😆
