### ISSUE TITLE
Return traces in dict or DataFrame?

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#191]
Currently `psample` returns traces that are unlabeled, so it is not easy to determine which traces match up with which variables. Can we return something with labels, like a dict or a Pandas DataFrame?

I also wonder if we need to return the state and time elapsed. It should be easy to retrieve the state if you need it, no (e.g. from the end of the trace)? Perhaps the time elapsed should simply be reported.

**Comment by fonnesbeck** [comment]
Sorry, I did just notice that `NpTrace.sample` is a dict. That may fit the bill, but it is worth considering what should be returned to the user.

**Comment by jsalvatier** [comment]
I really like the idea of returning a DataFrame. I looked into it a few days ago, and the issue I saw was that DataFrame didn't allow efficient incremental adding of rows, which would make that tricky. If it worked, it would be really nice though. 

I guess numpy arrays can't be concatenated like that either, and that seems to work OKish in NpTrace. Maybe we can just replace the numpy arrays with a data frame? Maybe we could just store the results in a python list until we're done sampling and then concat them into a DataFrame.

**Comment by twiecki** [comment]
Yeah, a DataFrame is a numpy array underneath. Both have to be consecutive blocks in memory so there should be no difference between them, except that DataFrame has a much nicer interface.

**Comment by fonnesbeck** [comment]
I thought the traces are preallocated. Do we need to incrementally add rows very often?

**Comment by jsalvatier** [comment]
@fonnesbeck they are, no we don't need to do that very often. In fact the current NpTrace object doesn't increase in size at all, it just raises an error if it runs out of room. We should probably fix that before release.

**Comment by jsalvatier** [comment]
This looks promising: http://stackoverflow.com/questions/13751926/efficiently-add-single-row-to-pandas-series-or-dataframe

**Comment by fonnesbeck** [comment]
The downside is that HDF5 is pretty fussy to install, which is why we made it an optional backend extension in PyMC2.

**Comment by twiecki** [comment]
I think resizing happens only rarely in reality so bringing out the HDF5
guns is probably not worth it, especially given install-issues.

We could initialize a DataFrame with columns for all variables (empty in
the beginning). Sampling then creates a new DataFrame that gets appended to
the main one. That way supports multiple calls to sample() as we just keep
appending.

Alternatively we could use a 3d DataFrame (i.e. Panel) with the 3rd axis
being the trace.

**Comment by jsalvatier** [comment]
@twiecki 
I implemented a little something and came up with: https://github.com/pymc-devs/pymc/tree/dftrace . Basically you append to a list until you finish sampling, and then concatenate it into a data frame.

The issue I came across is that the values are stored as objects rather than arrays, so plotting didn't work if size > 1 http://nbviewer.ipython.org/urls/raw.github.com/pymc-devs/pymc/dftrace/examples/tutorial.ipynb .

I think this is fixable, but I don't know pandas well enough to know what the right solution is. Is it a 3d DataFrame? Is it a multiindex? Any suggestions Thomas?

I suspect this is complex enough that we shouldn't try to add this before release. However I'd like to make the future transition as easy as possible by making NpTrace more DataFrame like so that we can seamlessly change the default later.

**Comment by twiecki** [comment]
I like the interface.

The potentially multidimensional random variables add complexity. It seems
as if multicolumns might do the trick:
http://pandas.pydata.org/pandas-docs/dev/indexing.html#creating-a-multiindex-hierarchical-index-object
(further
down he uses it for columns as well).

It seems as if the sampler currently returns [value] rather than value. You
could just unpack the values when creating the df though. Then those would
be float types.

A 3d DataFrame (called a Panel) would have an issue if you mix random
variables of different dimensionality.

I'm not clear however what to do if the random variable is a matrix... I
suppose we could flatten it out to a vector and still do multicolumns. Or
just keep adding levels of multicolumns for the dimensionality of random
var.

**Comment by jsalvatier** [comment]
This isn't happening right now (asked a question about this, but no good responses http://stackoverflow.com/questions/15806414/storing-multidimensional-arrays-in-pandas-dataframe-columns), so I'm removing the release tag. I've tried to make the current implementation of NpHistory at least somewhat friendly to a future pandas implementation.

**Comment by twiecki** [comment]
Hm, indeed. This essentially requires shape heterogeneity which pandas doesn't have. However, blaze was built with these things in mind (http://blaze.pydata.org/docs/overview.html). Not sure how ready for prime time it is but there is some work there: https://github.com/ContinuumIO/blaze-core

**Comment by jsalvatier** [comment]
It doesn't seem to require shape heterogeneity in the way blaze means, just multi-dimensional columns (with different dimensions).

**Comment by twiecki** [comment]
Granted, blaze can do much more funky stuff but multi-dimensional columns are a subset of shape heterogeneity.

I still think the pandas multiindexing would give us mostly what we need. The problem is that it's not easy to get from your list of dicts to a suitable format. Also, it'd get a little messy for everything more than 2 dimensions.
http://pandas.pydata.org/pandas-docs/dev/indexing.html#creating-a-multiindex-hierarchical-index-object
