### ISSUE TITLE
memory leak issue when running the pymc3 in AWS machine

### ISSUE THREAD

**Issue by mydatech001** [pymc-devs/pymc#1959]
i came across a strange problem and wonder if anyone here had similar experience and know how to work it out. basically:

1. i start coding my pymc3-based script in my own laptop and learnt how to use shared variable which help to minimize my 'memory leak' issues that is caused by recompiling theano multiple times (https://github.com/pymc-devs/pymc3/issues/1825)

2. after this, i start deploying the same script in AWS cloud machine (linux) and found the memory leak issue happened again. 

3. what surprised me is that, with the same python script, the memory leak problem is only observed in AWS environment (but not in my own windows/linux laptop)

Any advice would be highly appreciated!

**Comment by twiecki** [comment]
Are you up-to-date on theano master (0.9.0) and pymc3 master?

**Comment by mydatech001** [comment]
pymc3-3.1rc2-py3.5.egg-info
theano-0.9.0rc4-py3.5egg-info

**Comment by twiecki** [comment]
And you instantiate just a single model?

**Comment by mydatech001** [comment]
true. just a single model is initiated. it's the same code deployed on both local laptop and remote AWS machine.....

the code structure looks like:
`

    with pm.Model() as model:
        .....
        betas =...
        tau = ...
        mu = sum(betas[n]*xx[:,n] for n in range(len(betas)))

    for iteration in range (0,xxx)):
        ...    
        xx.set_value(X)
        yy.set_value(y)

        with model:
            trace = pm.sample(niter, ...)

        mcoefs=pm.df_summary(trace)['mean']                

`

**Comment by twiecki** [comment]
That looks correct. How do you identify the leak?

**Comment by mydatech001** [comment]
the memory occupied by python keep going up....but in my own machine, i didnt observe anything like this

**Comment by aaronjmaxwell** [comment]
Interesting.  I found a problem similar to the OPs, which I discussed in #1825.  My workaround was to use the `multiprocessing` module and spin the PyMC3 model compilation and solution into its own process.  Something like this, @mydatech001:
```
import multiprocessing as mp
for i in range(n):
    args = my_new_loop_args
    q = mp.Queue()
    p = mp.Process(target = my_model, args = (q, my_new_loop_args,)
    p.start()
    result = q.get()
    q.close()
    p.join()
```
and `my_model` is simply where you've defined the `pymc3` model.
```
def my_model(q, my_model_args):
    import pymc3 as pm
    with pm.Model() as my_model:
        mu = pm.Normal('mu', *args, **kwargs)
        ...
    q.put(my_model_result)
```
Since `multiprocessing` spins the process off onto it's own processor, the memory will be freed back to the system.  You lose some execution time because of the message passing through the queue and the overhead to spin up the process, but you won't eat up your system memory.

What get's me, though, is that my memory issue is also on AWS.  Could there be an architecture issue here?
