### ISSUE TITLE
GLM logistic regression notebook broken

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2016]
The [logistic regression example notebook](https://pymc-devs.github.io/pymc3/notebooks/GLM-logistic.html) is broken, as currently rendered.

I think we have to have a testing procedure in place to ensure merged changes do not break notebooks. Probably too time-consuming for Travis, but there seems to be a fair amount of breakage that is occurring as the master branch evolves. Perhaps PR reviewers can instruct those submitting significant changes to run each of the notebooks locally? Suggestions welcome.

**Comment by jake-westfall** [comment]
Someone recently brought [nbval](https://github.com/computationalmodelling/nbval) to our attention, which seems great for just this purpose. We haven't started using it in our `bambi` repo yet, so I can't speak from any personal experience with it, but it's probably worth looking into.

**Comment by ColCarroll** [comment]
I started working on a project this weekend for keeping pymc (and other?) notebooks up to date: https://github.com/ColCarroll/carpo

Haven't even gotten to a readme, but briefly, it is a CLI so that 
```
carpo notebooks/*.ipynb
```

will start executing and saving all notebooks.  Exceptions are caught and printed (in which case the notebook is not saved again).  It keeps a sqlite database of successful runs (and timing), so you can run things for a while, then restart later and it will only run notebooks that haven't run successfully yet for the given gitrev (for projects that aren't in git, it will rerun everything, every time).

Will need to check out `nbval` -- I don't love overwriting notebooks, but don't have a better answer right now (in particular, progress bars and plots virtually guarantee output will be different every time).

**Comment by fonnesbeck** [comment]
Sounds good, @ColCarroll. In the interim, I will add a sentence in the CONTRIBUTING file to suggest running notebooks that would be affected by submitted changes.

**Comment by ColCarroll** [comment]
Perfect - this project wouldn't change that advice, it would just make it easier to follow!

**Comment by owlas** [comment]
(disclaimer: I'm an author of nbval)

nbval essentially reruns notebooks in a separate kernel and compares the output to the output stored in the notebooks. The usual workflow: you make some code changes, run tests including nbval, identify notebooks who's output has changed, inspect the changes and if they're acceptable you save the notebook with the new outputs.

One of the disadvantages is that rerunning notebooks for PyMC3 will probably add a significant amount of time to the test suite, which is already hitting the Travis CI limit (as @fonnesbeck mentioned)
