### ISSUE TITLE
Ignored KeyboardInterrupt

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2043]
This feels like bad behavior: `KeyboardInterrupt` should stop the program as soon as reasonable.  I see it in three spots:

- [ ] Inference, [line 85](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/inference.py#L85)
- [ ] Inference, [line 159](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/inference.py#L159)
- [ ] Sampling, [line 285](https://github.com/pymc-devs/pymc3/blob/master/pymc3/sampling.py#L285)

Both files also have helpful handling of keyboard interrupts (saving traces, closing buffers), so this seems straightforward (unless there's a reason to ignore!)

**Comment by twiecki** [comment]
You mean the fact that they are nested? I think only two of them are, no? The one in `fit` should be called independently.

**Comment by aseyboldt** [comment]
This lets us stop sampling and still get access to the trace. I use it all the time in the notebook and I quite like it. I don't think there is anything in a standard saying that SigInt should stop a program, that is just the default signal handler. For terminating a program there is always sigterm, and that still works.
Posix isn't very specific about how programs should behave when they get a specific signal, but it is specified that `ed` shouldn't exit on sigint, but stop what it is doing and wait for new user input. Same for `ex`.

The UNIX Programmer's manual says this:

> The ‘break’ or ‘interrupt’ key causes an interrupt signal, as does the The ASCII ‘delete’ (or ‘rubout’)
character, which is not passed to programs. This signal generally causes whatever program you are run-
ning to terminate. It is typically used to stop a long printout that you don’t want. However, programs
can arrange either to ignore this signal altogether, or to be notified when it happens (instead of being ter-
minated). The editor, for example, catches interrupts and stops what it is doing, instead of terminating,
so that an interrupt can be used to halt an editor printout without losing the file being edited.

**Comment by ColCarroll** [comment]
ah, sorry, you're both right -- I was reading the `except` as being indented one further, so it would catch and continue sampling.
