### ISSUE TITLE
Parameter bound checking

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#2086]
None of the discrete distributions test that their parameter values are in the allowable range (see below example).  IMHO there should be parameter bound checking in the constructors.  

```
import pymc3 as pm


with pm.Model():
    x = pm.Binomial("x", 10, -0.5)
    tr = pm.sample(10)

print(tr["x"].mean())
-5.3
```

**Comment by kyleabeauchamp** [comment]
Is `assert_negative_support()` from `continuous.py` and extra `bound()` statements the best way to implement this?

**Comment by kyleabeauchamp** [comment]
Why not do some refactoring of *all* distributions so that the constructor always tests for nonzero probability for all parameters?

**Comment by hvasbath** [comment]
One way how to check you can find in the current smc.py step_method. It extra compiles a check_bound function next to the logp which simply only includes the input variables. And calculates their summed logp ... if inf the value is out of bounds ...

The function is compiled in line 204 and used in line 241

This avoids refactoring.

**Comment by fonnesbeck** [comment]
`bound` already checks the support of `p`:

            binomln(n, value) + logpow(p, value) + logpow(1 - p, n - value),
            0 <= value, value <= n,
            0 <= p, p <= 1)

I think the problem here is that `Metropolis` does not blow up when it gets `-inf` log-probabilities, the way `NUTS` does when it encounters `NaN`. The sampler should be complaining loudly.

**Comment by kyleabeauchamp** [comment]
See #2091 : I think that `bound` is not working as we think it should, as demonstrated by my additional test case.

**Comment by aseyboldt** [comment]
We had some recent discussion about `bound` somewhere, I just can't find it at the moment. What I'd like to do when I have the time is to add a parameter to `Model`, that controls how much `bound` should do. I'd like three settings:

1. Add a node to the theano graph that raises an exception if the variable is invalid (including what variable and if possible which parameter). The step methods should then catch that and mostly handle it as -inf, but also print a waring / add a warning to the report. We need exception handling like this anyway, for example if the graph raises a LinAlgError or similar. This would be similar to what stan is doing, and I think it would help greatly when debugging a model.
2. The current behaviour: Return -inf if it is invalid. The runtime overhead of this should be smaller. Theano puts this inside an Elemwise, so it does not become its own `Apply` node.
3. Leave it out altogether. In many cases the support is fine because of the parametrization and inf/nan arithmetic, and it just slows things down and makes it impossible for theano to do some optimizations. Alternatively we could try to write theano optimization passes that get rid of some checks, but I think this might be rather difficult.

The issue you found in `assert_negative_support` is I think more or less unrelated. It is just executed once when the graph is build, and apparently it could be quite a bit more thorough. 😄

**Comment by twiecki** [comment]
Yeah, the specific bounds had more of a raison d'être when we didn't auto-transform, so somewhat an anachronism. Thus, your option 3 sounds pretty appealing. An easy interim solution to get both would be to add a flag to `Model(bounds_check=False)` which turns all bounds into noops.

**Comment by aseyboldt** [comment]
@twiecki I'd really like warnings, too. I've spend quite a bit of time trying to figure out where exactly some variable becomes inf or nan, and this seems to come up in issues and on SO a lot as well.

**Comment by junpenglao** [comment]
I think we should address this issue. The `assert_negative_support` currently is not working as demonstrated by @kyleabeauchamp. It failed on simple cases like:
```python
with pm.Model() as model:
    sd = pm.Normal('sd', 0., -1.)
    obs = pm.Normal('obs', 0, sd**2, observed=np.random.randn(1000))
```
the code above runs without throwing an error.

**Comment by twiecki** [comment]
`assert_negative_support` seems to only support probability distributions being passed in.
