### ISSUE TITLE
Automatic step method assignment

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#211]
We probably want to consider a mechanism for automatically assigning step methods to nodes. For PyMC2, this worked really well 90% of the time. Each step method has a competence function that yields a score depending on the structure of the candidate node (e.g. continuous vs. discrete, array-valued vs. scalar) and the step method with the highest score is automatically assigned. Each assignment, of course, can be overridden with an explicit assignment.

**Comment by jsalvatier** [comment]
Thoughts:
- How should we handle samplers that work on multiple variables? Should we iterate over all permutations of variables? The number of variables will probably usually be small enough to do that.
- What do you think about Estimated Effective Samples Per Sec (or computation) as the currency of fitness? These don't necessarily need to be very good estimates to be useful.
- To support this, we'll need to start keeping track of Random Variables that hold their distribution rather than just Theano variables. Not sure what the cleanest way to do this is.

**Comment by twiecki** [comment]
I believe we have implemented this.
