### ISSUE TITLE
traceplot slow when there are many parameters

### ISSUE THREAD

**Issue by maxliving** [pymc-devs/pymc#2118]
I have a model in which I learn a vector of ~2,000 parameters. Traceplot is very slow and often crashes when trying to plot the results. I assume the problem is just a constraint of matplotlib. What would be nice if there were an easy way for it to only plot a subset (random or otherwise) of my 2,000 parameters, just to get a quick visualization of whether things look sensible. What are people's thoughts on this approach?

**Comment by aloctavodia** [comment]
I have some points you may find useful.

* You can pass a list of variables names  using the ```varnames``` argument to plot a subset of variables.
* You can make things easier to traceplot by plotting a  "thinned" trace, something like ```trace[::10]```
* If you are running multiple chains you can combine them for plotting ```combined=True```
* You can try using a forestplot, instead of a foresplot.
* PyMC3 implements a fast routine to compute the KDEs, but maybe there is still room from improvement.
* Visually checking so many parameters could be daunting maybe you can build an automatic-diagnostic-report using the diagnostics already available in PyMC3. I guess this could be a nice addition to PyMC3.

**Comment by fonnesbeck** [comment]
@maxliving I second @aloctavodia's advice, particularly the use of `forestplot`. The `traceplot` function is only intended to be used on scalar (or very small vector-valued) variables. The `forestplot` on the other hand can be used on much larger sets, as you can scale the panel vertically to accommodate a large number. 

However, even with `forestplot` having thousands of variables outstrips the capabilities of the built-in plotting functions. At that point, you may want to take the raw trace and use a package like `seaborn` or `bokeh` to come up with a useful visualization.
