### ISSUE TITLE
Remove statsmodels from examples

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#2245]
We don't want to depend on it; depending on licensing, can ship the relevant data sets as part of the pymc3 repo.

The following examples (and perhaps more) need to be modified:

- [ ] [Dirichlet process mixtures](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/dp_mix.ipynb)
- [ ] [Survival analysis](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/survival_analysis.ipynb)

**Comment by freddyalfonsoboulton** [comment]
I'd like to help with this!

**Comment by ColCarroll** [comment]
I'm bad at reading licenses, but: a quick look says all data comes from `rdatasets`, which fall under the core `R` license (if you get them from there), which I think is GPLv3 and more restrictive than ours (in particular, it is copyleft).  

I'd guess the particular datasets are public domain (since they're pretty well known), but didn't dig too much.

**Comment by fonnesbeck** [comment]
... yet `statsmodels` is BSD-licensed.

**Comment by ColCarroll** [comment]
I think the data carries its own license.  The internal datasets actually
mention if they're public.
