### ISSUE TITLE
sample_smc: AttributeError: 'NoneType' object has no attribute 'n_steps'

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#2374]
```
with pm.Model():
    pm.NormalMixture('m', 
                     mu=np.array([0., 1.]), 
                     w=np.array([.6, .4]), 
                     sd=np.array([.2, .2]))
    step = pm.smc.SMC(n_chains=500)
    trace = pm.smc.sample_smc(n_steps=1000, step=step, homepath='/tmp')
```

`traceplot(trace)` gives:
![image](https://user-images.githubusercontent.com/674200/27769932-025816ac-5f36-11e7-9fca-a9499857b86d.png)

`sns.distplot(trace.get_values('m'));` gives:
![image](https://user-images.githubusercontent.com/674200/27769934-0bf06408-5f36-11e7-9fd9-875294f9cf1a.png)

**Comment by junpenglao** [comment]
You need to set up the SMC step first.
```python
with pm.Model():
…
    step = smc.SMC(
        n_chains=n_chains, tune_interval=tune_interval)
    
    mtrace = smc.sample_smc(
                        n_steps=n_steps,
                        step=step,
                        n_jobs=n_jobs,
                        progressbar=False,
                        stage=0,
                        homepath=test_folder,
                        rm_flag=False)
```

**Comment by fonnesbeck** [comment]
Can they not be passed via `inf_kwargs`? If not, they should be. 

Again, looking to keep the interface consistent with others.

**Comment by hvasbath** [comment]
@fonnesbeck sorry I was not aware of these new interface changes, when I started you always had to define a step object and give that to the sampling function. Can you please refer me to the lines where you do that?
@twiecki yes please follow @junpenglao suggestion and the transforms have to be disabled, transforms=False

You are right as there is a dedicated sample_smc function the initalisation of the step object should be done automatically if the input is None ... will look into that when I have time the next days...

**Comment by junpenglao** [comment]
@hvasbath I will have time (finally) next week to have a look at the code as well.
Some motivation: after the refactoring we can remove the experiment tag ;-)

**Comment by hvasbath** [comment]
@junpenglao looking forward for that! I will also look a little more on the GPU speedup as mentioned in the other issue, maybe we should coordinate that a little-or I wait after you are done with the refactoring. Dont hesitate to ask if you need any clarification or whatever ...

**Comment by junpenglao** [comment]
I will keep you posted - probably will come as many questions...

**Comment by hvasbath** [comment]
```
with pm.Model() as mixmodel:
   ...:     pm.NormalMixture('m', 
   ...:                      mu=np.array([0., 4.]), 
   ...:                      w=np.array([.8, .4]), 
   ...:                      sd=np.array([1., 2.]),
   ...:                      )
   ...:     

mtrace = pm.smc.sample_smc(n_steps=10, n_chains=1000, tune_interval=2, model=mixmodel, homepath='/tmp/', rm_flag=True, progressbar=True)
```

/Users/vasyurhm/Software/pymc3/pymc3/step_methods/smc.py:477: UserWarning: Warning: SMC is an experimental step method, and not yet recommended for use in PyMC3!
  warnings.warn(EXPERIMENTAL_WARNING)
Argument `step` is None. Auto-initialising step object using given/default parameters.
/Users/vasyurhm/Software/pymc3/pymc3/step_methods/smc.py:120: UserWarning: Warning: SMC is an experimental step method, and not yet recommended for use in PyMC3!
  warnings.warn(EXPERIMENTAL_WARNING)
Adding model likelihood to RVs!
Removing previous sampling results ... /tmp/stage_0
Init new trace!
Sample initial stage: ...
Beta: 0.000000 Stage: 0
Initialising chain traces ...
Sampling ...
100%|██████████████████| 1000/1000 [00:05<00:00, 180.21it/s]
Beta > 1.: 1.999999
Sample final stage
Initialising chain traces ...
Sampling ...
100%|██████████████████| 1000/1000 [00:43<00:00, 23.22it/s]

In [11]: tp = pm.traceplot(mtrace, transform=last_sample, combined=True)
![figure_mixture](https://user-images.githubusercontent.com/11273616/27768649-aab9d2ae-5f18-11e7-8e98-2d1a7307458f.png)

Is it Ok like this?

**Comment by junpenglao** [comment]
I ran a few quick simulation - I think it is fine.

**Comment by twiecki** [comment]
Results with NUTS:
![image](https://user-images.githubusercontent.com/674200/27780742-f3010570-5fca-11e7-8100-693c7b35dd82.png)

Results with SMC:
![image](https://user-images.githubusercontent.com/674200/27780753-0c7feca0-5fcb-11e7-8f74-b42d294513c2.png)

Traceplot gives:
![image](https://user-images.githubusercontent.com/674200/27780763-1c451e30-5fcb-11e7-96d2-c080eda7ea30.png)


Code:
```python
with pm.Model():
    pm.NormalMixture('m', 
                     mu=np.array([0., 1.]), 
                     w=np.array([.6, .4]), 
                     sd=np.array([.2, .2]))
    step = pm.smc.SMC(n_chains=500)
    trace = pm.smc.sample_smc(n_steps=10000, step=step, homepath='/tmp')
```

**Comment by junpenglao** [comment]
Did you run with #2376? I find it outperform NUTS when the `mu` is far apart.

**Comment by junpenglao** [comment]
@twiecki The SMC traceplot needs more care as well, below is my code
```python
n_steps=10
with pm.Model() as mixmodel:
    pm.NormalMixture('m', 
                     mu=np.array([0., 1.]), 
                     w=np.array([.6, .4]), 
                     sd=np.array([.2, .2]))

mtrace = pm.smc.sample_smc(n_steps=n_steps, n_chains=1000, tune_interval=2, model=mixmodel, homepath='/tmp/', rm_flag=True, progressbar=True)

def last_sample(x):
    return x[(n_steps - 1)::n_steps]
pm.traceplot(mtrace, transform=last_sample, combined=True);
```
![image](https://user-images.githubusercontent.com/12952641/27787115-12449190-5fe4-11e7-9990-9b6faffc4e41.png)

**Comment by junpenglao** [comment]
SMC outperform NUTS: for example, with 
```python
pm.NormalMixture('m', 
                     mu=np.array([0., 10.]), 
                     w=np.array([.6, .4]), 
                     sd=np.array([1., 1.]))
```
SMC (n_steps=10, n_chains=1000, tune_interval=2):
![image](https://user-images.githubusercontent.com/12952641/27787270-8244dafe-5fe4-11e7-88f2-46f833dc18f2.png)


NUTS (10000, init=None, 500 tune):
![image](https://user-images.githubusercontent.com/12952641/27787274-85880b46-5fe4-11e7-92da-d10ade1b7472.png)

**Comment by twiecki** [comment]
#2376 shouldn't produce different results here, just simpler API, right?

In any case, the output you get is more what I would expect, not sure why it doesn't work for me. Do you get the same results on 3.1?

**Comment by twiecki** [comment]
Ah, I had to remove the old files. The UX is still quite clunky here, I think we need to put some effort it making this more turn-key. Specifically:
1. it should not be required to manually delete files when doing multiple sampling runs
2. `pm.sample_smc()` should just work (#2376 fixes this)
3. the trace should display correctly when passed to `pm.traceplot()` without any custom transformations.

**Comment by junpenglao** [comment]
Yep, agree. 

IMO SMC should internally always create a new folder and then move to the destinative one after sampling (address point 1). Also, trace should return the final particles with the history of the sampling (currently all in trace) in a different subfield (maybe `mtrace.history`?) to address point 3. 

@hvasbath what do you think?

**Comment by aloctavodia** [comment]
I think SMC is actually returning all samples from the last temperature/stage, i.e. all samples from the _true_ posterior, isn't it?

**Comment by hvasbath** [comment]
@twiecki it performs so badly for you, because you do not use enough chains! You have to increase n_chains! The standard traceplot doesnt work! You have to define this function last_sample as @junpenglao did and use this as a transform. Because only the last sample of each chain is assumed to be a sample from the posterior. So n_steps as for the other samplers is not the length of the final trace but rather n_chains!
I was thinking about creating a smc.traceplot function. What do you think?
You simply have to set the rm_flag=True and it will remove anything that is present in the destination folder. Sometimes you dont want to do that and rather restart in an intermediate stage. Thats why the default is rm_flag=False. Improving the API is absolutely no problem, just tell me what you like to have and think is needed.
I will fix the test error in the PR soon. I am still on the bussiness trip ...

**Comment by junpenglao** [comment]
> Because only the last sample of each chain is assumed to be a sample from the posterior. So n_steps as for the other samplers is not the length of the final trace but rather n_chains!

What do you think about my suggestion above: we do the transform internally and return the final trace (length n_chains), so that the normal `pm.traceplot()` works directly. The mtrace (as it is currently) will be rename into something else (suggestion: `history`?).

> I was thinking about creating a smc.traceplot function. What do you think?

Unless there is some additional information from the SMC traceplot, i don't think this is very necessary. 

> You simply have to set the rm_flag=True and it will remove anything that is present in the destination folder. Sometimes you don't want to do that and rather restart in an intermediate stage. Thats why the default is rm_flag=False. 

I think a `rm_flag=True` default would be easier for end user then.

Just to emphasise: my points are mostly for shaping the SMC API so that minimal code changes are needed to switch from another sampler to SMC. One of such is the `transformed=False`, it would be great to get the none transformed RV (or add a random method for the transformed but the solution I tried is rather too slow).

**Comment by twiecki** [comment]
I agree with all those suggestions.

**Comment by hvasbath** [comment]
I agree, with your points and I should be able to do most of that, but with the transforms I really have no clue. Lately, it also worked with transform = True, I think you might have changed something with these. 
Setting them to false was mainly, because the trace got junked with the transformed variables and the variable names changed also to something to indicate that they were transformed. This made it impossible to retrieve the right meaningful value from the trace. With the example above it works also with transforms. Did you try other models?

**Comment by hvasbath** [comment]
Updated the notebook as an example to use the "new API". 
1. The returned trace can be given to traceplot and summary now. 
2. The rm_flag is True by default - I warned you, so be careful now especially with expensive models.  
3. Transforms=None has to be still set otherwise the initialisation of the starting points doesnt work which calls random. Someone with knowledge about how the transforms work would need to look into that.
Unfortunately, I wont have time for that the next months as I am changing jobs and moving between countries. Minor things I can still fix.

**Comment by junpenglao** [comment]
Thanks @hvasbath , good luck with your moving ;-)
So #2376 is ready?

**Comment by hvasbath** [comment]
Tests are still running, but should pass, if nothing unexpected happens ;) .

The final trace can be loaded independendly later after sampling with:
```
stage_handler = smc_text.TextStage(path)
rtrace = stage_handler.load_result_trace(model)
```
I was not sure where to put it. Maybe we should work anyways on more extensive docs for SMC? Maybe there. Or should that also go to the notebook?

**Comment by hvasbath** [comment]
Timeout issue again with the tests... Otherwise they are fine... @junpenglao

**Comment by junpenglao** [comment]
Hmmm I am trying to run the notebook locally and I got a weird result:
![image](https://user-images.githubusercontent.com/12952641/27993990-4ffc8b1c-64b4-11e7-8a0b-ae723df670ec.png)

**Comment by hvasbath** [comment]
Intersting!? and WTH? :) And ah I know whats the problem ... needs another fix. I had the feeling that this might go wrong, now thats the proof thanks for testing! ;) Strangely for me it works...

**Comment by hvasbath** [comment]
Ok this should fix it. Was more difficult than expected... Could you please test it again locally @junpenglao ? For me everything works fine.

**Comment by junpenglao** [comment]
@hvasbath it works ;-)

btw, the `rtrace` loaded from
```python
stage_handler = smc_text.TextStage(path)
rtrace = stage_handler.load_result_trace(model)
```
is the same as `mtrace` from 
```python
mtrace = smc.sample_smc(
    n_steps=n_steps,
    n_chains=n_chains,
    tune_interval=tune_interval,
    n_jobs=n_jobs,
    progressbar=False,
    stage=0,
    homepath=test_folder,
    model=ATMIP_test)
```
right?

**Comment by hvasbath** [comment]
Yes thats right! It should be like that. Just accidentally named it differntly here...
