### ISSUE TITLE
Stochastic Volatility Example

### ISSUE THREAD

**Issue by willferreira** [pymc-devs/pymc#2566]
There are two Stochastic Volatility examples in the docs, [here](http://docs.pymc.io/notebooks/stochastic_volatility.html), and [here](http://docs.pymc.io/notebooks/getting_started.html#Case-study-1:-Stochastic-volatility).

In the first example, the daily log returns, _log(y(i)/y(i-1))_, are specified to follow a StudentT distribution, where _y_ is described as the daily returns series, but I think it should be described as the daily _price_ series; then this would make _log(y(i)/y(i-1))_ the daily (log) _returns_ series.

Also, is _exp(−2s(i))_ meant to be the scale or the _squared precision_ of the StudentT distribution? In the code, the third parameter of the initializer for the StudentT class is the scale, but if _s(i)_ is meant to be a log volatility, i.e. s(i) = log v(i) for volatility v(i), then _exp(−2s(i))_ is 1/(v(i)^2), which makes the parameter look like a squared precision. The code defines the returns r as:

`r = pm.StudentT('r', nu, lam=pm.math.exp(-2*s), observed=returns)`

In the second example, _y_ is again a returns series, but now _log(y(i))_ is specified to follow a StudentT distribution, and the example is implying that the log of the returns is distributed StudentT, which sounds plain wrong.

Also, an intermediate deterministic variable `volatility_process` is introduced:

`s = pm.GaussianRandomWalk('s', sigma**-2, shape=len(returns))`
`volatility_process = pm.Deterministic('volatility_process', pm.math.exp(-2*s))`

`r = pm.StudentT('r', nu, lam=1/volatility_process, observed=returns)`

and now the scale of the StudentT distribution is effectively _1/pm.math.exp(-2*s)_, which is very confusing. Does this look strange to anyone else, or am I not getting enough sleep? ;)

**Comment by yongsua1989** [comment]
Damn, I was working with the second example. Thanks for pointing out. Someone please help, I need help to complete my assignment.

**Comment by yongsua1989** [comment]
Besides, I would like to know if stochastic volatility model can be applied to price volatility (without percentage of change) too instead of return volatility. Thanks.

**Comment by junpenglao** [comment]
I am not completely familiar with this example, but I think you should follow the second one as it is in the PyMC3 paper. @twiecki ?

We should probability remove the first one as it is redundant.

**Comment by yongsua1989** [comment]
I am not maths pro but I think the second example should be correct. Since the lambda value for sigma and degrees of freedom(nu or v) were given with 1/0.02 and 1/10 for exp(50) and exp(0.1) respectively as required by the example, then logically the lambda value for student's T should also be 1/exp(-2*s) possibly due to the analogy of comparing between apple and apple.

**Comment by aaronjmaxwell** [comment]
I haven't walked through each step by step, but here are the differences that are visible to me:

1. Example 1 uses *r* as opposed to *y* to model the returns, so the difference is really just nomenclature.  They both pass the returns variable as the observations to the Students T distribution.
2. Example 1 uses *step_size* as the standard deviation, while Example 2 uses *sigma*.   In PyMC3, GaussianRandomWalk interprets the first argument as the precision, so Example 2 passes 1 / *sigma*^2, while Example 1 passes it as *sigma*.  Again, the difference is nomenclature, with the different ways to pass the variable being a feature of python.
3. This is where the break happens.  The docs for GaussianRandomWalk state that *lambda* is the precision of the Students T distribution.  Thus, Example 1 treats *s* as the log-root of the precision (ln[1 / stddev]) while Example 2 treats *s* as (ln[stddev]).  You can see this because in the Deterministic (which I assume has been used in Example 2 to force the trace to store *s*) the equation
`pm.math.exp(-2*s)`, with `s = ln[v]`, evaluates to `v^-2`.  So Example 1 passes this directly (thus treating it as the precision) while Example 2 passes the inverse of this (thus treating it as the variance).

This last difference can be confusing, because it represents a disconnect between what the author stated the model should look like mathematically, and what they actually constructed.  This needs to be fixed (either by swapping signs in the Deterministic or by passing `lam=volatility_process`).  Furthermore, Example 2 comes at the end of the `Getting Started` page whereas Example 1 is found under the Stochastic Volatility model.  So if you delete Example 1, you may want to think about routing users in the help docs to the relevant point on the `Getting Started` page.

**Comment by twiecki** [comment]
@aaronjmaxwell Good catch, want to fix the language to say variance?

**Comment by aaronjmaxwell** [comment]
Sure @twiecki.  Which one?  Is there anything else you want me to edit?

**Comment by twiecki** [comment]
@aaronjmaxwell The code in the NB is the master version so everything should be harmonized with that.

**Comment by aaronjmaxwell** [comment]
I'm unsure of the best way to do this.  Quite honestly, it's as simple as deleting the minus sign when the model is specified using the mathematical notation.  Under:
#Getting started with PyMC3
## Case study 1: Stochastic volatility
### The Model
simply replace `\log(y_{i}) \sim t(\nu, 0, \exp(-2s_{i})` with `\log(y_{i}) \sim t(\nu, 0, \exp(2s_{i})`.  This relieves the need of re-writing the NB code, since the code itself treats `s_{i}` as the root of the precision rather than the root of the variance.  However, since I'm unfamiliar with the original intention of the model used in the NUTS paper, I'm wary of making this change.  Is the log-volatility really defined as the variance?  If so, then the `with pm.Model() as sp500_model:` block needs to be changed and the whole model needs to be re-run.

In any case, this becomes a moot point if you consider the whole point of the doc is to give you an example of how to use `GaussianRandomWalk`.  The actual break between the model specification and what's stated in the text isn't that important.  Many of the OP's questions were due to the use of variable annotations, what `pymc3.Deterministic` is, and how the distributions are defined in PyMC3.  Much of this is actually field dependent - as a physicist, I call it the Gaussian distribution and I always use variance, not precision.  Unless the OP or project Owner objects, I think this issue should be closed.

**Comment by twiecki** [comment]
@aaronjmaxwell Want to do a small PR for this change?

**Comment by aaronjmaxwell** [comment]
Okay.  I'm basically going to copy and past my rationale in the PR.  Hopefully I don't break your notebooks, because I love `PyMC3` and I wish I'd know about it when I was doing my PhD.

**Comment by twiecki** [comment]
Good to hear :).

**Comment by aaronjmaxwell** [comment]
All right, PR is in.  It's now in the hands of you and the other wonderful maintainers, @twiecki.

**Comment by junpenglao** [comment]
close by #2978
