### ISSUE TITLE
Beta RV outside its support with pm.find_MAP

### ISSUE THREAD

**Issue by mcavallaro** [pymc-devs/pymc#2618]
While investigating problems in my model,  I found that the MAP estimate of a simple Beta random variable falls at the boundary of its support.

    with pm.Model() as beta_model:
        B = pm.Beta('B', alpha=0.2, beta=0.00002)
        MAP = pm.find_MAP()

    >> MAP
    {'B': array(1.0), 'BB_logodds__': array(30.210340371976017)}

    >>beta_model.logp(MAP)
    array(-inf)

I know that is based on extreme values for the parameters (my data seem to select for such values), but I think that it's an issue.

Seems similar to issue #334.

Can this also create problems during the inference with NUTS?

* How did you install PyMC3: (conda/pip) I'm using the current version as installed with pip from github

**Comment by bwengals** [comment]
You can do `conda install pymc3`.  I think soon there will be a new version available, so you are basically up to date using pip from github either way.

Like you said, those parameters in a Beta distribution produce an extremely(!) narrow posterior.   Minimization routines and something like NUTS in general will have a very hard time with parameters that are highly constrained like this.  Is it possible to consider the value of this parameter as known, since the uncertainty here is so small?  If not, can you reparameterize somehow so that the width of its posterior is in a nicer range, like -2ish to 2ish?

**Comment by aseyboldt** [comment]
The MAP is at 1 with a density of `+inf`, with #2622 that should be fixed now.
In general looking at the map really isn't useful here. Sampling with NUTS won't work well, I think that is because of numerical issues in the gradient.

@mcavallaro You might want to try and work on the logit scale directly in a case like this.
