### ISSUE TITLE
Sampling problems with a multinomial + poisson prior on n

### ISSUE THREAD

**Issue by jefio** [pymc-devs/pymc#2734]
## Description of your problem

When defining the following model, all samples of N are equal to 10:
N ~ Poisson(10)
X ~ Multinomial(N, p=[0.7, 0.3])

**Please provide a minimal, self-contained, and reproducible example.**

```
import numpy as np
import pymc3 as pm

with pm.Model() as model2:
    n = pm.Poisson('n', mu=10)
    x = pm.Multinomial('x',
                       n=n,
                       p=np.array([0.7, 0.3]),
                       shape=2)
    trace = pm.sample(10000)

print(trace['n'][-20:])
print(np.all(trace['n'] == 10))
```

```
Assigned Metropolis to n
Assigned Metropolis to x
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10500/10500 [00:02<00:00, 4079.75it/s]
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
True
```

**Please provide any additional information below.**

The equivalent model, using the binomial distribution instead of the multinomial, works as expected.

```
import numpy as np
import pymc3 as pm

with pm.Model() as model1:
    n = pm.Poisson('n', mu=10)
    x = pm.Binomial('x',
                    n=n,
                    p=0.7)
    trace = pm.sample(10000)

print(trace['n'][-20:])
```

```
Assigned Metropolis to n
Assigned Metropolis to x
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10500/10500 [00:02<00:00, 4637.29it/s]
[ 6  6  6  6  6  6  6  8  8  8  8  8  9  9  9  9 12  8  9 10]
```

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291
* Python Version: 3.6.0
* Operating system: macOS 10.13.1
* How did you install PyMC3: conda

**Comment by fonnesbeck** [comment]
Yes, I can confirm this. Thanks for reporting.

**Comment by jefio** [comment]
So I managed to narrow it down (a bit). From the `Multinomial` class:

```python
    def logp(self, x):
        n = self.n
        p = self.p

        return bound(
            factln(n) + tt.sum(-factln(x) + logpow(p, x), axis=-1, keepdims=True),
            tt.all(x >= 0),
            tt.all(tt.eq(tt.sum(x, axis=-1, keepdims=True), n)), # <--- PROBLEM HERE!!
            tt.all(p <= 1),
            tt.all(tt.eq(tt.sum(p, axis=-1), 1)),
            tt.all(tt.ge(n, 0)),
            broadcast_conditions=False
        )
```

https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L641

The goal is to sample from the following distribution:
N ~ Poisson(10)
X ~ Multinomial(N, p=[0.7, 0.3])

When we run the script from the first post, initially N = 10 and X = [7, 3]. Then, something like this happens:
- sample X
  - If for example the candidate value is [6, 3], it will always be rejected because the sum 6 + 3 is less than 10:`tt.all(tt.eq(tt.sum(x, axis=-1, keepdims=True), n)) = False --> logp(X = [6, 3]) = -inf --> delta_logp = -inf --> [6, 3] is rejected --> X_new = [7, 3]`
  - If for example the candidate value is [6, 4], then it may be accepted or rejected (no problem here)
  - Either way the new value for X is always such that it sums to 10
- sample N
  - Because `sum(X) = 10`, any value other than 10 for N will be rejected for the same reason as above: `tt.all(tt.eq(tt.sum(x, axis=-1, keepdims=True), n)) = False --> ...`

So we can see why `N=10` in all samples. Not sure how to fix this...

**Comment by jefio** [comment]
No fix?

**Comment by twiecki** [comment]
we did a bunch of fixes, did you test that it still exists?

**Comment by twiecki** [comment]
if yes, please reopen.

**Comment by twiecki** [comment]
cc @lucianopaz

**Comment by jefio** [comment]
> we did a bunch of fixes, did you test that it still exists?

Yes the issue still exists with the latest version of the code (ef39aed02072a308b40f86dfaac12049e25d465d)

**Comment by lucianopaz** [comment]
I'm definitely not familiar enough with the step methods involved. I don't know if the step order of `n` and `x` is at all relevant, nor if the energy of the proposed changes is evaluated after each individual step and then summed, or if the energy of the entire configuration change is evaluated after all the steps were done. If the latter is the case, then you should eventually see a change in `n` during the trace sample and the reason the changes are so unlikely maybe is because it is hard to get `n` and `sum(x)` to match with independent metropolis proposals. If you do not see any change in `n` at all, then this could mean that the step order is relevant and individual steps are rejected immediately before seeing if the global step configuration of `n` and `sum(x)` are compatible.

One hackish possibility is to step all the `x` elements except the last one, and set it equal to `n - sum(x[:-1])`. We could just test that all `x` are greater than zero and that `sum(x[:-1]) < n` instead of the hard sum equality condition (which is kind of what `Binomial` does). Another possibility could be to write a new step class for multinomial, which defers the step of `n` to be executed first and then makes a proposal of `x` the that is compatible with `n`. As I said, I'm not familiar enough with the step methods to implement either of them now. When I come back from the winter holidays, I call look at this, but it will take a while before I'm able to fix this. Maybe someone else more experienced with the step methods can take a look at this issue first.

**Comment by jefio** [comment]
> I'm definitely not familiar enough with the step methods involved. I don't know if the step order of `n` and `x` is at all relevant, nor if the energy of the proposed changes is evaluated after each individual step and then summed, or if the energy of the entire configuration change is evaluated after all the steps were done.

The issue may be caused by the [Metropolis-within-Gibbs sampler](https://docs.pymc.io/developer_guide.html#mcmc) implemented by `CompoundStep`, where a new point is sampled using MH for each random variable in the model: (x0, y0, z0) --> MH on x --> (x1, y0, z0) --> MH on y --> (x1, y1, z0) --> MH on z --> (x1, y1, z1). This approach does not work for sampling from the Poisson / Multinomial, as `n` and `sum(x)` become interlocked by the equality constraint.

> One hackish possibility is to step all the `x` elements except the last one, and set it equal to `n - sum(x[:-1])`. We could just test that all `x` are greater than zero and that `sum(x[:-1]) < n` instead of the hard sum equality condition (which is kind of what `Binomial` does). Another possibility could be to write a new step class for multinomial, which defers the step of `n` to be executed first and then makes a proposal of `x` the that is compatible with `n`. As I said, I'm not familiar enough with the step methods to implement either of them now. When I come back from the winter holidays, I call look at this, but it will take a while before I'm able to fix this. Maybe someone else more experienced with the step methods can take a look at this issue first.

I wonder if this problem could also be solved at the model level (rather than at the distribution level). One would need to identify models for which the Metropolis-within-Gibbs sampler is not appropriate (based on my first post, that would include all models containing a multinomial distribution where the parameter `n` is a random variable), and call a different sampler for them (maybe just vanilla MH). Looking at [`Metropolis.astep`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/metropolis.py#L139), this may involve decoupling the code generating a candidate point from the code accepting / rejecting it.

**Comment by brandonwillard** [comment]
> > 
> 
> I wonder if this problem could also be solved at the model level (rather than at the distribution level). One would need to identify models for which the Metropolis-within-Gibbs sampler is not appropriate (based on my first post, that would include all models containing a multinomial distribution where the parameter `n` is a random variable), and call a different sampler for them (maybe just vanilla MH). Looking at [`Metropolis.astep`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/metropolis.py#L139), this may involve decoupling the code generating a candidate point from the code accepting / rejecting it.

FYI: This is exactly the kind of situation in which symbolic optimizations/rewritings are appropriate.  In general, the same is true of all estimation approaches&mdash;like Gibbs samplers&mdash;that work by using an equivalent model that lends itself to better and/or direct conditional sampling.

**Comment by ricardoV94** [comment]
It seems to me that although this is a real limitation in the Metropolis step algorithm / Multinomial parametrization, there might be no good practical reason to change either in order to accommodate this specific example. 

If a Multinomial (under the current parametrization) is observed there can be no ambiguity about what `n` is. For a latent Multinomial, the question is when would it really be useful to have one? I fail to see what is the benefit of having an integer output as opposed to something in the same ballpark like this:

```python
n = pm.Poisson('n', mu=10)
p = pm.Dirichlet('p', a=np.array([0.7, 0.3]), shape=2)
x = pm.Deterministic('x', n * p)  # result can also be rounded if integers are really needed
```

If one desires a more flexible Multinomial, it may be achievable by reparametrizing it as `k-1` Binomials, as described in here: https://discourse.mc-stan.org/t/multinomial-distribution/17330/4

I am closing this again, but if anyone thinks that such reparametrization / change to the step algorithm is really useful feel free to reopen it :)
