### ISSUE TITLE
TypeError in Normal

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#293]
I get a strange `TypeError` when using a Normal as a stochastic with stochastic parents. For example, if I am trying to draw from the posterior predictive distribution:

```
diffs = Normal("diffs", mu=mu, tau=tau, observed=y)
diff_pred = Normal("diff_pred", mu=mu, tau=tau)
```

I get the following when I specify the model (i.e. before sampling):

```
/Users/fonnescj/Code/pymc3/pymc/distributions/continuous.pyc in logp(value)
    106 
    107         return bound(
--> 108             (-tau * (value - mu) ** 2 + log(tau / pi / 2.)) / 2.,
    109             tau > 0)
    110 

TypeError: unsupported operand type(s) for -: 'TensorVariable' and 'TensorVariable'
```

Surely we can subtract tensors from one another?

**Comment by jsalvatier** [comment]
Yes, I think this is a theano bug. I thing the actual error is somewhere else, but the error gets caught and then thrown so that this error shows. I've had this error when the test values didn't line up with the shape of the variable. 

I would make a theano issue if you can find a good way to replicate it. The easiest way to debug the issue is going to be to catch all thrown errors (even uncaught ones) in a debugger. PyDev for Eclipse can do that.

**Comment by jsalvatier** [comment]
Are you continuing to have this problem?

**Comment by fonnesbeck** [comment]
Yes, but I have not had time to dig around to figure it out yet. I'm at SciPy this week, so I should be able to have a look at it.

**Comment by twiecki** [comment]
Closing. Feel free to reopen if problem persists.
