### ISSUE TITLE
Using a discrete distribution as index

### ISSUE THREAD

**Issue by 1pakch** [pymc-devs/pymc#3056]
I am wondering why this

```python
x = np.array([0.3, 0.2, 0.1, 0.6, 0.9, 0.2])
mu = np.array([0.1, 0.9])
tmu = t.shared(mu)
with pm.Model() as model:
    pLeft = pm.Beta('pLeft', mu=0.1, sd=0.1)
    LeftRight = pm.Binomial('LeftRight', p=pLeft, n=x.shape[0])
    pLI = pm.Beta('pLI', mu=tmu[LeftRight], sd=0.1, observed=x)
```
fails to work (with indexing errors reported from Theano). It works when rewritten as

```python
    #...
    LeftRight = pm.Categorical('LeftRight', p=tt.stack([pLeft, 1-pLeft]), shape=x.shape[0])
    pLI = pm.Beta('pLI', mu=tmu[LeftRight], sd=0.1, observed=x)
```

and I am wondering if one can use discrete RVs directly for subindexing or why one can't.

#### Versions
pymc 3.2
Theano 1.0.2

**Comment by junpenglao** [comment]
`pm.Binomial('LeftRight', p=pLeft, n=x.shape[0])` will return a discrete value between 0 and n, when the return is >1 the indexing of `tmu[LeftRight]` would fail. 
What you are looking for is probably `LeftRight = pm.Bernoulli('LeftRight', p=pLeft, shape=x.shape[0])`.

Since this is not a bug I am closing for now. In the future, if you have use case question please post to https://discourse.pymc.io/

**Comment by 1pakch** [comment]
Sorry, I meant to use Bernoulli of course and it works.
