### ISSUE TITLE
Pyflakes and pycodestyle return many warnings

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#3063]
Hello,
The contributing guide mention using pyflakes and pycodestyle to check for warnings in the codebase

When I run this though on the master branch I get a lot of warnings. 

Is my output correct? If so should these be resolved per the contributing guide?

The warnings I get are attached below
[pycodestyle_warnings.txt](https://github.com/pymc-devs/pymc3/files/2139755/pycodestyle_warnings.txt)
[pyflakes_warnings.txt](https://github.com/pymc-devs/pymc3/files/2139756/pyflakes_warnings.txt)

**Comment by eigenfoo** [comment]
Referring to https://github.com/pymc-devs/pymc3/issues/3307#issuecomment-449808060 and https://github.com/pymc-devs/pymc3/pull/3239#issuecomment-433693309.

The tldr is that, since refactoring code for style would touch many lines in the code base, a simple git blame would not come up with anything useful. By all means we should write pep8-comformant code going forward, but touching everything to conform to PEP8 is a bit extreme.

Closing this issue now, but please reopen if you have something to add!
