### ISSUE TITLE
DiscreteUniform distribution documentation should explicitly call out exclusion of upper

### ISSUE THREAD

**Issue by benyi1981** [pymc-devs/pymc#3074]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem

Just calling out a minor mistake in the documentation of DiscreteUniform distribution:
https://docs.pymc.io/api/distributions/discrete.html#pymc3.distributions.discrete.DiscreteUniform

It would be clearer to explicitly call out that the upper value is NOT being sampled. Therefore, this is incorrect:
x∈lower,lower+1,…,upper

It should be:
x∈lower,lower+1,…,upper-1

Otherwise, the total probability of the distribution would sum to >1.

## Versions and main components

* PyMC3 Version: 
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by junpenglao** [comment]
Good catch. Would you like to submit a pull request to fix this?

**Comment by canyon289** [comment]
@benyi1981 If you'd like I would be happy to make the edit and submit a PR. Let me know what you'd like me to do

**Comment by benyi-mikara** [comment]
I'd love to make the PR and make a contribution to this community. However, I've never done it before. Please bear with me while I try it.
@canyon289 thanks for volunteering - I might come to you for help!

**Comment by benyi-mikara** [comment]
On further investigation, it appears that the code is inclusive of both lower and upper. So the mistake is in the pmf calculation (should be upper-lower**+1** )  

Before I make the PR, should I commit to the master branch, or is there another branch I should use? thanks.

**Comment by canyon289** [comment]
hey @benyi-mikara for the couple of pull requests I performed I basically followed this procedure

1. Fork pymc3
2. Make a branch
3. Make the fixes
4. If needed rebase to the latest pymc3 repo/master commit
5. Submit from your forked repo to the pymc3 master

This contributing guide is really good and explains that above plus more
https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md

**Comment by eigenfoo** [comment]
Hello @benyi-mikara! Do you still need help with submitting a PR? We're always here if you need anything.

**Comment by vbsinha** [comment]
@junpenglao Can I take up this issue? From what I understand, `upper` is not sampled. This means that we would need to replace `upper` by `upper - 1` in all the formulae (pmf, support, mean and variance) in the documentation. 

I think that the pmf [graph](https://docs.pymc.io/api/distributions/discrete.html#pymc3.distributions.discrete.DiscreteUniform) in the documentation is also off. It shows that the pmf takes the value 0 at all x's. I think this error is because `/` returns int in python 2 if both operands are ints. Moreover, the graph also takes the value of `upper`, which should be modified.
