### ISSUE TITLE
TypeError: No context on context stack

### ISSUE THREAD

**Issue by dongfeng951** [pymc-devs/pymc#3251]
I have a problem. I run the example code of sample statistics from https://docs.pymc.io/notebooks/sampler-stats.html.
The code is
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import pandas as pd
import pymc3 as pm
model = `pm.Model()`
with model:
    mu1 = pm.Normal("mu1", mu=0, sd=1, `shape=10)`
with model:
    _step = pm.NUTS()_
    trace = pm.sample(2000, tune=1000, init=None, step=step, cores=2)
However,  "step = pm.NUTS()" raises an error "TypeError: No context on context stack". What is the problem? 
Thank you1

**Comment by lucianopaz** [comment]
The code you posted is not properly indented, and this may be the cause of your problem. Check what happens if you run:

```python
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import pandas as pd
import pymc3 as pm

with pm.Model() as model:
    mu1 = pm.Normal("mu1", mu=0, sd=1, shape=10)
    step = pm.NUTS()
    trace = pm.sample(2000, tune=1000, init=None, step=step, cores=2)
```

It's important to have the calls to `pm.Normal`, `pm.NUTS()` and `pm.sample` inside a model's context. That means that they must be in the indented block of a `with model:` statement.

**Comment by dongfeng951** [comment]
Hi,I got it. Thank you very much!

**Comment by thinkuxdesign** [comment]
Got I did the same mistake, glad I check it first. Thanks a lot as well.
