### ISSUE TITLE
Flake8 Warnings

### ISSUE THREAD

**Issue by rsdel2007** [pymc-devs/pymc#3307]
I run the flake8 tests on the cloned repository and found that the code is filled with these warnings:
**E501** 
**E306**
**F841** 
**E231** 
**E301**
**E128**
**W291**
**W293**
**F401**
**E127**
**W391**
**F305**
**E203**
**E303**
**E741**
**E305**
**W605**
**E302**
**F401**
**E261**
**E225**
**E124**
**E114**
**E116**

I will be happy to fix some of them.

### Versions and main components

* PyMC3 Version:3.5
* Theano Version: 1.0.3
* Python Version: 3.6.5
* Operating system: ubuntu 16.04
* How did you install PyMC3: pip

**Comment by eigenfoo** [comment]
Hello @rsdel2007!

I like to have style-conformant code as much as anybody, and a simple `autopep8` would probably fix all these warnings. However, the PyMC project has been here before: https://github.com/pymc-devs/pymc3/pull/3239#issuecomment-433693309.

The tldr is that, since refactoring code for style would touch many lines in the code base, a simple `git blame` would not come up with anything useful. By all means we should write pep8-comformant code going forward, but touching everything to conform to PEP8 is a bit extreme.

@aseyboldt unless you disagree, I think we should close this?
