### ISSUE TITLE
Documentation for inverse estimation

### ISSUE THREAD

**Issue by ckrapu** [pymc-devs/pymc#3326]
In a [recent post on Discourse](https://discourse.pymc.io/t/multilevel-model-how-to-model-outcome-at-the-group-level/2446), a user asked for an explanation of how to do inverse estimation. Since the solution is (I think) especially straightforward thanks to PyMC3's design, it might be nice to have a documentation Jupyter notebook showing how to do inverse estimation of covariates for linear regression. I'm happy to write that up if it seems like a good idea.

**Comment by eigenfoo** [comment]
@ckrapu that sounds wonderful! Were you thinking of doing inverse estimation for linear regression covariates, or doing inverse estimation/estimating missing data more generally? Both would be great additions to the documentation, but I just ask to see where we should add this.

If the former, I think it makes sense to add it to the linear regression notebooks (e.g. perhaps adding a `Inverse Estimation of Covariates` section in [this notebook](https://docs.pymc.io/notebooks/GLM.html)), instead of making a new notebook for it.

If the latter, I think a `Modelling Missing Data` notebook deserves to be its own case study.

**Comment by twiecki** [comment]
@ckrapu Yes, that'd be much appreciated. I'll close this as it'd be mostly be a todo for you at this point, but feel free to keep discussing in this thread.
