### ISSUE TITLE
sample _prior_predictive samples both prior and prior predictive

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#3592]
## Description of your problem

`pm.sample_prior_predictive` samples both the prior and the prior predictive. It may be useful for users to add an `include` argument to choose between the two, or some `excluded_vars` argument or to follow ArviZ's variable negation notation of adding `~` before the variable name. 

Related to #3591.

**Comment by ricardoV94** [comment]
Is there a demand for this option? If so it looks very straightforward to implement.

**Comment by ricardoV94** [comment]
@OriolAbril Do you still think this is a needed feature? Users can specify what variables to sample explicitly, although that can be tedious for large models as you need to enumerate them all. 

Otherwise, I haven't seen people requesting this type of feature on the discourse at least. What do you think?

**Comment by OriolAbril** [comment]
With inferencedata backend it doesn't matter much. The two reasons for this, users getting confused and not understanding the difference between prior and prior predictive and complications with prior predictive checks, dist comparison and so on,  are no longer relevant.

**Comment by ricardoV94** [comment]
Alright, so I'll close this one :)
