### ISSUE TITLE
Docs to numpydoc convention

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#3713]
Right now, running 

```bash
$ python -m pydocstyle --convention=numpy pymc/ | wc -l
3090
```
Shows 3090.

It would be a bit much to try to fix all this at once, but a helpful contribution would be to:

1.  fix one directory at a time: use `python -m pydocstyle --convention=numpy pymc3/path/to/directory/` and do what the suggestions say
2. add `python -m pydocstyle --convention=numpy pymc3/path/to/directory/` to `pymc3/scripts/lint.sh`
3. make a PR 
4. repeat.

**Comment by eigenfoo** [comment]
I think the reason this issue has been so persistent is because there are quite a few `D10X: Missing docstring in X function` errors. This is pretty bad because missing docstrings should definitely be failing _some_ test, so should we could agree to fix up the stylistic issues, and allow missing docstrings to fail the lint build?

**Comment by michaelosthege** [comment]
When the roadmap is clear, I'd like to help with this one.

**Comment by ricardoV94** [comment]
@OriolAbril Is this issue still relevant?

**Comment by OriolAbril** [comment]
probably yes, hopefully we don't have that many errors now though.

**Comment by ricardoV94** [comment]
Closing in favor of #6378
