### ISSUE TITLE
Metropolis chain tuning is differs between single- and multiprocessing

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#3733]
(split from #3731)

### Observations
When `Metropolis` is used with `cores > 1 and chains > 1`, all chains are independently tuned.

With `cores=1` however, `Metropolis` initializes the 2nd chain with the `scaling` from the first. It is still tuned, but in the end it's a different between sequential single-process and parallelized multiprocess sampling.

### Cause
For `Metropolis`, the stepper is re-used and re-tuned, but no reset happens.

https://github.com/pymc-devs/pymc3/blob/dc9fd7251b34e9851308e91d622513ebe648f49e/pymc3/sampling.py#L711-L716

### Possible Solutions
+ re-setting the tuning parameter before continuing with the next chain
+ ...other ideas?

**Comment by ColCarroll** [comment]
Wow, this is interesting.

1. This is definitely a bug, in that it is different behavior due to settings that have nothing to do with tuning. I think we should reset the tuning parameter (or just initialize a new stepper?) before continuing.
2. More generally, sharing tuning data between chains does not seem like a bad idea to me, either as an early diagnostic (if you just compare them), or to speed up tuning (like here, we have a "good initialization" for scaling).

**Comment by michaelosthege** [comment]
Over in #3784 I fixed it for the `DEMetropolisZ`. Shall I include a fix for `Metropolis` in the same PR ?

**Comment by junpenglao** [comment]
I think it is better sending a separate PR.
