### ISSUE TITLE
Switching between draws/s and s/draws

### ISSUE THREAD

**Issue by jtrakk** [pymc-devs/pymc#3757]
## Description of your problem

Sometimes the sample rate is shown in units of `draws/s` and sometimes it's in `s/draws`. For example, [this notebook](https://github.com/pymc-devs/pymc3/blob/55ccacf2105f1c37fc49999b5417ab1086c0243d/docs/source/notebooks/GLM-logistic.ipynb) from the docs has both 

`
Sampling 2 chains: 100%|██████████| 4000/4000 [56:48<00:00,  1.12s/draws]  
`
and 
`
Sampling 2 chains: 100%|██████████| 4000/4000 [16:13<00:00,  3.05draws/s] 
`
**Please provide a minimal, self-contained, and reproducible example.**

It would be easier to understand the output if it maintained a consistent unit rather than switching back and forth depending on the value. 

Would it make sense to consistently report `draws/s`?

## Versions and main components

* PyMC3 Version: 3.7
* Theano Version:
* Python Version: 3.7
* Operating system:
* How did you install PyMC3: (conda/pip) conda

**Comment by eigenfoo** [comment]
As far as I can tell, this is default behavior from `tqdm` or `fastprogress`, and not an issue with PyMC3 directly. I believe that they occasionally invert numbers in order to make the numbers more interpretable: for example, with really slow sampling, I would prefer to know that it's `13.2 s/draw` instead of `0.075 draws/s`, even though they mean the same thing. Contrariwise, with really fast sampling, I would rather know that I'm having `13.2 draws/s` instead of `0.075 s/draw`

Theoretically, `tqdm` allows you to modify this behavior with the [`bar_format` argument](https://tqdm.github.io/docs/tqdm/#9595init9595), so we could allow users to customize this behavior if they so choose, but I'm not convinced that modifying the default behavior is a good idea.

@jtrakk what do you think? I'm very much open to changing my mind!

**Comment by ericmjl** [comment]
@eigenfoo has the best explanation I’ve seen of this behaviour. Closing this issue for now, but please feel free to re-open if there’s further questions.

**Comment by fonnesbeck** [comment]
@jtrakk we've recently switched from tqdm (the progressbar in the current release) to fastprogress. Any customization to the progressbar would have to be via pull requests to the fastprogress project directly. It may be in our long term interest to fork the project to make it suit our needs.
