### ISSUE TITLE
GaussianRandomWalk prior predictive is broken

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#3962]
## Description of your problem
When running a `sample_prior_predictive` for a `GaussianRandomWalk`, the result looks not even close to what one would expect:

```
x = numpy.arange(0, 10)
with pymc3.Model() as pmodel:
    grw = pymc3.GaussianRandomWalk('grw', mu=0, sd=1, shape=len(x))
    pp = pymc3.sample_prior_predictive()
fig, (left, right) = pyplot.subplots(ncols=2, figsize=(10,5))
for i in numpy.random.randint(0, 500, size=40):
    left.plot(x, pp['grw'][i,:])
left.set_title('sample_prior_predictive')    
for _ in range(50):
    right.plot(x, grw.random())
right.set_title('.random()')
pyplot.show()
```

![image](https://user-images.githubusercontent.com/5894642/84579474-54745600-adce-11ea-8fc8-5f7bfde107da.png)

## Versions and main components
* PyMC3 Version: latest master
* Theano Version: the one and only
* Python Version: 3.6.8
* Operating system: Windows
* How did you install PyMC3: pip

**Comment by Rish001** [comment]
I would like to work on this

**Comment by Rish001** [comment]
So far I have been able to tie the starting point of the lines of sample_prior_predictive() plot at 0. PFB the attached screenshot of the result.
![image](https://user-images.githubusercontent.com/21169674/86034547-6dc90380-ba58-11ea-896b-fa15c236d4c2.png)

The issue was that in the _random() function of Gaussian Random Walk, `data = data - data[0]` produced intended line starting from 0 for 1d array. However, for 2d array this caused the first row of the 2d array to turn 0.
![image](https://user-images.githubusercontent.com/21169674/86035103-59393b00-ba59-11ea-8c86-350c167bfb9c.png)

After altering the code now it is
![image](https://user-images.githubusercontent.com/21169674/86035386-e54b6280-ba59-11ea-887b-7d0e41175a0d.png)


Will this do the job?

**Comment by Rish001** [comment]
So far I have been able to tie the starting point of the lines of sample_prior_predictive() plot at 0. PFB the attached screenshot of the result.
![issue](https://user-images.githubusercontent.com/21169674/86035662-5723ac00-ba5a-11ea-88c6-58bf903170c2.png)


The issue was that in the _random() function of Gaussian Random Walk, data = data - data[0] produced intended line starting from 0 for 1d array. However, for 2d array this caused the first row of the 2d array to turn 0.

is this fine now?

**Comment by twiecki** [comment]
@Rish001 No, there is this weird correlation between instantiations that is quite puzzling. The left plot should look as random as the right.

**Comment by Rish001** [comment]
@twiecki I suspect the issue lies in the internal workings of the method `.rvs(size)` of scipy when size is 2d. When I invoked the same method in a loop for each row of the 2d matrix, it generated the expected plot. PFB the screenshot attached
![image](https://user-images.githubusercontent.com/21169674/86047304-53008a00-ba6c-11ea-9ea7-dae6bb182470.png)

PFB the code snippet for the 2d matrix
`data = np.empty(size)
            for i in range(size[0]):
                data[i] = rv.rvs((size[1],)).cumsum(axis = axis) 
                data[i] = data[i] - data[i][0]`

**Comment by michaelosthege** [comment]
> @twiecki I suspect the issue lies in the internal workings of the method `.rvs(size)` of scipy when size is 2d. When I invoked the same method in a loop for each row of the 2d matrix, it generated the expected plot. PFB the screenshot attached
> ![image](https://user-images.githubusercontent.com/21169674/86047304-53008a00-ba6c-11ea-9ea7-dae6bb182470.png)
> 
> PFB the code snippet for the 2d matrix
> `data = np.empty(size) for i in range(size[0]): data[i] = rv.rvs((size[1],)).cumsum(axis = axis) data[i] = data[i] - data[i][0]`

That looks promising!
What if the shape is reversed (and the result transformed)? 
If that doesn't help, do you think it's a scipy bug that should be reported?

**Comment by Rish001** [comment]
@michaelosthege I believe its a valid issue that should be reported to scipy.

**Comment by WarrenWeckesser** [comment]
I just commented on the scipy issue (https://github.com/scipy/scipy/issues/12482).  It looks like the problem is actually in PyMC3; apparently the [`_random`](https://github.com/pymc-devs/pymc3/blob/1bf867edf74e1c5fc0db79a4f0ca4e2bdab94e66/pymc3/distributions/timeseries.py#L305) method in `GaussianRandomWalk` is not performing the cumulative sum along the correct axis.

**Comment by AlexAndorra** [comment]
Thanks a lot @WarrenWeckesser ! Don't know how I missed that 🤦
