### ISSUE TITLE
Timeseries distributions lack a `random` method

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/pymc#3964]
None of our [time series distributions](https://docs.pymc.io/api/distributions/timeseries.html) have a `random` method implemented, except for `GaussianRandomWalk` -- and even then, there seems to be a problem with `sample_prior_predictive`, see #3962.

As a result, these distributions cannot be used in prior predictive sampling, and in posterior predictive sampling when they are `observed`.
Adding a `random` method to these distributions would thus be a valuable contribution!

**Comment by Rish001** [comment]
Hi I want to work on this

**Comment by AlexAndorra** [comment]
Thanks @Rish001 ! Which distributions would you like to work on?

**Comment by Rish001** [comment]
Firstly I would like to fix #3962 and then move on to creating 'random' method for AR1 process.

**Comment by AlexAndorra** [comment]
Great! Good coding and tell us if you have any questions 🖖

**Comment by NowanIlfideme** [comment]
During my master's thesis work I made some [AR model generators](https://github.com/NowanIlfideme/masters_switching_models/blob/master/regime_switching/fit/ar.py) that might be useful to look into, though the parametrization is a bit more general (N-dimensional VARX processes 😛). There are some problems I ran into though:

* Do you generate a posterior sample of the entire process (e.g. from timestep `0` onwards), a conditional one (i.e. allow fixing values and generate continuations of the process from timestep `t`), or something else? I decided then to generate posteriors of the entire process, which is probably the expected case. However, this makes it harder to use for "rolling validation" and such, because you must recreate the model every time rather than using `pm.Data`. I'm not sure the best way to do that otherwise.

* I couldn't figure out how to change the process shape when changing input data, e.g. when doing AR with exogenous regressors and trying to predict ahead. This is the problem with all time series processes, actually - the best I could come up with is to manually remove the samples for the `time_series_process` from the trace and forcing the random method.

Any thoughts on those two? Also I hope the code is helpful; I wanted to contribute a modification of it to pymc3, but felt it was too out-of-line from the other repo code & would take too much time from me to refactor...

**Comment by AlexAndorra** [comment]
Closing in favor of #4337
