### ISSUE TITLE
Shape Issues

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4114]
Linking all shape issues tickets together

https://github.com/pymc-devs/pymc3/issues/2326
https://github.com/pymc-devs/pymc3/issues/4029

**Comment by kc611** [comment]
#3007  and #3631 also seems to fit this list

**Comment by martintb** [comment]
I am also experiencing this issue. I'll add to this that if I specify the coords of the model and dims for my RVs I can work around this issue but the NUTS sampling seems to get much slower. Happy to provide more information if it would be helpful.

**Comment by twiecki** [comment]
@martintb Please do.

**Comment by martintb** [comment]
So, my model was a bit complicated and messily implemented, but I was able to adapt an example from Eric Ma's [very nice tutorial](https://github.com/ericmjl/bayesian-stats-modelling-tutorial). I have a simple notebook that I'd be happy to share, but I'm not sure the best way to do so given that I can't attach it to this issue. 

I generate two datasets with different shapes (1000 points for dataset1, 750 for dataset2):
![image](https://user-images.githubusercontent.com/6588826/104761921-9634f880-5731-11eb-96b4-1bdfcf01ff8e.png)

The model is defined as
```python
with pm.Model() as model:
    t_data = pm.Data('t',t1)
    act_data = pm.Data('activity',activity1)
    
    A = pm.HalfNormal('A', sd=100)
    tau = pm.Exponential('tau', lam=1)
    C = pm.Normal('C', sd=100)
    
    sd = pm.HalfCauchy('sd', beta=1)
    
    link = A * np.exp(-t_data/ tau) + C
    
    like = pm.Normal('activity_likelihood', mu=link, sd=sd, observed=act_data)
```

The initial sampling of the data works fine
```python
with model:
    trace = pm.sample(2000,tune=2000)
pm.plot_trace(trace)
```

But if I try to reset the data:
```python
with model:
    pm.set_data({'t':t2,'activity':activity2})
    trace = pm.sample(2000,tune=2000)
pm.plot_trace(trace)
```
I get a very long error that ends in: 
```python
~/software/anaconda/miniconda3_200323/envs/analyze/lib/python3.7/site-packages/theano/gradient.py in access_term_cache(node)
   1235                                 "%s.grad returned object of "
   1236                                 "shape %s as gradient term on input %d "
-> 1237                                 "of shape %s" % (node.op, t_shape, i, i_shape))
   1238 
   1239                 if not isinstance(term.type,

ValueError: Elemwise{sub,no_inplace}.grad returned object of shape (1000,) as gradient term on input 0 of shape (750,)
```

Interestingly, I can change the values of the domain variable (time) in order to sample the posterior predictive and not get an error
```python
tnew = np.arange(0,1000,0.5)
with model:
    pm.set_data({'t':tnew})
    ppc = pm.fast_sample_posterior_predictive(idata)
``` 

Also, I think my comment about the "coords" above was wrong. I was misinterpreting the coords "fixing" the problem from the sample_posterior_predictive working.

**Comment by OriolAbril** [comment]
Sampling the same model on new data with different shape currently fails, see issue #3007 (though it took a slight detour for a few comments). Hopefully this can be fixed in the next major release. 

Currently, this needs to be done with _model factories_ in order to recompile the model every time the shape of the data is modified. Luciano talks about them in his [PyMCon talk](https://discourse.pymc.io/t/posterior-predictive-sampling-in-pymc3-by-luciano-paz/6028) for example, and there are many other similar questions on Discourse.

**Comment by martintb** [comment]
Thanks @OriolAbril! I'll use the model factory pattern until I hear that shape changing is supported. It would be nice if the devs could add a sentence or two on the [Data Container](https://docs.pymc.io/notebooks/data_container.html) page in the documentation about this limitation.

**Comment by ConradWhiteley** [comment]
@OriolAbril 
> Sampling the same model on new data with different shape currently fails, see issue #3007 (though it took a slight detour for a few comments). Hopefully this can be fixed in the next major release.
> 
Has there been any updates/ fixes for this issues yet? I can't find anything online.


@martintb 
> Thanks @OriolAbril! I'll use the model factory pattern until I hear that shape changing is supported. It would be nice if the devs could add a sentence or two on the [Data Container](https://docs.pymc.io/notebooks/data_container.html) page in the documentation about this limitation.

Did you ever solve this?

**Comment by OriolAbril** [comment]
All of the above should be fixed in v4 which is currently in beta. All the changes are listed in https://github.com/pymc-devs/pymc/blob/main/RELEASE-NOTES.md. We are also working on a migration guide explaining the dims/shape/size argument and other changes.
