### ISSUE TITLE
PyMC3 Plotting docs link to wrong ArviZ Link

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4319]
## Description of your problem
Links on this page are broken. They should be changed to link to the correct arviz plotting documentation

https://docs.pymc.io/api/plots.html

**Comment by CloudChaoszero** [comment]
Hey there, @canyon289.  I think I found a fix. 🤞 Submitted a PR now

**Comment by CloudChaoszero** [comment]
@canyon289 Hey there! Hope you are doing well. 

From this PR #4333 , 
It appears that the original `.rst` file should work for the re-directed links. Moreover, if i made a change to the `conf.py`, that was not correct.

Maybe the docs should be re-built?

Here is an example of my local changes using `make html` && `make serve`
* See the re-direct link, at the bottom left of the screenshot

<img width="555" alt="Local sphinx changes for arviz hyperlink redirect" src="https://user-images.githubusercontent.com/19514362/102172675-18d64980-3e4e-11eb-8683-d0bad3906a85.png">

**Comment by canyon289** [comment]
@CloudChaoszero Looks like the other contributors have been helping out. I just wanted to stop by and say thanks for taking this on and following through. Its very much appreciated :)

**Comment by MarcoGorelli** [comment]
Closing as these work fine with the latest build of the docs

**Comment by OriolAbril** [comment]
Sorry I'm late to the party and thanks for being on top of that everyone! :smile: 

I refactored the stats and plots links a while back (#3927) to use intersphinx instead of using html links precisely to try to avoid having to edit the source if ArviZ docs were changed. When using intersphinx, as long as the homepage address is not modified, rebuilding the docs should always regenerate the links and fix any that have ended up outdated.
