### ISSUE TITLE
Theano dependency is pinned in 4 places

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4320]
A bit unfortunate that we specify the exact version in 4 places now. Do we even need it for the `-dev` environments? My understanding is that these are just the dependencies in addition to what is in `requirements.txt`.

**Comment by MarcoGorelli** [comment]
In the future, will PyMC release have a minimum theano-pymc/aesara version, or will each PyMC release have one particular theano-pymc release associated with it?

If the latter, then it should probably only be defined in a single place (or there should be checks that the different places it's defined match up). If it's the latter, then in the other three places it's pinned (`conda-envs/environment-dev-py36.yml`, `conda-envs/environment-dev-py37.yml`, `conda-envs/environment-dev-py38.yml`), the pins could be mixed up a bit between them so that different CI jobs run tests with different versions. 

---

I presume the `requirements-dev.txt` is for people (like @rpgoldman ?) who aren't developing in a conda environment?

In pandas there's a script to generate `pip` requirements from conda: https://github.com/pandas-dev/pandas/blob/master/scripts/generate_pip_deps_from_conda.py , if you want we could add that to make sure they stay consistent.

**Comment by twiecki** [comment]
@MarcoGorelli for the time being we will probably be pretty interlocked with specific theano versions.

I like the idea with generating the pip files from the conda env.
