### ISSUE TITLE
Searching documentation not working

### ISSUE THREAD

**Issue by billtubbs** [pymc-devs/pymc#4438]
## Description of problem

The search function on the documentation website doesn't seem to be working at the moment.

Page URL: `https://docs.pymc.io/search.html?q=MCMC`

The page displays  the word "Searching..." for an indefinite period with the trailing dots making an animated incremental pattern (indicating that it is busy).

I get the same problem in Safari and Chrome on Mac OS X Mojave and on Safari on iOS 14.2.

Is something broken on the server side maybe?

## Versions and main components

* Website: `https://docs.pymc.io`
* Operating system: Mac OS X 10.14.6
* Browser versions: Safari (14.0.2) and Chrome (88.0.4324.96)

**Comment by ColCarroll** [comment]
Yikes -- third one is probably what's breaking us most, but none of those look great: 
![image](https://user-images.githubusercontent.com/2295568/105644948-90908e80-5e66-11eb-9201-aec3856bb984.png)

**Comment by ricardoV94** [comment]
@OriolAbril Can we close this one?

**Comment by OriolAbril** [comment]
I think we have 2 options:

* Close this and have the v3 docs with a non-working search bar as a wontfix issue because the v4 work.
* Keep this open with a v3 tag and a low priority tag or something of the sort to indicate that v3 still has the issue but we probably won't work on it.

I personally don't think it's worth fixing in v3.

**Comment by ricardoV94** [comment]
> I personally don't think it's worth fixing in v3.

Agree
