### ISSUE TITLE
Broken PyMC's Jupyter Notebook Style link in docs

### ISSUE THREAD

**Issue by matteo-pallini** [pymc-devs/pymc#4485]
I wanted to start contributing on pymc3. While reading the [contributing doc](https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md) I got the impression that the `PyMC's Jupyter Notebook Style` link is broken. 

It seems to be pointing toward a non-existing page https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style, and prompts you to create a new one. I guess that it should point toward https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide.

It feels like an easter egg for anyone keen to contribute :-)

**Comment by ricardoV94** [comment]
Thanks for reporting. I opened a PR to fix it (I should have asked first if you wanted to do that in case you are a complete beginner, but hopefully I did not steal it from you!). We have some beginner-friendly issues listed here if you want to pick one: https://github.com/pymc-devs/pymc3/issues?q=is%3Aopen+is%3Aissue+label%3A%22beginner+friendly%22

I recommend you ask first whether the issue you want to work on is still relevant, because we are in a transition period for V4.0, and some things will simply not be needed / used afterwards.

**Comment by matteo-pallini** [comment]
Thanks for picking it up so quickly. 

I was considering picking the one below. Mainly because it's among the few ones with no comments, so likely to be unclaimed.
https://github.com/pymc-devs/pymc3/issues/4425

wdyt? happy to pick another one, if you think it may be a better idea. I am likely to have some free time within the next 10 days, so it would be great to do work that would give me a feeling of the codebase structure. Surely you have more context than me on the codebase and what's needed, so happy to follow your advice

**Comment by ricardoV94** [comment]
@drabbit17 That one is definitely useful and still up to grabs. If you leave a comment there I can assign it to you. Feel free to ask any questions about it over there :)
