### ISSUE TITLE
windows 安装失败

### ISSUE THREAD

**Issue by weidongzhou1994** [pymc-devs/pymc#4498]
导入包后出现：
![image](https://user-images.githubusercontent.com/40510496/109782320-b8cc9380-7c43-11eb-841c-5556b2930202.png)

**Comment by twiecki** [comment]
@weidongzhou1994 English only here. From the error it seems like your Theano version is not up-to-date and I recommend uninstalling and reinstalling `Theano-PyMC`.

**Comment by weidongzhou1994** [comment]
sorry, but when I installed Theano-PyMC,  I encounter a new problem:UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte.
![image](https://user-images.githubusercontent.com/40510496/110562517-9cb97c80-8184-11eb-83d7-84c9e3d209cb.png)

**Comment by mengyuqianxun** [comment]
I have the same problem.

**Comment by michaelosthege** [comment]
Same discussion happened in https://github.com/pymc-devs/aesara/issues/337#issuecomment-798926928

I'm closing this issue because it's likely a general problem with the GCC installation not harmonizing with OS settings (see the comment linked above).
But if you find a solution, please do post relevant information.
