### ISSUE TITLE
Runtime warning in pm.summary(trace.sample_stats)

### ISSUE THREAD

**Issue by mjhajharia** [pymc-devs/pymc#4614]
To reproduce:

```
coords = {"step": ["BinaryMetropolis", "Metropolis"]}
dims = {"accept": ["step"]}

with pm.Model(coords=coords) as model:
    mu1 = pm.Bernoulli("mu1", p=0.8, dims="step")
    mu2 = pm.Normal("mu2", mu=0, sigma=1,dims = "step")

with model:
    step1 = pm.BinaryMetropolis([mu1])
    step2 = pm.Metropolis([mu2])
    trace = pm.sample(
        10000,
        init=None,
        step=[step1, step2],
        cores=2,
        tune=1000,
        return_inferencedata=True,
        idata_kwargs={"dims": dims, "coords": coords},
    )

pm.summary(trace.sample_stats)
```

<img width="988" alt="image" src="https://user-images.githubusercontent.com/55153708/113509569-035b6b80-9574-11eb-8f49-fdca552d2df0.png">

```
numpy     : 1.20.1
arviz     : 0.11.2
pymc3     : 3.11.2
```

It might be something like a floating-point calculation error

**Comment by mjhajharia** [comment]
could this possibly be happening, because of some convergence error or something?

**Comment by OriolAbril** [comment]
This looks like a division by 0 error. But I don't think we have to concern ourselves with that. By default `az.summary` (note that `pm.summary` is only an alias for that) computes both summary statiatics and diagnostics. Some of these make no sense when applied to many variables in sample_stats. The divergences for example are stored as a boolean, the mean will act as percentage of diverging samples,  but variance, hdi, mcse or rhat make no sense. The step size is a constant in the vast majority of cases (would only vary if it were jittered which I think only turing supports,  and then the step size nom is added which is a constant) so variance is 0 and ess,  mcse, rhat again make no sense. Moreover,  as rhat has a division by the variance,  it should be expected to encounter runtime warnings and nans as results. I am quite sure that the rhat of the step size is the culprit here

**Comment by mjhajharia** [comment]
@OriolAbril That makes sense. Thankyou for Clarifying! that was very helpful.
