### ISSUE TITLE
Allow naming of dims when parametrizing with size

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4656]
## Description
The current implementation allows users to register/name/introduce dimensions to the model by specifying `dims` on RVs that have implied dimensions:

```python
with pm.Model():
    pm.Normal("n", mu=[1,2,3], dims=("town",))
```

But the `shape`/`dims`/`size` kwargs are currently implemented as exclusive, so the following scenario is currently not supported:
```python
with pm.Model():
    pm.Normal("n", mu=[1,2,3], size=7, dims=("day_of_week", "town"))
```

There's already a test for this scenario: `test_shape_handling.py::TestShapeDimsSize::test_data_defined_size_dimension_can_register_dimname`

Technically there should be nothing preventing us from supporting this use case. We'll just need to require the newly introduced dim name to be previously unknown, so we can rule out potential shape conflicts.

**Comment by ricardoV94** [comment]
@michaelosthege Is this one done?

**Comment by michaelosthege** [comment]
No, the corresponding test is still marked as XFAIL on `main`:

https://github.com/pymc-devs/pymc3/blob/0923d255a45773b7a92bbe36cb11ad5d946a3122/pymc3/tests/test_shape_handling.py#L315-L324

On a high level this is what needs to be changed:
* Permit simultaneously passing `dims and shape` or `dims and size`
* Check that the dimensionality of the created `rv_out` matches all expectations
* Think about ways how this could break & add corresponding warnings/tests:
  E.g. if elements in `shape`/`size` don't match the (symbolic) dimension lengths that are already registered with the model.
  In these cases we probably want to substitute the entries in `size`/`shape` such that `dims` takes priority over `size`/`shape`. (Ignoring the numeric entries that would restrict model flexibility.)

If nobody else picks this up I'll do it, but there are other important things on the ToDo-list too: Getting the `gp` submodule back online, for example.

**Comment by ricardoV94** [comment]
I actually closed it by pure accident! Sorry for that

**Comment by LukeLB** [comment]
Hi guys. I've been looking at trying to put together a PR for this issue. All I've done so far is remove the if statement in the Distrubution parent class that disallows dual passing of size/shape and dims (lines 216-223 in distrubution.py), then written a new test using some of the model spec code from #5181, this test passes. However, as @michaelosthege mentions above there is already a test for this case,
```
    @pytest.mark.xfail(reason="Simultaneous use of size and dims is not implemented")
    def test_data_defined_size_dimension_can_register_dimname(self):
        with pm.Model() as pmodel:
            x = pm.Data("x", [[1, 2, 3, 4]], dims=("first", "second"))
            assert "first" in pmodel.dim_lengths
            assert "second" in pmodel.dim_lengths
            # two dimensions are implied; a "third" dimension is created
            y = pm.Normal("y", mu=x, size=2, dims=("third", "first", "second"))
            assert "third" in pmodel.dim_lengths
            assert y.eval().shape() == (2, 1, 4)
```

 but when I run it it fails, from what I can see it fails for two reasons:

1. No coords are passed into the model constructor function. Which causes an error but this is fixed by passing `pm.Model` some dummy coords. 
2. A shape error is raised.

>  ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2,) and arg 1 with shape (1, 4).

Is this correct? Should we be expecting this error from this model spec in the test given the assert statement expects them to be able to be broadcast together? 

Apologies if I'm missing something obvious, I'm still fairly new to this.

**Comment by michaelosthege** [comment]
Hi @LukeLB I already made the necessary changes this weekend - see #5325.
But please try if the test you wrote works with latest `main`. It doesn't hurt to have another check :)

**Comment by LukeLB** [comment]
@michaelosthege I'll go ahead and do that! Thanks for letting me know :)
