### ISSUE TITLE
Use something like `versioneer`

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/pymc#4727]
Instead of manually updating a version string in code, why don't we use something like [`versioneer`](https://github.com/python-versioneer/python-versioneer) that allows us to utilize `git` tags?

**Comment by twiecki** [comment]
+1

**Comment by maresb** [comment]
I wish I had seen this earlier...

If we were to switch from setuptools to [Hatch](https://github.com/pypa/hatch), this would be [just a few lines of config](https://github.com/ofek/hatch-vcs) in the `pyproject.toml` instead of an awkward vendored script. Hatch also eliminates the need for lots of other boilerplate.

**Comment by twiecki** [comment]
We can always change it.
