### ISSUE TITLE
Reimplement old start value logic

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4752]
After the initial V4 refactoring, the model initial point is now specified by random samples from the prior distribution. In, comparison, in V3 we were using central moments (mean, median, mode) to specify the starting point for most (some?) samplers. @junpenglao and @ColCarroll argue that the changes might be suboptimal.

If anyone with more background knowledge could clarify how the starting values were being used (and from where) that might help figuring out a plan to reimplement them (if that's indeed what we want to do).

**Comment by brandonwillard** [comment]
That should be straightforward enough to do, but I'm admittedly curious about this strict deterministic starting point idea.  

@junpenglao and @ColCarroll, is this a concern for something outside of initializing MCMC chains, because it seems odd that one would want to fix the starting points of a sample chain based on the general form of a model (and its observations), especially when/if RNG seeding is involved, because that would ultimately fix the sample chain across multiple runs.

**Comment by ricardoV94** [comment]
There is also the initial random jittering on top of the fixed initial point, which I guess would break the deterministic sampling over multiple runs. But that's where my knowledge ends

**Comment by brandonwillard** [comment]
Before I forget, we still need to figure out exactly how we want to start multiple chains.  The way the initial point sampling is currently designed, we should be able to produce multiple valid starting points using the same code.

**Comment by brandonwillard** [comment]
> There is also the initial random jittering on top of the fixed initial point, which I guess would break the deterministic sampling over multiple runs. But that's where my knowledge ends

Looks like you anticipated my follow-up!

Yeah, I think this all boils down to the when and where of initialization for multi-chain sampling, which has yet to be fully resolved.
