### ISSUE TITLE
Create installation guide

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc#4792]
Current installation instructions are broken. 
- Update installation instructions
- Add basic troubleshooting
- Include differences between PyMC3 and PyMC3 v4 if necessary

**Comment by ernewton** [comment]
I may be encountering the this issue (specifically the broken installation instructions). In a clean conda 3.7 environment on MacOS Catalina and on Big Sur, conda install per the current documentation results in a stalled environment solve. I am able to install each of the three packages separately (mkl, pymc3, theano-pymc; theano-pymc3 still fails at resolving the environment, but doesn't stall), but as far as I can tell pymc3 still is trying to use theano rather than theano-pymc.

```
conda install -c conda-forge mkl pymc3 theano-pymc
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \

[[which persists indefinitely]]

**Comment by fonnesbeck** [comment]
@ernewton Thanks for the report. Are you using an Intel Mac, or one of the new M1 machines?

**Comment by twiecki** [comment]
Closing due to no response.
