### ISSUE TITLE
Separate notebook build from documentation build 

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc#4794]
Building them together is unnecessary since they don't need to be versioned and some take a very long time to build (up to three days in some cases).

**Comment by Sayam753** [comment]
I am starting to look into this.

For main branch, this is how the docs are built -
<img width="959" alt="Screenshot 2021-08-01 at 2 21 58 AM" src="https://user-images.githubusercontent.com/43073325/127752177-cf0f0c0d-244e-45dd-bf65-86ec4cb9a61e.png">

A quick question -
For notebook build, are we considering to execute this build from PyMC?
This would mean that the Tutorials and Examples section in the PyMC website will be filled in by PyMC-examples.

or will PyMC-examples have a dedicated website+url on this own? And PyMC website will just link to it.

cc @OriolAbril

**Comment by OriolAbril** [comment]
> For main branch, this is how the docs are built -

This is how they look right now after changing the theme but nothing else, but after GSoD the documentation should look like the moqup: https://app.moqups.com/eS8Ttyrfsp/view/page/aa9df7b72, which has different sections. IIUC, notebooks will be discoverable via the learning section.

Moreover, even if we kept the same website structure, the pydata theme allows to use external links in the navbar, so we could build docs and example independently, docs builds the books+videos, api, dev guide and about pages, examples builds the tutorials and examples but both have the same navbar so the only way to know on which webite you are is checking the url. Most readers would not notice they are changing websites when navigating between the two via the navbar.

> or will PyMC-examples have a dedicated website+url on this own? And PyMC website will just link to it.

This is what I'm proposing. That each has its own url and is build independenly of the other (using intersphinx for linking the two seamlessly though, so for example the glossary is shared between the two websites). My opinion on that is not too strong but I do lean towards this option because while the documentation should be versioned and doing so will have many advantages, the examples don't really follow the release cycle. The current example gallery has most notebooks executed with pymc3 3.11 and 3.10 and a few still left to update since 3.8 or 3.9, and I don't think it's feasible to revise and rerun _all_ the notebooks with every release. Moreover, we now have ~6 new notebooks, running on 3.11 that are not shown in the website, and won't be until the next release (which might already be 4.00 even!). As an extra welcome side effect, the generation of pymc3 docs will be blazing fast if doing this, with the generation of examples website taking more time like current docs do.

What I'm not sure about is how do we want the exampes website to look like. Do we want it to be divided in topics like it is now? in branches of the tree? something else altogether? Once we have this clear, we can move the gallery_generator sphinxext here and use it as is, modify it, remove it altogether and use pure sphinx with ablog only...
