### ISSUE TITLE
Scalar ODEs on Windows failing because of a casting & broadcastability issue that was fixed only for Linux

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4904]
## Description of your problem
Three ODE tests - all testing with a scalar ODE - still run into broadcastability problems.
The related Aesara ticket https://github.com/aesara-devs/aesara/issues/390 was closed with a fix that did fix the aforementioned tests for non-Windows OSes.

But the tests kept failing for Windows, so apparently the issue still persists under some rare circumstances.

Also see https://github.com/pymc-devs/pymc3/pull/4902 which edited the `@pytest.mark.xfail` conditions accordingly.

## Versions and main components

* PyMC3 Version: `main`
* Aesara Version: `2.1.3`
* Operating system: Windows

**Comment by ricardoV94** [comment]
Figured out the source of difference in behavior. Aesara constant integer lists have dtype int32 in Windows but dtype int64 in Linux. 

```python
import aesara.tensor as at

# Changes from int64 in Linux to int32 in Windows
print(at.constant([1]).dtype)
```

This leads to an extra casting in the size input when creating RVs in Windows compared to Linux.
```python
# Will be a constant in Linux but a SpecifyShape of a cast in Windows
print(at.random.normal(size=[1]).owner.inputs[1])
```

Which might lead to further issues down the road due to things like https://github.com/aesara-devs/aesara/issues/692
