### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by lncohn** [pymc-devs/pymc#4988]
Would it be possible to always keep installation with Anaconda on Mac updated and verified. It's currently not possible to install correctly on Mac. Easy and consistent installation would be a big value unlock for this product.

**Comment by michaelosthege** [comment]
I'm not a Mac user myself, but there's an [installation guide for it](https://github.com/pymc-devs/pymc3/wiki/Installation-Guide-(MacOS)).
Contributions to make installation procedures more robust is very welcome. Points of entry are also the [pymc3-feedstock](https://github.com/conda-forge/pymc3-feedstock) and [aesara-feedstock](https://github.com/conda-forge/aesara-feedstock).

We have CI jobs that test PyMC3 on all of Linux, Mac and Windows platforms, but these tests can't reproduce all the different flavors of how users might have set up their environments.
Anaconda is generally problematic (on all platforms) because it easily leads to conflicts between compilation dependencies between conda envs and the base environment.

We are aware that the installation has a lot of friction and there are activities ongoing trying to improve it.
Therefore I'm going to close this issue, but if you can pinpoint a specific problem, or propose a specific solution feel free to reopen.

**Comment by ericmjl** [comment]
@lncohn agreeing with @michaelosthege here. Also, I would recommend puling PyMC3 from the `conda-forge` channel rather than the `anaconda` channel, as that is where we keep it up-to-date with the latest PyPI releases. (There are bots that are helping us here.)

@lncohn I noticed in your original post there wasn't a specific error message that you were referring to. Without specifics, it's going to be incredibly difficult to debug, as you'd probably be familiar with :smile:.

**Comment by lncohn** [comment]
Here's my suggestion. If you or a teammate were to create a new conda environment with python 3.7 or python 3.8 and run 
conda install -c conda-forge mkl pymc3 theano-pymc -- it wouldn't install properly. If there is a better way to think about installing pymc3 on a mac, please let me know. I promise that many data scientists would like to know.

**Comment by MarcoGorelli** [comment]
I've ran into problems myself when creating an environment and then running `conda install`, can you try instead to make an `environment.yml` file in which you specify your dependencies, and then creating an environment with `conda env create -f environment.yml`

Hard to know if this solves your issue though as

> it wouldn't install properly

isn't exactly a complete bug report

**Comment by MarcoGorelli** [comment]
> Here's my suggestion. If you or a teammate were to create a new conda environment with python 3.7 or python 3.8 and run
> conda install -c conda-forge mkl pymc3 theano-pymc -- it wouldn't install properly

I just did that, on mac, and it worked fine:

```
$ conda create -n can-i-install-pymc3 python=3.8 -y
$ conda activate can-i-install-pymc3
$ conda install -c conda-forge mkl pymc3 theano-pymc
$ python
>>> import pymc3 as pm
>>> pm.__version__
'3.11.4'
```

**Comment by lncohn** [comment]
This is exactly what I've been doing for the past few days. But this worked this morning :).
Thanks for your help. --Lee

**Comment by lncohn** [comment]
I found that the anaconda installation above only works with Xcode is installed on a mac. If this is the case, it would be helpful if your instructions for mac mentions this explicitly.

**Comment by MarcoGorelli** [comment]
Feel free to mention that, I think anyone can edit the wiki
