### ISSUE TITLE
Coordinates and values of `constant_data` messed up

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5046]
## Description of your problem
I have a model that has two data variables of identical dimensionality:
```python
pymc3.Data("obs_A360", obs_A360, dims=("replicate_id", "cycle"))
pymc3.Data("obs_A600", obs_A600, dims=("replicate_id", "cycle"))
```
where `obs_A360` and `obs_A600` are numpy arrays of shape (131, 5).

Sampling works fine, also an `InferenceData` object is returned.

But looking into `idata.constant_data` the shapes, values and coordinates of those data variables are completely messed up:

- The `replicate_id` coordinate became a concatenation of the string-valued replicate IDs with a numpy arange of the same length.
- `idata.posterior.replicate_id` and `idata.constant_data.replicate_id` don't match
- `constant_data.obs_A360` and `constant_data.obs_A600` have shapes (262, 5) and are half filled with `nan`. And not even the same way!

![grafik](https://user-images.githubusercontent.com/5894642/136253278-275af748-7801-41c0-b15d-77bc13750c29.png)

What's going on?!

## Versions and main components

* PyMC3 Version: `main`

**Comment by OriolAbril** [comment]
This might be an issue with the faulty workaround from https://github.com/pymc-devs/pymc/issues/5042. Because it is triggered only when `default_dims` is not None -> not triggered for posterior which does work, but triggered by constant data and all hell gets loose.

I'd recommend fixing #5042 and then check to see if the issue persists.
