### ISSUE TITLE
Improve default seeds used for each chain

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5164]
@ColCarroll mentioned that we might want to be more careful with how we seed different chains/processes. Right now this is our default:

https://github.com/pymc-devs/pymc/blob/52a126dd31c68d8417495cd240af700800d2878b/pymc/sampling.py#L453

Whereas this seems to be the NumPy recommended strategy: https://numpy.org/doc/stable/reference/random/parallel.html#seedsequence-spawn

I am not sure if this also applies to other places where we create seeds such as in https://github.com/pymc-devs/pymc/blob/bdd4d1992f11cab9202774b14b8044ddf0cb7674/pymc/model.py#L965

**Comment by larryshamalama** [comment]
Upon closer inspection, it seems like NumPy is recommending us to move to `Generator`s instead of `RandomState`s: https://numpy.org/doc/stable/reference/random/legacy.html?highlight=randomstate#numpy.random.RandomState Should we go from `RandomState` to `Generator`, or would this be too much work?

I'm also mentioning this because each `SeedSequence` can spawn `Generator` objects and I'm not sure if this would break our code if we were to use their recommended strategy for seeding parallel processes.

**Comment by ricardoV94** [comment]
This has mostly been done. Further improvements depend on #5797
