### ISSUE TITLE
Filter variables in `model_graphviz`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5198]
@lucianopaz suggested that we could could filter variables similar to the `var_names` keyword in arviz, so that we plot subsets of the model graph. This should be straightforward with some simple Aesara graph manipulation prior to calling the main function in `model_graphviz`

**Comment by michaelosthege** [comment]
Related: An option to drop disconnected `pm.Data` nodes from the visualization.

**Comment by ricardoV94** [comment]
> Related: An option to drop disconnected `pm.Data` nodes from the visualization.

I think that could work out of the box with the filtering based on varnames

**Comment by danhphan** [comment]
Hi @ricardoV94 and @michaelosthege, I am happy to take this task.

**Comment by ricardoV94** [comment]
Thanks @danhphan!

Just a heads up, this one will require a bit of exploration. We know what we want the behavior to be like, but we don't know exactly how to achieve it just yet.

Let us know if you manage to get something working, and if not, what did you try so we can help.

**Comment by danhphan** [comment]
Hi, yes sure, I will do some exploration first. This is a good opportunity to learn `model_graphviz` and `arviz` as well :smile:

**Comment by danhphan** [comment]
Hi, as this issue is going to be solved in #5527, I will focus on other tasks then :). Thanks

**Comment by michaelosthege** [comment]
Thanks @danhphan for pointing out the duplicate.
I'm going to close this issue in favor of #5527 (because that one is more concrete in its description).

Regarding the who's working on it (cc @danhphan @soma2000-lang), I wrote it in other issues as well: We don't usually take reservations for issues.
IMO Anybody who wants to resolve an issue should just check if there's already a PR about it and if not open a (draft) pull request to get it done. Any (small) issue that doesn't have a corresponding PR yet can be considered _up for grabs_. Also those where someone might have been assigned a long time ago.
