### ISSUE TITLE
Add AePPL logp/logcdf references for all Distributions that are missing them

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5329]
## Description of your problem
Many of the distributions in PyMC call another library, AePPL, for their logp and logcdf calculation.

Please add references to the AePPL log P library. See PR below for an example of the code changes needed, and where to find the AePPL library

https://github.com/pymc-devs/pymc/pull/5327

**Comment by OriolAbril** [comment]
These should probably use sphinx cross-references. I don't completely understand aeppl, it's scope and audience nor the relation pymc-aeppl, and I'm willing to be convinced otherwise in this scenario. 

IMO, there are two reasons for the comment above:

1. in general the average user shouldn't need to read the code _at all_. It is great to have the source code easily available from the api page (with the source button) and I use it quite often, but that should be a thing aimed mostly at power users and contributors, otherwise it is a failure of the documentation
2. urls to documentation pages of other python libraries are brittle and in addition are generally less specific than sphinx cross references. In the template PR, we could have use `` {func}`aeppl.logprob.exponential_logprob` `` to point direclty to the right api page (which could then have a [source] button and so on), now it links only to the logprob file.

_Note:_ Point 2 especially (but related to both) requires that aeppl has html documentation served somewhere. https://aesara-devs.github.io/aeppl/index.html exists but it seems to have last been updated on August. I can _help_ (not do it myself) setting up documentation for aeppl, configuring readthedocs if that is something of interest to aesara-devs (cc @ricardoV94) and in fact I already reviewed https://github.com/aesara-devs/aeppl/pull/52. If we can rely on aeppl having up to date documentation published then a link to relevant file in github is ok.

**Comment by purna135** [comment]
Is it okay if I work on this?

**Comment by OriolAbril** [comment]
I think it's best to wait a bit on this until we figure out aeppl docs and how to better integrate the two documentations. I'm removing the labels for now.
