### ISSUE TITLE
Discussion: Dims usage on univariate regression is a bit confusing

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5561]
## Description of your problem
Using coords or dims in univariate situations necessitates the usage of indexing. This can be confusing as if I have a model that is specified without indexing, and then add dims/coords, an shape mismatch is caused. If the behavior can't be changed can a more useful exception be raised?

**Please provide a minimal, self-contained, and reproducible example.**
```
# Generate data and specify coords
df = pd.DataFrame(np.random.normal(size=(10,2)), columns=["x_1", "y"])

COORDS = {
    "slopes": ["x_1"]
}
```

## Doesnt work
```

with pm.Model(coords=COORDS) as adelie_regression:

    β = pm.Normal("β", sigma=1000, dims=("slopes"))
    
    mu =  β * df["x_1"].values
    pm.Normal(
        "obs",
        mu=mu,
        sigma=1,
        observed=df["y"].values
    )
    idata_regression = pm.sample()
```

## Works
```
with pm.Model(coords=COORDS) as adelie_regression:

    β = pm.Normal("β", sigma=1000, dims=("slopes"))
    
    mu =  β[0] * df["x_1"].values
    pm.Normal(
        "obs",
        mu=mu,
        sigma=1,
        observed=df["y"].values
    )
    idata_regression = pm.sample()
```

## Also works
```
with pm.Model() as adelie_regression:

    β = pm.Normal("β", sigma=1000)
    
    mu =  β* df["x_1"].values
    pm.Normal(
        "obs",
        mu=mu,
        sigma=1,
        observed=df["y"].values
    )
    idata_regression = pm.sample()
```

## Exception for first case
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/7213793/156950679-82e3fb0b-8863-4aee-8139-0abdc5446d5b.png">
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/7213793/156950691-16850e94-834e-4c1a-aa8e-38735f0e2a42.png">

## Versions and main components

* PyMC/PyMC3 Version: Main at https://github.com/pymc-devs/pymc/commit/620546b77f035623b50a5602b530f7ad2413a682
* Aesara/Theano Version:

**Comment by OriolAbril** [comment]
I am not sure there is any sensible way to get around this. `dims` gets converted to `size` so what you are asking boils down to having the two options below be equivalent:

```
β = pm.Normal("β", sigma=1000)
β = pm.Normal("β", sigma=1000, size=(1,))
```

Which I think will probably mean many more shape issues down the road.

**Comment by ricardoV94** [comment]
> I am not sure there is any sensible way to get around this. `dims` gets converted to `size` so what you are asking boils down to having the two options below be equivalent:
> 
> ```
> β = pm.Normal("β", sigma=1000)
> β = pm.Normal("β", sigma=1000, size=(1,))
> ```
> 
> Which I think will probably mean many more shape issues down the road.
> 

Or alternatively allow dims for scalar distributions (`size=()`)

**Comment by OriolAbril** [comment]
> Or alternatively allow dims for scalar distributions (size=())

Not sure I understand this, could you explain how that would be defined and how the output would look like?

**Comment by ricardoV94** [comment]
> > Or alternatively allow dims for scalar distributions (size=())
> 
> Not sure I understand this, could you explain how that would be defined and how the output would look like?

I don't have a good suggestion, just wanted to mention the flip side of what you said. We have a way to specify dims for `size >= 1`, but not for `size=()` which is what the original problem hinged on. 

Not saying it is incoherent, since they have zero dimensions according to the numpy API, therefore dims should be `None`. We also can't say `size=(0,)`

I hope this clarifies the original question.

**Comment by OriolAbril** [comment]
@canyon289 could you explain why do you want dimension names on scalar quantities at a conceptual level? How do they differ from the variable names?

I also ignored the changing the error message previously. I think the most important thing would be to be able to distinguish such cases from "regular" shape mismatches, however, I am not yet sure I understand what "such cases" means, much less if or how they could be distinguished

**Comment by canyon289** [comment]
To be clear I'm not suggesting that dimension names with scalar quantities has to work, or that I want them implemented. All I'm saying is that the exception raised is confusing because it "feels" like it should work, especially in a workflow where multiple dimensions are being added iteratively.
,
Perhaps we can just raise an exception earlier if we detect it saying that we don't support that behavior so users don't get a dimension mismatch later are confused what's happening. Just a suggestion!

**Comment by ricardoV94** [comment]
@canyon289 how would you distinguish dim for scalar size and size=1? Also I don't know whether InferenceData allows this either?

**Comment by ricardoV94** [comment]
Conceptually you are asking to give a name to a dim that does not exist.

```python
assert pm.Normal.dist().ndim == 0
```

**Comment by twiecki** [comment]
The current behavior is what I would have expected and is internally consistent. If I specify a `dims` I get a vector. I'd be more confused if I wrote code that worked on vectors and then change the dims to 1 and it stops working.

The shape errors are indeed not the best, which is a more general problem. Would be good if they mentioned the name of RV at least.

**Comment by OriolAbril** [comment]
> To be clear I'm suggesting that dimension names with scalar quantities has to work, or that I want them implementing.

I read this as

> To be clear I'm *not* suggesting that dimension names with scalar quantities has to work, or that I want them implementing.

Otherwise the rest of the paragraph doesn't make mich sense.

> Perhaps we can just raise an exception earlier if we detect it saying that we don't support that behavior so users don't get a dimension mismatch later are confused what's happening.

Here I don't understand what you refer to with "that behaviour".

> The shape errors are indeed not the best, which is a more general problem. Would be good if they mentioned the name of RV at least. 

That would be nice 

---

Also, looking back at the first code snippet, the column in the dataframe is selected with a string,  not with a list, so it is a 1d vector of length 10, not a 1x10 2d array. Shouldn't two 1d vectors of lengths 1 and 10 broadcast?

**Comment by canyon289** [comment]
@OriolAbril my apologies i fixed the original post.
For the behavior its raising a more useful message to the user if dimension names on scalar quantities is not supported.

> @canyon289 how would you distinguish dim for scalar size and size=1? Also I don't know whether InferenceData allows this either?

I have no idea, in this situation I'm a user that's confused, not a developer that has answers :D. I don't mean that to be flippant, just want to be clear where my perspective is coming from.

I'm getting the understanding that at an "automagic fix" wouldnt be the best route! That's alright!
Would it be possible to "detect" the use of dimension names on scalar quantities on scalar quantities to tell users this may cause issues shape issues later, either through an exception or logging?

**Comment by OriolAbril** [comment]
> Would it be possible to "detect" the use of dimension names on scalar quantities on scalar quantities to tell users this may cause issues shape issues later, either through an exception or logging?

This issue is proof that this can't be done. You expected the code from the first snippet to be a scalar but I have used that same code several times _because I want a 1d array of length 1_. I think the best way is probably adding examples of that on the dims/size notebook so that it is clear to users that these two are equivalent:

```
with pm.Model(coords={"slopes": ["x_1"]}):
    pm.Normal("b", 0, 1, size=(1,))
    pm.Normal("a", 0, 1, dims="slopes")
```

and to get a scalar neither size nor dims should be used.

**Comment by ricardoV94** [comment]
Would this be wrong?

```python
with pm.Model(coords={"slopes": ()}):
    a = pm.Normal("a", 0, 1, size=())
    # This is treated as size=(0,), and not size=(), or size=None right now
    b = pm.Normal("b", 0, 1, dims="slopes") 

a.eval(), b.eval()
# array(1.2774636), array([], dtype=float64)
```

**Comment by OriolAbril** [comment]
Are `size=5` and `size=(5,)` equivalent?

**Comment by canyon289** [comment]
> > Would it be possible to "detect" the use of dimension names on scalar quantities on scalar quantities to tell users this may cause issues shape issues later, either through an exception or logging?
> 
> This issue is proof that this can't be done. You expected the code from the first snippet to be a scalar but I have used that same code several times _because I want a 1d array of length 1_. I think the best way is probably adding examples of that on the dims/size notebook so that it is clear to users that these two are equivalent:
> 
> ```
> with pm.Model(coords={"slopes": ["x_1"]}):
>     pm.Normal("b", 0, 1, size=(1,))
>     pm.Normal("a", 0, 1, dims="slopes")
> ```
> 
> and to get a scalar neither size nor dims should be used.

If docs are the best fix thats a great outcome of this discussion!

**Comment by ricardoV94** [comment]
> Are `size=5` and `size=(5,)` equivalent?

Yes

**Comment by OriolAbril** [comment]
> If docs are the best fix thats a great outcome!

Maybe the error message in general should also be improved to show the name the user gave the variables as @twiecki said, otherwise it can be hard to track where the error comes from.

And this particular situation of not broadcasting two 1d arrays of lenghts 1 and 10 feels strange, how does broadcasting differ between Aesara and numpy?

> > Are size=5 and size=(5,) equivalent?
>
> Yes

Then I think we should keep `dims="slopes"` and `dims=("slopes",)` equivalent too. If the 0 thing is a desired and useful feature, it should probably be triggered with `coords={"slopes": []}` instead, which I think would match `size=0` and `size=(0,)`, are these two valid and equivalent too?

**Comment by ricardoV94** [comment]
> Then I think we should keep `dims="slopes"` and `dims=("slopes",)` equivalent too. If the 0 thing is a desired and useful feature, it should probably be triggered with `coords={"slopes": []}` instead, which I think would match `size=0` and `size=(0,)`, are these two valid and equivalent too?

I don't think the zero thing is desired. I would expect it to behave as `size=()`, `size=[]`, or `size=None` (all the same). The problem is that we probably just do a `len(dims)` internally, which gets converted to `size=0`. I don't think that's helpful or expected.

**Comment by ricardoV94** [comment]
> Maybe the error message in general should also be improved to show the name the user gave the variables as @twiecki said, otherwise it can be hard to track where the error comes from.

That is an Aesara question. I don't think there's an easy way though, because as you see the compiled graph is one of these CompositeOps that do not include the original variables or names anymore in them.

**Comment by ricardoV94** [comment]
> And this particular situation of not broadcasting two 1d arrays of lenghts 1 and 10 feels strange, how does broadcasting differ between Aesara and numpy?

Somehow the dims is turning the output variable into something that is not (known) to be broadcastable:

```python
import pymc as pm

with pm.Model(coords={"slopes":["x_1"]}) as m:

    b_dim = pm.Normal("b_dim", sigma=1000, dims=("slopes"))
    b_size = pm.Normal("b_size", sigma=1000, size=1)

print(b_dim.broadcastable, b_size.broadcastable)
(False,) (True,)
```

**Comment by OriolAbril** [comment]
> Somehow the dims is turning the output variable into something that is not (known) to be broadcastable

This looks like a bug :thinking:, should we open a new issue for this?

**Comment by canyon289** [comment]
> > And this particular situation of not broadcasting two 1d arrays of lenghts 1 and 10 feels strange, how does broadcasting differ between Aesara and numpy?
> 
> Somehow the dims is turning the output variable into something that is not (known) to be broadcastable:
> 
> ```python
> import pymc as pm
> 
> with pm.Model(coords={"slopes":["x_1"]}) as m:
> 
>     b_dim = pm.Normal("b_dim", sigma=1000, dims=("slopes"))
>     b_size = pm.Normal("b_size", sigma=1000, size=1)
> 
> print(b_dim.broadcastable, b_size.broadcastable)
> (False,) (True,)
> ```

This is confusing to me

**Comment by ricardoV94** [comment]
> > Somehow the dims is turning the output variable into something that is not (known) to be broadcastable
> 
> This looks like a bug thinking, should we open a new issue for this?

~I think it might be fixed by https://github.com/aesara-devs/aesara/pull/825, but worth opening an issue with a pure Aesara MWE~

Edit: I don't quite get where the problem is coming from. Would need to debug a bit further

**Comment by ricardoV94** [comment]
> This is confusing to me

Me too, they should be the same. 
Perhaps @michaelosthege as an idea?

**Comment by OriolAbril** [comment]
Could it be because dims are converted to symbolic sizes?

**Comment by michaelosthege** [comment]
Phew, lots to read through.
Let's assert a few things first:
* `size=3` is _lazy notation_ for `size=(3,)`
* `shape=3` is _lazy notation_ for `shape=(3,)`
* `dims="three"` is _lazy notation_ for `dims=("three",)`
* [Here are the tests for this ☝](https://github.com/pymc-devs/pymc/blob/2db28f0b2c0497124f118d7a27728a729c6ca8e0/pymc/tests/test_shape_handling.py#L442-L468)

Quoting [this](https://github.com/pymc-devs/pymc/issues/5561#issuecomment-1068802659) 👇
> I am not sure there is any sensible way to get around this. dims gets converted to size so what you are asking boils down to having the two options below be equivalent:
> 
> `β = pm.Normal("β", sigma=1000)`
> `β = pm.Normal("β", sigma=1000, size=(1,))`
> 
> Which I think will probably mean many more shape issues down the road.

Prior to [`3.11.0`](https://github.com/pymc-devs/pymc/releases/tag/v3.11.0) we had that behavior and it was causing a lot of problems. Length-1 vectors is a perfectly reasonable thing and it's not the same as a scalar.

The different broadcastability from [this](https://github.com/pymc-devs/pymc/issues/5561#issuecomment-1071049968) example is probably because with `dims` the RV is created and then reshaped, whereas size/shape do it in one step?
See https://github.com/pymc-devs/pymc/blob/2db28f0b2c0497124f118d7a27728a729c6ca8e0/pymc/distributions/distribution.py#L166-L176

**Comment by ricardoV94** [comment]
I opened a separate issue for the broadcasting with dims in #5613. I think that is the largest source of the confusion here, as the initial example would have worked fine if that was not going on.

The other question is what should happen for zero-length dims. I am not sure what is better, since empty size is not always no-size, but whatever is implied by the parameter dimensions. Perhaps the best is to just raise whenever dims have a size of zero?

**Comment by michaelosthege** [comment]
> The other question is what should happen for zero-length dims. I am not sure what is better, since empty size is not always no-size, but whatever is implied by the parameter dimensions. Perhaps the best is to just raise whenever dims have a size of zero?

Yes, even with dynamic shape or dynamic dimensionality a length-0 dimension is essentially a "does not exist".
Raise sounds like the best option until someone can demonstrate a valid use case.

**Comment by ricardoV94** [comment]
Closing this issue for now. Feel gree to reopen if you think something is still unclear.
