### ISSUE TITLE
Remove SGMCMC step method

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5580]
As discussed in #5508

**Comment by arihantbansal** [comment]
I want to take this up!

**Comment by ricardoV94** [comment]
> I want to take this up!

Sure, go ahead

**Comment by michaelosthege** [comment]
@arihantbansal I don't see a PR on the issue. [As per our contributing guide](https://github.com/pymc-devs/pymc/blob/main/CONTRIBUTING.md#etiquette-for-code-contributions) please don't claim an issue without following up a PR.

The SGMCMC file is causing problems with our mypy pre-commit step and the best solution to that problem is doing the removal (this issue).
Unless you can do it today I will take over, because the pre-commit problem is urgent.
