### ISSUE TITLE
logp of Binomial distribution raises error when n is zero

### ISSUE THREAD

**Issue by theorashid** [pymc-devs/pymc#5593]
## Description of your problem

Following the [discourse post](https://discourse.pymc.io/t/how-does-pymc3-handle-n-0-in-binomial-discrete-likelihood-function/7900/5), the Binomial distribution works when `n=0` but the `logp` has the constraint that `n>0`.

```python
import pymc as pm
pm.logp(pm.Binomial.dist(n=0, p=0.5), 0).eval()
```
raises
```
aeppl.logprob.ParameterValueError: n > 0, 0 <= p <= 1
```

</details>

**Please provide any additional information below.**
`n=0` cases are important, for example in mortality modelling, when the populaiton for a subgroup is 0 but we still want to estimate the probability of death. So we should allow `n=0` to work.

Note n=0 are common in other count distributions, so BetaBinomial, Poisson (observed counts=0), Negative Binomial, etc will need to be allow this too

## Versions and main components

* PyMC Version: 4.0.0b2

**Comment by ricardoV94** [comment]
From a quick look, the limitation doesn't seem necessary. We could just modify these lines to include `0 <= n` instead of `0 < n`:

https://github.com/pymc-devs/pymc/blob/a6e6748e176a4bc14fff68ad69b7c7b418c94daf/pymc/distributions/discrete.py#L149

https://github.com/pymc-devs/pymc/blob/a6e6748e176a4bc14fff68ad69b7c7b418c94daf/pymc/distributions/discrete.py#L180

**Comment by ricardoV94** [comment]
@theorashid would you like to open a PR for this?
