### ISSUE TITLE
Link in "About" section of this repo points to version3 

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#5758]
## Description of your problem

For this repo here:  
https://github.com/pymc-devs/pymc

Link points to:
[docs.pymc.io/](https://docs.pymc.io/)

It should point to:
https://docs.pymc.io/en/latest/

<img width="309" alt="Screen Shot 2022-05-12 at 7 27 31 AM" src="https://user-images.githubusercontent.com/2507232/168064536-f91334b3-cb6a-46ed-8c23-2ecaa8b4557b.png">

cc:  @OriolAbril

**Comment by OriolAbril** [comment]
The `docs.pymc.io` link is the right one. We then choose the "default" version to be shown from the readthedocs configuration. The default is currently this `v3` branch due to an issue with the old sphinx theme and the renaming of images, but it will and should be the `stable` alias in general.

Once v4 is officially released I will update this and `stable` will alias to v4 (it always points to the latest release excluding pre-releases). Users install pymc from pip or conda, so the documentation at `latest` won't show what they expect (aka the version they have if freshly installed): there may be functions that appear there but haven't been released yet because they are new additions, or changes in defaults... 

A bit more context on `stable` vs `latest` also on https://github.com/pymc-devs/pymc/issues/5728#issuecomment-1120323462
