### ISSUE TITLE
Add jupyter-sphinx to requirements-dev.txt and conda envs

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5845]
## Description of your problem
Installed new environment and it seems dependencies are missing for doc build. One identified below, not sure if there are others

![image](https://user-images.githubusercontent.com/7213793/171868286-2ac8f3a8-1544-469a-93b8-bf6ece404129.png)

**Please provide the full traceback.**

```
Extension error:
Could not import extension jupyter_sphinx (exception: No module named 'jupyter_sphinx')
make: *** [Makefile:62: html] Error 2
```

</details>

## Versions and main components

* PyMC/PyMC3 Version:
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by OriolAbril** [comment]
jupyter sphinx used to be a dependency of myst-nb, since the last myst-nb release it is not anymore. We need to add it because we use both explicitly. 

We need to rethink how we manage/bundle dependencies, which we are tracking in #5074. I'd restrict this issue to adding jupyter-sphinx to the conda envs and requirements-dev.

Note: if we don't fix this the readthedocs build will break at some point. It is still working only because it uses an old myst-nb version that depends on jupyter-sphinx. I also know there are no other dependencies to be added because readthedocs uses the 3.8 conda env to build the docs and it manages to do so at every commit and PR preview
