### ISSUE TITLE
Float variables required by grad

### ISSUE THREAD

**Issue by erlebach** [pymc-devs/pymc#5879]
I have the following error:
``` python
TypeError: grad requires real- or complex-valued inputs (input dtype that is a sub-dtype of np.inexact), but got int64. If you want to use Boolean- or integer-valued inputs, use vjp or set allow_int to True.
```
when running
```
with model:
    idata = jx.sample_numpyro_nuts(target_accept=0.9)
```
I have not figured this out yet, and I am trying to come up with a MWE. In the meantime, I wonder why the compiler does not automatically convert integers to floats. Shouldn't that be possible?  Thanks.

**Comment by ricardoV94** [comment]
NUTS cannot sample discrete variables because it needs to take gradients. Casting them to floats wouldn't solve anything as the distribution is still discrete.

When sampling your model in PyMC you would see that a metropolis stepper would be automatically assigned for those discrete variables and the rest would be sampled with NUTS. The numpyro sampler however does not allow for this kind of mixed samplers and as such it won't work when you call it.
