### ISSUE TITLE
Why is the '*' argument necessary in sample function? (help needed)

### ISSUE THREAD

**Issue by 5hv5hvnk** [pymc-devs/pymc#5921]
The * indicates the end of the positional arguments but is it necessary here? 
What can be the implications of removing it from here?

https://github.com/pymc-devs/pymc/blob/f9b749b76fc24c67366feee0cbbe94ae47b7e1d8/pymc/sampling.py#L308

**Comment by ricardoV94** [comment]
We are forcing people to use keyword arguments. This is quite common for complex functions with many arguments and allows us to change arguments (or their order) in the future without silently breaking people code.

Uses of this function would be pretty unreadable otherwise as well. So it enforces a best practice.

**Comment by 5hv5hvnk** [comment]
Oh okay I was currently trying to add a function that calls pm.sample but due to this there was some issues with calling it. Is there a specific way to refer to these arguments while calling them?

**Comment by ricardoV94** [comment]
You can still call positional arguments by name. What exactly was the problem you faced?

**Comment by 5hv5hvnk** [comment]
I got a `TypeError: sample() takes from 0 to 17 positional arguments but 20 were given` when I pass all arguments while calling the function.
however if I remove the star from the pm.sample() definition it allows up to 20 positional arguments and works fine

**Comment by ricardoV94** [comment]
Do you mind opening a topic on Discourse with your problem and with a bit more code context? You can tag me there when you do it. Asking because we try to keep GitHub for bugs and development issues alone. I was hoping I could solve your problem in one reply but it might need more forth and back.

In general to wrap a function you would do something like:

```python

def my_sample(*args, **kwargs):
    ...
    return sample(*args, **kwargs)
```
And then iterate from there with new arguments or new defaults or something else.
