### ISSUE TITLE
Mark Recapture Model not sampling correctly in PyMC3

### ISSUE THREAD

**Issue by bjedwards** [pymc-devs/pymc#596]
I was trying to convert the [Mark Recapture](https://github.com/pymc-devs/pymc/wiki/Mt) model from pymc2 to pymc3, and don't think pymc3 is sampling the observation probabilities correctly (or I didn't convert the model correctly).

The [pymc2 version](http://nbviewer.ipython.org/gist/bjedwards/7c6b6961b9b33d3bc86d) seems to work correctly, and matches OpenBUGS well enough.

I think there is a mistake in the original Link and Barker model (the observations are out of order, see `f`). 

When I converted [it to pymc3](http://nbviewer.ipython.org/gist/bjedwards/09609c23ec4d0c70f3b0), it doesn't seem like the samples converge and `p[1]` is never altered when sampling.

Moreover, I seem to only be able to use the `Metropolis` sampler on `p`. I get weird errors:

``` python
AttributeError: 'ProdWithoutZeros' object has no attribute 'grad'
```

Is this a bug or did I specify the model incorrectly?

**Comment by jsalvatier** [comment]
Sorry for the year long delay. I was able to get this to work by adding `pi = mc.prod(c, 1, no_zeros_in_input=True)`. The problem is that theano doesn't know how to handle  gradients if some of the values can be zero. Also the new automatic transform logic probably makes this work more easily. 

We should ask theano to give more informative errors here.
