### ISSUE TITLE
approx_hessian throws PositiveDefiniteError when called with test_point

### ISSUE THREAD

**Issue by tshauck** [pymc-devs/pymc#607]
Hi,

I'm attempting to implemented a similar step as: Issue #544, however when I attempt to use the test point to approximate the hessian, I'm met with 

```
PositiveDefiniteError: Scaling is not positive definite. Simple check failed. Diagonal contains negatives. Check indexes [ 0 10]
```

I'm not sure what additional information would be helpful, but I'm happy to provide what I can.

**Comment by tshauck** [comment]
Not sure if it's related to Issue #410.  I tried using the MAP estimated, but it gives unreasonable results (I think) do to the fact I'm fitting a multilevel model.

**Comment by twiecki** [comment]
Yeah, multilevel models are tricky. There are several potential strategies:
- Use NUTS and pass a good starting point without calling approx_hessian.
- To optimize: first fit the MAP of RVs that are directly connected to the data and then in a separate `find_MAP` call the group nodes. 
- Select a point by hand that should work well.
- Use find_hessian() instead of approximate_hessian().

If none of these work you can paste the model you have.

**Comment by fonnesbeck** [comment]
Closing. Please re-open if this issue is ongoing.
