### ISSUE TITLE
Faling test_variational_inference.py::test_fit_fn_text

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6127]
This test failed a couple of times in #6113 

test_variational_inference.py::test_fit_fn_text[asvgd-kwargs6-TypeError]

https://github.com/pymc-devs/pymc/actions/runs/3053220065/jobs/4923561777

**Comment by ricardoV94** [comment]
CC @ferrine @fonnesbeck

**Comment by ricardoV94** [comment]
Failed again in https://github.com/pymc-devs/pymc/actions/runs/3053791757/jobs/4924868962

**Comment by ricardoV94** [comment]
Seems to fail on Windows only. It passes locally for me.

**Comment by Armavica** [comment]
It fails for me on linux on commit ec27b5c but not on commit bbb3082.

More precisely because the commits have been squashed, 1bd4fda2 is the first commit where the test fails.

Commenting out this line makes the test pass by me: https://github.com/pymc-devs/pymc/commit/1bd4fda2e70975f82fa0d7319b0dc3f42e6826f5#diff-f159494798d11be8eb28b2085c0e5a306f99ed4fb61020cbc16e300a42b65944R637

**Comment by ricardoV94** [comment]
I see the test was failing in the PR itself: https://github.com/pymc-devs/pymc/actions/runs/3003933042/jobs/4826249787.

I will revert it for the time being. CC @markusschmaus
