### ISSUE TITLE
Weird interaction between for loop and aesara.scan result in bug

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#6148]
Reported by user in https://discourse.pymc.io/t/aesara-scan-creating-weird-intermediate-variables-that-crash-the-model/10473/4

**Please provide a minimal, self-contained, and reproducible example.**
```python
with pm.Model() as model:
    m = pm.Uniform("m0", lower=0, upper=1)        # Init the state

    # Broken with Normal
    # delta = pm.Normal("delta", mu=0, sigma=1)     
    # Works with Uniform
    delta = pm.Uniform("delta", lower=-1, upper=1)     
    
    def step(prev, d): # System dynamics
        return prev + d
    
    for i in range(10): # Time loop
        res, _ = aesara.scan(step, outputs_info=[m], n_steps=3, non_sequences=[delta])
        m = res[-1]
        pm.Normal(f"inter_{i}", mu=m) # Extracting an intermediate "measurement"
    
    trace = pm.sample()
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
File /opt/homebrew/Caskroom/miniforge/base/envs/pymc2/lib/python3.10/site-packages/pymc/step_methods/hmc/base_hmc.py:107, in <listcomp>(.0)
    101 # We're using the initial/test point to determine the (initial) step
    102 # size.
    103 # XXX: If the dimensions of these terms change, the step size
    104 # dimension-scaling should change as well, no?
    105 test_point = self._model.initial_point()
--> 107 nuts_vars = [test_point[v.name] for v in vars]
    108 size = sum(v.size for v in nuts_vars)
    110 self.step_size = step_scale / (size**0.25)

KeyError: 'delta0'
```

**Comment by ricardoV94** [comment]
It seems compling the aesara function of the dlogp is altering the name of one of its input variables. Opening an issue in Aesara https://github.com/aesara-devs/aesara/issues/1216

**Comment by brandonwillard** [comment]
While we can put in a change for this, it bears repeating that `Variable` names are not treated (or expected to be) identifying properties/attributes of a particular `Variable` instance.  All `Variable` instances are distinct, so the only consistent way to keep track of `Variable`s is directly via their instance objects (or `id`s, perhaps).

This point was brought up multiple times while I was writing v4 and was even addressed explicitly in a few design choices.  Now that I've been away from the codebase for a while, I don't know what the status on this issue is anymore, but it's clearly something from which the codebase hasn't completely moved away yet, so I highly recommend adding this issue as a priority TODO&mdash;if there isn't one for it already.
