### ISSUE TITLE
pymc.math.sum(xxx, axis=yyy) does not support axis kwarg being an xarray dim name

### ISSUE THREAD

**Issue by JonAnCla** [pymc-devs/pymc#6178]
## Description of your problem

`axis` kwarg of `pymc.math.sum` and similar functions require axis to be an int index into the shape of provided input to sum, and throw when an xarray dimension name is provided instead.

Having to use dimension indexes numbers instead of labels means we can't benefit from using xarray for these situations.  

Code is more fragile and less readable when we have to use a dimension index.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc
import xarray

with pymc.Model() as model:
    model.add_coord('subset', ['A', 'B'])
    model.add_coord('type', ['t1', 't2', 't3'])
    var = pymc.Normal('noise', mu = 0, sigma = 1, dims = ['subset', 'type'])

    z = pymc.math.sum(var, axis = 'subset')  # raises TypeError
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [40], in <cell line: 4>()
      6 model.add_coord('type', ['t1', 't2', 't3'])
      8 var = pymc.Normal('noise', mu = 0, sigma = 1, dims = ['subset', 'type'])
---> 11 z = pymc.math.sum(var, axis = 'subset')

File ~/.pyenv/versions/3.10.2/envs/test-mcmc/lib/python3.10/site-packages/aesara/tensor/math.py:2515, in sum(input, axis, dtype, keepdims, acc_dtype)
   2495 def sum(input, axis=None, dtype=None, keepdims=False, acc_dtype=None):
   2496     """
   2497     Computes the sum along the given axis(es) of a tensor `input`.
   2498 
   (...)
   2512 
   2513     """
-> 2515     out = Sum(axis=axis, dtype=dtype, acc_dtype=acc_dtype)(input)
   2517     if keepdims:
   2518         out = makeKeepDims(input, out, axis)

File ~/.pyenv/versions/3.10.2/envs/test-mcmc/lib/python3.10/site-packages/aesara/graph/op.py:297, in Op.__call__(self, *inputs, **kwargs)
    255 r"""Construct an `Apply` node using :meth:`Op.make_node` and return its outputs.
    256 
    257 This method is just a wrapper around :meth:`Op.make_node`.
   (...)
    294 
    295 """
    296 return_list = kwargs.pop("return_list", False)
--> 297 node = self.make_node(*inputs, **kwargs)
    299 if config.compute_test_value != "off":
    300     compute_test_value(node)

File ~/.pyenv/versions/3.10.2/envs/test-mcmc/lib/python3.10/site-packages/aesara/tensor/elemwise.py:1735, in CAReduceDtype.make_node(self, input)
   1731 assert op.acc_dtype is not None
   1733 # TODO: Why doesn't `make_node` just take these
   1734 # automatically-determined values as arguments?
-> 1735 return super(CAReduceDtype, op).make_node(input)

File ~/.pyenv/versions/3.10.2/envs/test-mcmc/lib/python3.10/site-packages/aesara/tensor/elemwise.py:1296, in CAReduce.make_node(self, input)
   1293 if axis is None:
   1294     axis = list(range(inp_dims))
-> 1296 copy_op = any(a < 0 for a in axis)
   1297 # scalar inputs are treated as 1D regarding axis in this `Op`
   1298 try:

File ~/.pyenv/versions/3.10.2/envs/test-mcmc/lib/python3.10/site-packages/aesara/tensor/elemwise.py:1296, in <genexpr>(.0)
   1293 if axis is None:
   1294     axis = list(range(inp_dims))
-> 1296 copy_op = any(a < 0 for a in axis)
   1297 # scalar inputs are treated as 1D regarding axis in this `Op`
   1298 try:

TypeError: '<' not supported between instances of 'str' and 'int'
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version: 4.1.4
* Aesara/Theano Version: aesara 2.7.9
* Python Version: 3.10.2
* Operating system: Ubuntu 20.04
* How did you install PyMC/PyMC3: (conda/pip) pip

**Comment by ricardoV94** [comment]
@hottwaj I noticed you have opened similar type of issues regarding xarray-like dims in PyMC operations recently.

They are not supported and there are no immediate plans to support them because we rely on Aesara which at the moment has no support for dims. The only dims support we have is for specifying the shape of PyMC variables or labeling the dimensions of variables wrapped in pm.Deterministic.

Please do not open more issues like this, unless they refer to a specific bug or feature that is not working as advertised.

If you want PyMC to integrate dims more seamlessly the place to discuss that is in Aesara. You will already find some discussions to that matter in their GitHub. You are welcome to express your interest in there.

Best regards :)

**Comment by JonAnCla** [comment]
Hi Ricardo, thanks and sorry if these issues were annoying, that was definitely not my intention.

My impression from pymc docs was that integrating xarray labelling into pymc was a neat new addition (to me, it is definitely a useful and important new feature), so I was trying to document areas where this feature seemed to be lacking and this one in particular I think is an important one that wasn't already mentioned on here.

Thanks for clarifying that aesara is the place for issues like this, it was not obvious to me that that is the place to look (e.g. pymc.Model.add_coord is in pymc and seems to be the basis of xarray support in pymc)

Thanks

**Comment by JonAnCla** [comment]
Also I did do a brief check on aesara before posting and there is currently no support for xarray in its code.  The only thing I found was this issue:

https://github.com/aesara-devs/aesara/issues/352

So would it be right to say that it is pymc is doing the "translation" between xarray dims/coords and underlying axes?

Thanks

**Comment by ricardoV94** [comment]
No worries. If the PyMC documentation is misleading/ confusing about how much compatibility there is with xarray API, it could be a good place for contributing (such as opening an issue asking for clarification and even addressing that issue).

Right now Aesara advertises numpy API compatibility and that's what PyMC can mostly offer. Xarray dims is mostly there for labelling so that outputs of sampling can be easily manipulated with xarray tools afterwards.

There is no reason why you would have to know that the "limitation" lies at the Aesara level. I just wanted to clarify that. Apologies if I wrote too rudely.

Thanks for your time

**Comment by JonAnCla** [comment]
Thanks understood & no problem.  Also please ignore my previous message of a few minutes ago, you already stated the same in your first message and I didn't quite read it properly :)

Thanks again!
