### ISSUE TITLE
Require `supports_sampler_stats=True` for all `BaseTrace`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6193]
We don't have a backend that doesn't support it, and by requiring support we can simplify code.

**Comment by williambdean** [comment]
I'm interested in taking this issue in order to learn more about the backends submodule. 

Could you give a little more details? Is this looking to remove the `supports_sampler_stats` attribute or just change default to True? I'm see that it is used in a [few places](https://github.com/pymc-devs/pymc/search?q=supports_sampler_stats).
Is the `BaseTrace` class still meant to be extended?

Thanks

**Comment by michaelosthege** [comment]
I think removing it right away should be fine.
My plan is to morph `BaseTrace` closer to [`mcbackend.Chain`](https://github.com/michaelosthege/mcbackend/blob/b37dc475705fe3a1541002bcb4c43144c8917e57/mcbackend/core.py#L50) to make it easier to switch.
#6188 was part of that and so is #6192.

I you take on this issue it will help too!

**Comment by williambdean** [comment]
Great. Thanks for the context @michaelosthege 

Okay. What I will do is remove all references to `supports_sampler_stats` and assume that is True. If there is any logic using `supports_sampler_stats` = False (ie raising Errors), I will remove those as well unless it depends on another condition. 

Basically will follow the flow of logic where `supports_sampler_stats` = True

I will take a stab and open a PR

**Comment by michaelosthege** [comment]
sounds good, @wd60622 !
ping me for review when ready

**Comment by michaelosthege** [comment]
Closed by #6205 / 534b89bb73c11eb32f65b71344199b45717c8914
