### ISSUE TITLE
GitPod instructions

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#6215]
## Description of your problem
Some questions on GitPod:
a) Does Gitpod for PyMC work for all repos, or some repos?
b) Do we need to add links to Gitpod?
c) Do we need to add instructions for Gitpod?

Example:
https://jupyterlab.readthedocs.io/en/3.1.x/api/index.html

cc:  @maresb @cluhmann @rowangayleschaefer 

<img width="629" alt="Screen Shot 2022-10-13 at 1 03 18 PM" src="https://user-images.githubusercontent.com/2507232/195660079-489eec35-2124-4773-9422-4d7fc5e58ecf.png">

**Comment by maresb** [comment]
Thanks for following up with this. On my pymc fork [here](https://github.com/maresb/pymc) I put in a bunch of commits towards improving the GitPod experience.

GitPod is very closely related to VS Code [devcontainers](https://code.visualstudio.com/docs/remote/containers). I have quite a lot of experience with devcontainers, but this is my first experience with GitPod. There are some differences, and @rowangayleschaefer has been really helpful in explaining them and helping me to test.

My current effort stalled a bit due to some contributions I've been making to upstream tools and also my travel plans. We were trying to understand how Live Share works, which is effectively Google Docs-style collaborative editing. It doesn't seem to work directly on GitPod over the browser, but I suspect that it might work with VS Code. I could test that with @rowangayleschaefer if we coordinate some time to test it.

One of the biggest issues at the moment in my mind is that it takes about 5 minutes or so to start up because it has to download and install all the dependencies. GitPod is supposed to have [a feature to alleviate this](https://www.gitpod.io/docs/configure/projects/prebuilds), but I think it doesn't work at the level I would expect, and it doesn't seem very useful to me. (This makes me wonder if I'm understanding it correctly.)

In any case, I think it's useful to have a Docker image which is suitable as both a devcontainer and a GitPod, which is what I've mostly accomplished in my branch. It should be mostly ready-to-go. Do we have any GitPod specialists who might be able to review what I've done?

As for the specific questions:

> a) Does Gitpod for PyMC work for all repos, or some repos?

I haven't been paying that close attention, but it only works for PyMC or any other repo where someone has added a `gitpod.yml` file.

> b) Do we need to add links to Gitpod?

Once we believe it's far along enough to be helpful, I think we could add a link/badge to the README.

> c) Do we need to add instructions for Gitpod?

Yes

**Comment by rowan-schaefer** [comment]
My experience with gitpod is mainly using it to alleviate setup barriers in educational settings, so I have less experience integrating it into a development workflow with git. Also, minimal experience with live share, but I'm always willing to help test!

I've been doing some [reading](https://github.com/gitpod-io/gitpod/issues) to get a better handle on terminology, and potentially solve the prebuild issue

I agree with @maresb on point C. 

In general it would not need to be too much explanation. With gitpod you don't need to have conda, python, or dependencies installed - so I can contribute from a library computer or an iPad if I wanted to!
(Theoretically, if my phone was bigger, I could contribute from mobile.)

It should be as easy as clicking the button, or modifying the URL to open the repository in gitpod. (@reshamas this is what I was using when I screen shared the other day.) 

In regards to their open source program, it seems this is on an individual level, with GitHub users who have made >n contributions being qualified automatically. It's possible all the regular pymc contributors already have unlimited hours of use - [thread](https://twitter.com/gitpod/status/1493953590167232527)

**Comment by ferrine** [comment]
I support the efforts to improve gitpod integration. I use it extensively, in a setup where I have computer that is not supposed to lift tests, and usually runs on a battery. gitpod it super useful.

I appreciate the instructions in the readme, special care should be taken for prebuilds. I found this the most confusing.
