### ISSUE TITLE
Do not compute model `log_likelihood` by default at the end of sampling

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6266]
This evaluation can be quite expensive and require too much memory. I think it's safe to say most users don't make use of this information (nor most of our tests where we choose to return inferencedata), making it pretty wasteful.

It's also trivial to provide an API to obtain it after the fact:

```python
with model:
  idata = pm.compute_log_likelihood(idata, extend_inferencedata=True)
```

My suggestion is to add that API, and make the automatic computation at the end of sampling opt-in rather than opt-out as it is now, if a user already knows they will want it.

```python
with model:
  idata = pm.sample(idata_kwargs={"log_likelihood": True})  # Otherwise it's not computed by default
```

I would even consider deprecating that `idata_kwargs` option to keep `pm.sample` a bit more simple, but no strong opinion there

CC @OriolAbril

**Comment by OriolAbril** [comment]
Test wise log likelihood can be turned off using rcparams even before we do this: https://github.com/arviz-devs/arviz/blob/main/arvizrc.template#L10.

I am not opposed to the change but I would modify the rcparam used for this so that the same way users who don't want this default can change it on a personal or project basis, the ones that like the default can continue to use it.

Regarding idata kwargs I would keep it as it also allows other arguments to be passed to the converter. What might be a good idea would be refactoring the converter.

Whatever default we end up using I would love the compute log likelihood function

**Comment by ricardoV94** [comment]
> I am not opposed to the change but I would modify the rcparam used for this so that the same way users who don't want this default can change it on a personal or project basis, the ones that like the default can continue to use it.

Is this a possibility? Is PyMC the only library that makes use of that argument?

> Regarding idata kwargs I would keep it as it also allows other arguments to be passed to the converter. What might be a good idea would be refactoring the converter.

I meant just the log-likelihood option, but it's fine to leave it, specially if it's already an option in rcParams.

We definitely want to keep the functionality to compute it, the main question was just not to do it by default.

**Comment by OriolAbril** [comment]
> Is this a possibility? Is PyMC the only library that makes use of that argument?

I think other libraries use it too, but it might still be possible to change it.
