### ISSUE TITLE
Binary variable gets assigned poisson proposal distribution

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#627]
This was mentioned by Tom Minka here: http://stats.stackexchange.com/questions/120028/2-gaussian-mixture-model-inference-with-mcmc-and-pymc

`For category, the default proposal_distribution = 'Poisson' which gives poor results (I don't know why this is, but it certainly doesn't sound like a sensible proposal for a binary variable).`

**Comment by tminka** [comment]
This issue came up again in another model: http://stats.stackexchange.com/questions/121936/simple-model-selection-example-in-pymc
Changing the proposal_distribution of a binary variable from 'Poisson' (default) to 'Prior' was necessary to get sensible results.

**Comment by fonnesbeck** [comment]
This should be fixed by 7006608f6. The issue was that a Categorical likelihood will automatically be assigned a `DiscreteMetropolis` rather than a `BinaryMetropolis` step method, since in general there are k categories (the Bernoulli likelihood was intended for variables that are binary). With this change, a Categorical with k=2 will be assigned a `BinaryMetropolis` step method. Should be working in master, but open an issue on pymc-devs/pymc if something is still amiss.
