### ISSUE TITLE
`_LKJCholeskyCovRV` doesn't have its `dtype` and `size` as `Op` inputs

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc#6289]
## Description of your problem

I'm trying to work on adding a dispatcher that computes the expected values of the distributions and it expects all RV `Op`s to have the following inputs:
1. The random generator
2. `size`
3. `dtype`
4. Other distribution specific inputs

For some reason, `_LKJCholeskyCovRV` doesn't comply with this anymore. I'm not sure when this changed, but it was working with pymc 4.1.1, but with 4.3.0 it isn't.

**Please provide a minimal, self-contained, and reproducible example.**
```python
>>> import pymc as pm
>>> pm.LKJCholeskyCov.dist(eta=1., n=3, sd_dist=pm.DiracDelta.dist(1), compute_corr=False).owner.inputs
[RandomGeneratorSharedVariable(<Generator(PCG64) at 0x7F24707C73C0>),
 TensorConstant{3},
 TensorConstant{1.0},
 diracdelta_rv{0, (0,), None, False}.out]
```

You can compare against a standard normal distribution where the second and third inputs are the `size` and `dtype`.
```
>>> pm.Normal.dist(0, 1).owner.inputs
[RandomGeneratorSharedVariable(<Generator(PCG64) at 0x7F2470FAE900>),
 TensorConstant{[]},
 TensorConstant{11},
 TensorConstant{0},
 TensorConstant{1.0}]
```

## Versions and main components

* PyMC/PyMC3 Version: 4.3.0
* Aesara/Theano Version: 2.8.7
* Python Version: 3.8.13
* Operating system: Ubuntu 18.04
* How did you install PyMC/PyMC3: (conda/pip) pip

**Comment by ricardoV94** [comment]
For context, `_LKJCholeskyCov` stopped being a `RandomVariable`, and became a `SymbolicRandomVariable`. These don't promise the same API, and should not be treated as being `RandomVariable`s in general (in many cases they can, but that must always be assessed). 

In this case, it meant the signature of the node changed and the dispatch method had to be updated. Same thing would have happened if for some reason we had added a new input to `_LKJCholeskyCov`. It's simply a new object.

***

A discussion about making the API of `SymbolicRandomVariables` more similar to that of `RandomVariables` can be had, but note that there are many other things that are different (some `SymbolicRandomVariable`s don't even have RNGs, others have multiple ones, and for some cases they must appear as the last input due to OpFromGraph limitations). We also don't offer info about `ndim_params`, and so on... All this complexity is avoided with `SymbolicRandomVariable`s at the cost of them... well not being `RandomVariable`s :)

The most important difference, however, is that we don't offer `size` parametrization: That would require nesting every RV used by the SymbolicRV in its inner graph, which would require making the inputs of said RVS also inputs of the SymbolicRVl. These would grow exponentially as you nest SymbolicRVs. For instance for a Mixture, you would need to make all the inputs of the components, inputs of the SymbolicRV, and if you nest mixtures you would need to make the inputs of the inner Mixtures, inputs of the root level Mixture as well. Because of that we don't offer size, but instead offer an eager `change_dist_size`, which will recursively clone and resize all input RVs until the SymbolicRV has the right size.

**Comment by ricardoV94** [comment]
@lucianopaz let me know if it makes sense, in which case we can close this issue.
