### ISSUE TITLE
DOC: wrong bound for `sigma` in docstring of `Beta`

### ISSUE THREAD

**Issue by Gattocrucco** [pymc-devs/pymc#6295]
The docstring of `Beta` says

```
sigma : tensor_like of float, optional
    Alternative standard deviation (1 < ``sigma`` < sqrt(``mu`` * (1 - ``mu``))).
```

while it should be `0 < sigma < ...`.

(Related issue: #5023 says that `sigma` may be dropped in favor of `nu`)

## Versions and main components

* PyMC/PyMC3 Version: 4.3.0
* Aesara/Theano Version: 2.8.7
* Python Version: 3.10.5
* Operating system: macos 12.6.1 arm
* How did you install PyMC/PyMC3: pip

**Comment by ricardoV94** [comment]
Seems to have been changed (accidentally?) in https://github.com/pymc-devs/pymc/pull/5500

@Gattocrucco Do you want to add a PR to fix it?

About #5023 we would probably add it as an alternative parametrization, instead of deprecating `sigma` completely because many users probably rely on it. Feel free to take on that PR as well if you are interested :)

**Comment by alekracicot** [comment]
Is anyone working on this? If not I can do it.

**Comment by ricardoV94** [comment]
> Is anyone working on this? If not I can do it.

Go ahead
