### ISSUE TITLE
Website navigation bar links are broken from examples/docs sections

### ISSUE THREAD

**Issue by sharpsy** [pymc-devs/pymc#6308]
## Description of the problem

Website navigation bar links are broken from examples/docs sections. Once Examples, Learn, or API sections are visited, the rest of the navigation bar hyperlinks lead to "Page not found" or "The page isn’t redirecting properly".

**Please provide a minimal, self-contained, and reproducible steps.**
1) Visit the PyMC homepage (https://www.pymc.io/)
2) Click on the any of 'Examples', 'Learn', or 'API' links in the top navigation bar.
for example: https://www.pymc.io/projects/examples/en/latest/gallery.html)
3)  Click on 'Home', 'Community', or 'Contributing' links in the top navigation bar.
examples of linked location:
https://www.pymc.io/projects/examples/en/latest/https%3A//www.pymc.io.html
https://www.pymc.io/projects/docs/en/stable/https%3A//www.pymc.io/welcome.html.html)
4) Observe the 'Page nor found' or 'The page isn't redirecting properly'

**Comment by OriolAbril** [comment]
All of this is already fixed (except for 4.2 and maybe the 4.1 version slugs). It was fixed by https://github.com/pymc-devs/pymc.io/pull/57, https://github.com/pymc-devs/pymc/pull/6296 (plus the release to get the changes from latest to stable, the default), https://github.com/pymc-devs/pymc-examples/pull/465
