### ISSUE TITLE
Hessian (d2logp) has the wrong sign

### ISSUE THREAD

**Issue by cscheffler** [pymc-devs/pymc#6310]
In PyMC, the Hessian of the a model is [defined as](https://github.com/pymc-devs/pymc/blob/7ccfdaa891ec05c5af2ba69ad548ebefbc6882f3/pymc/aesaraf.py#L520) $-\nabla\nabla\log f$ and not $\nabla\nabla\log f$ which is the generally accepted mathematical definition, as the collection of second-order derivatives.

I accept that there is probably a good reason for computing the negative Hessian rather than the Hessian but, for clarity when reading the code and documentation, could these functions be renamed to indicate that this is the negative Hessian?

Context: For pedagogical/demonstration purposes, I am implementing the [Laplace approximation](https://en.wikipedia.org/wiki/Laplace%27s_approximation) using the `logp`, `dlogp`, and `d2logp` functions and the sign error in `d2logp` took me a long time to figure out, eventually by looking through the code and finding the definition of `aesaraf.hessian`.

**Comment by aseyboldt** [comment]
Yes, I think that's pretty terribly broken, and we should fix it.
I'm a bit afraid that some code out there now depends on the incorrect sign, but leaving it as it is will probably lead to more confusion than is worth it.
My guess as to why it is like this is probably because this was at some point used to initialize scale parameters for MCMC samplers, and wasn't really meant as an external function.
