### ISSUE TITLE
Record values that are not theano nodes

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#650]
It is common to want to record the output of a computation alongside the rest of the trace. We allow this with `Deterministic`. However, we also require the input to `Deterministic` to be a theano expression. This is required if the deterministic is transforming values that then tie into a likelihood, but if it's purely recording values it should not matter.

We should make this easier. Ideas?

**Comment by tyarkoni** [comment]
Haven't looked at the code in detail, so I'm not sure this makes sense, but would it be possible to add some kind of logging functionality to BaseTrace that allows arbitrary data to be attached in each sample? That would probably be the most flexible way to go, if a bit inelegant. Then maybe add a LoggedVar class in pymc/model that wraps around that, so that instead of having to use as_op() to wrap a theano expression and pass it to deterministic, one could do something like:

``` python
with pm.Model as model:
   my_arbitrary_data = LoggedVar('prediction', predicted_value)
```

...and that would show up in the trace as a separate property. Not sure this would work, just a thought... am happy to try to work up a PR with some guidance when I have a larger chunk of time.

**Comment by twiecki** [comment]
Not a bad idea. We could also try to to auto-wrap non-theano expressions passed to `Deterministic` with `as_op`. Would make the whole thing quite a bit easier. Maybe issue a warning that gradients can not be computed.

@bjedwards Would be curiours to hear your thoughts.

**Comment by twiecki** [comment]
Sorry, meant to CC @kyleam here.

**Comment by kyleam** [comment]
Sorry, I intended to comment earlier.

I agree this would be nice to have. At least at first glance, I'd favor keeping trace objects ignorant of how values are produced.  Currently, traces just know that there are variables with some name and shape, and they're only responsible for recording the values passed to them each iteration, not producing them.  So, I think this computation should happen upstream of calling the `record` method.

In terms of the trace having a separate property for accessing non-theano deterministic values, is there any reason to treat them different than other variables?  Right now, theano `Deterministic` variables are stored and accessed in the same way as other variables.  IIRC, this is true for PyMC 2 deterministic variables as well.

**Comment by jsalvatier** [comment]
Auto wrapping them in theano `as_op` seems like an attractive way to go.

**Comment by twiecki** [comment]
Not sure we can do that automatically as we'd have to detect which of them are not connected to any likelihood.

**Comment by aloctavodia** [comment]
is #2399 at least a partial solution to this?

**Comment by twiecki** [comment]
@aloctavodia I think so, yes. Can probably close.
