### ISSUE TITLE
Allow passing dims to `Potential`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6544]
Not important for InferenceData, since potentials don't produce any values that remain in the trace (unless a user wraps them in a Deterministic, which already accept dims), but it would be neat for `graphviz`.

It's a simple as forwarding dims here: https://github.com/pymc-devs/pymc/blob/562e51edf741e704ccdf755718a2cff6da217efb/pymc/model.py#L2052

**Comment by soma2000-lang** [comment]
@ricardoV94  orking on this

**Comment by Raj-Parekh24** [comment]
Hi @ricardoV94,

I have seen that this issue has been open for a long time and another member has raised no PR. I have started working on it and following the steps suggested by you.

The PR for this issue is #6576.

After solving the issue, I am thinking about whether a new test case is required to check the function working with dims. 

Please review the work and suggest changes accordingly.
