### ISSUE TITLE
Make sponsor images have the same size

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#6586]
### Description

Currently the sponsor section in the readme looks like this:
![image](https://user-images.githubusercontent.com/674200/224488037-15863bd4-18a9-443a-9b3d-874d72c269b8.png)

We should make it so that they all have the same size.

**Comment by aniketpancharia** [comment]
Hello @twiecki I would like to take up this issue can you please elaborate what would be the preferred end product of this image ?

**Comment by twiecki** [comment]
@aniketpancharia That's great. The way we have it on https://www.pymc.io/welcome.html would be ideal:

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/674200/224568062-4028fbbf-35b1-4314-af42-f4614cd5446b.png">

**Comment by aniketpancharia** [comment]
ok thanks for the help @twiecki

**Comment by 18bce133** [comment]
Hey @twiecki, I have tried to resolve this issue. Here's the [README](https://github.com/18bce133/pymc/tree/fix_sponsor_img) of my fork. It looks like this:

![image](https://user-images.githubusercontent.com/63655579/225588601-caf2e964-2414-4479-a6b0-50627d69a1fd.png)


 Let me know if you have anything else in mind. Thanks!

**Comment by twiecki** [comment]
@18bce133 That looks much better! If possible, would be nice to have a little padding/space between the logos, but no big deal if that's difficult. Feel free to open a PR.

**Comment by twiecki** [comment]
@18bce133 Ah, I just looked at how you did it, ideally there's a way in rst to scale images, you scaled the images directly.

**Comment by 18bce133** [comment]
Hi @twiecki, thank you for your reply and suggestions. I have resized image in rst rather than rescaling the image. I tried to do padding but [RST does not seems to have padding attribute](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/images.html) in image directive.
![image](https://user-images.githubusercontent.com/63655579/225829657-f2c438ce-3846-444f-a03b-a21691b6c649.png)

Let me know if any other changes are to be expected. Thanks !

**Comment by twiecki** [comment]
@18bce133 Much better, can you drop the height? The mistplay logo is getting squeezed a bit.

**Comment by 18bce133** [comment]
Hi @twiecki , Thank you for your reply and kind suggestions, I resized all the three images to same dimensions so that they appear symmetrical. But still as you suggested I have dropped the height of Mistplay Logo by 5px.

![image](https://user-images.githubusercontent.com/63655579/227421030-6b73af90-d1a1-4560-9442-1be4e111855d.png)

Let me know if any other changes are to be expected. Thanks !

**Comment by twiecki** [comment]
@18bce133 Great, want to open a PR?

**Comment by twiecki** [comment]
@18bce133 Any progress?

**Comment by reshamas** [comment]
@twiecki 
This issue is resolve via #6643 
See page:
https://github.com/pymc-devs/pymc/blob/main/README.rst
