### ISSUE TITLE
DOC: Bad Website Link

### ISSUE THREAD

**Issue by GeoffNordling** [pymc-devs/pymc#6732]
### Issue with current documentation:

Please see this post:
https://discourse.pymc.io/t/bad-website-link-installation-documentation/12197

The [introductory overview of PyMC](https://www.pymc.io/projects/docs/en/latest/learn/core_notebooks/pymc_overview.html#installation) says,

![1](https://github.com/pymc-devs/pymc/assets/33404577/3b0aa8eb-0f26-4d1e-9fcc-915a4b2392f2)

However, that link simply directs the reader to that same place. Clicking on it does nothing.

I believe the actual installation guide is here:
https://www.pymc.io/projects/docs/en/stable/installation.html

The link should point there instead.

**Comment by error9098x** [comment]
@GeoffNordling  Yeah, basically the issue was caused by the ref as the same ref name is used in the same page (https://www.pymc.io/projects/docs/en/latest/learn/core_notebooks/pymc_overview.html#installation ) , #installation was causing the issue, so I changed the ref name to #installationguide and also changed installation.md to installation.rst as markdown was somehow not working to reference back to installation page.
