### ISSUE TITLE
Implement default `moment` function for `CustomDist` provided with a `dist` function

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6804]
### Description

```python
import pymc as pm

def dist(mu, sigma, size):
  return pm.math.exp(pm.Normal.dist(mu, sigma size=size))`

with pm.Model() as m:
  ...
  x = pm.CustomDist("x", mu, sigma, dist=dist)

m.initial_point()
```

Since the `dist` is a symbolic forward graph, we could implement the `moment` automatically as
```python
def moment_dist(mu, sigma, size):
  return pm.math.exp(moment(pm.Normal.dist(mu, sigma, size))
```

Would just need to replace the RVs in the `dist` graph, by their moments.

**Comment by lucianopaz** [comment]
I'm kind of late to this issue but I need to comment that the expected value of the exponential of a Normally distributed random variable is not the exponential of the normal's location.

```python
>>> moment(pm.math.exp(pm.Normal.dist(mu, sigma, size)))
pm.math.exp(mu + sigma **2 / 2)
```

Just like the `Lognormal` distribution's moment. I do like the idea of being able to deduce the moments from the data generation process, and I like the approach of using a rewrite to do so, as what we do with `logp` graphs. The problem is that moments are integrals on the altered measures of some basic random variables. Maybe @maresb has some input on this topic, but to me it sounds like a mathematically challenging endeavor.

**Comment by ricardoV94** [comment]
With moment we're just looking for a nonzero density point to start sampling. We can call it something else, but definitely not confusing it with mean.
