### ISSUE TITLE
glm not picking up all factors

### ISSUE THREAD

**Issue by gabrielelanaro** [pymc-devs/pymc#689]
Hi, I was trying to implement a two way (bayesian) anova with the glm function. The data looks like this:

```
salary = pd.read_csv("/home/gabriele/workspace/bayesiandata/Salary.csv")
print salary.head()
print salary.Org.unique(), salary.Post.unique()

    Org Post  Salary
0  CEDP  FT1   89504
1  CEDP  FT1  106554
2  CHEM  FT1  108158
3  CEDP  FT1   92961
4  CHEM  FT1  154703
['CEDP' 'CHEM' 'BFIN' 'THTR'] ['FT1' 'FT2' 'FT3']
```

The code I'm using (I don't know if it's correct) is as follows. It looks like some factors are not picked up. (BFIN and FT1) Is there any way to fix that?

```
with pm.Model() as model:
    pm.glm.glm('Salary ~ Org + Post + Org:Post', salary)
model.vars

[Intercept,
 Org[T.CEDP],
 Org[T.CHEM],
 Org[T.THTR],
 Post[T.FT2],
 Post[T.FT3],
 Org[T.CEDP]:Post[T.FT2],
 Org[T.CHEM]:Post[T.FT2],
 Org[T.THTR]:Post[T.FT2],
 Org[T.CEDP]:Post[T.FT3],
 Org[T.CHEM]:Post[T.FT3],
 Org[T.THTR]:Post[T.FT3],
 sigma]
```

**Comment by twiecki** [comment]
`glm` just uses `patsy` for that. Perhaps @njsmith has any insight?

**Comment by njsmith** [comment]
They aren't getting lost, they're getting treatment coded :-). The idea is
that we pick a way of coding the categorical data that meets two criteria
1) every level (or combination of levels) should be able to take on its own
value in the model predictions. Here you have 4 \* 3 = 12 possible distinct
observations, and you've stated that you want each to be be to vary
separately (by writing "Org:Post"), so this means we need at least 12
parameters.
2) our model should be non-redundant, I.e. there should only be one set of
parameters that leads to each set of possible predictions. Otherwise you
end up in the situation where you have data showing that a + b = 1 and then
are trying to do statistical inference about the value of a. But a could be
anything... it depends on b! So this means that we need no more than 12
parameters, or our model inference will become undefined.

So together this means we should have exactly 12 parameters (for the glm
coefficients part of the model, anyway). And if you count, you'll notice
that that's exactly what happened :-).

To accomplish this, patsy first noted that you asked for an intercept
(since you didn't write -1 to remove it). So it used one parameter for an
intercept. Then it noticed that you wanted some main effects coded, because
you wrote Org + Post. So it added some parameters for those. If it had done
this in the naïve way, then we would have been over parametrized, so
instead it picked a "reference level". The fitted intercept parameter will
encode how the model predicts an observation will behave at the reference
level; the other parameters then encode the _difference_ between the
reference level and some other level.

Then something similar happens for the interaction term.

The " T." in the variable names is there to remind you that this has
happened, and that you're using _T_reatment coding.

This process, BTW, is what allows you to partition the variance in an
ANOVA: the parameters for each of your model terms are defined so that
they'll only be (significantly) nonzero if this term adds additional power
beyond the other predictors.

If you really want all this to just go away, try the formula: "-1 +
Org:Post". That'll remove all the lower order terms, so it'll use all 12
parameters encoding just the interaction in the naïve dummy-coded way.

If you want to learn more, there are lots of docs out there on formulas
(see most R tutorials) and on treatment coding, or on contrast coding
(which is the more general name). The patsy manual also includes a
technical explanation of how all the details here work. Good luck!

**Comment by gabrielelanaro** [comment]
Thank you very much for the detailed answer! Now I understand what the problem is (I'm teaching myself stats and this is really helpful)
