### ISSUE TITLE
DOC: `HSGP.prior_linearized` example raises error

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#7000]
### Issue with current documentation:

I'm running into issue with the example of the `HSGP.prior_linearized`
https://www.pymc.io/projects/docs/en/stable/api/gp/generated/classmethods/pymc.gp.HSGP.prior_linearized.html#pymc.gp.HSGP.prior_linearized

There is a `pymc.exceptions.NotConstantValueError` raised on the following line

```python
phi, sqrt_psd = gp.prior_linearized(Xs=Xs)
```
```text
Traceback (most recent call last):
  File "~/.../pymc/gp/hsgp_approx.py", line 290, in prior_linearized
    Xs, _ = self.cov_func._slice(Xs)
  File "~/.../pymc/gp/cov.py", line 189, in _slice
    [xdims] = constant_fold([xdims])
  File "~/.../pymc/pytensorf.py", line 1225, in constant_fold
    raise NotConstantValueError
pymc.exceptions.NotConstantValueError
```

I am running it with the latest main branch.

### Idea or request for content:

Maybe I am missing some context in the example that could be added within the page or the functionality has changed and the example should be removed

**Comment by twiecki** [comment]
CC @bwengals

**Comment by bwengals** [comment]
Looks like recent update to PyMC here broke this.  We can't use `constant_fold` there when `X` is passed as a mutable variable, the use case for that example.  

Previously I just had `.eval()` there, since the values of `X` can mutate but not the dimensions (and if they do, the warning will show).  @ricardoV94, is the `constant_fold` needed here or is there another way?

Also, `x_dims` is only actually used [here](https://github.com/pymc-devs/pymc/blob/cac99d95e2b88b677b2de5a8e413dc0a2e79c1b1/pymc/gp/cov.py#L190) to maybe give a warning.  This warning has come in handy for me from time, but would prioritize the HSGP example working over the warning. So another option is to get rid of this bit of code.

**Comment by ricardoV94** [comment]
In the `constant_fold` you can do a `raise...=False` and then have the warning logic only triggered when it did manage to constant_fold and figured out

**Comment by ricardoV94** [comment]
Alternatively you could be more strict and add a PyTensor assert, and don't support the "partial use of columns" case at all?

**Comment by wmbelk** [comment]
FYI; When I changed cov.py line 188, from:
def _slice(self, X, Xs=None):
        xdims = X.shape[-1]
        if isinstance(xdims, Variable):
            **[xdims] = constant_fold([xdims])** 

To be:
def _slice(self, X, Xs=None):
        xdims = X.shape[-1]
        if isinstance(xdims, Variable):
            **[xdims] = constant_fold([xdims], raise_not_constant=False)**

Overriding the default True on raise_not_constant... It seems to work.

**Comment by fonnesbeck** [comment]
<img width="638" alt="Screenshot 2024-02-08 at 5 19 33 PM" src="https://github.com/pymc-devs/pymc/assets/81476/70bb24d6-e604-4dc5-ad0e-e3ae3569052b">

I think I'm still getting this, even after building from main today.
