### ISSUE TITLE
ipython notebook kernel dies with njobs=4

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#707]
I'm trying to add multithreading to the [UQ book chapter](https://github.com/pymc-devs/uq_chapter/blob/master/reference/UQ Handbook Chapter.ipynb) by adding njobs=4 to one of the calls to `sample`, but it kills my kernel. Have you seen this before?

**Comment by twiecki** [comment]
Is this with theano master? They had some parallel fixes recently.

**Comment by PaulSorenson** [comment]
Using pymc3 '3.0' and theano 0.7.0 and so far haven't found a setting of njobs that doesn't crash my iPython kernel.  I pulled the latest theano from github and same deal.

**Comment by kyleam** [comment]
I tested the first `sample` call in the chapter with `njobs` set to 2 and 4, and my kernel survives.  Does yours seem to crash right away or mid-sampling?

---

Python 3.4.3
IPython 3.1.0
Theano 0.7.0
Linux

**Comment by jsalvatier** [comment]
Interesting

Python 2.7.3
Ipython 3.1
Theano 0.7.0
Ubuntu

I'll try Python 3

**Comment by twiecki** [comment]
This might in fact be a python 3 issue: https://github.com/stan-dev/pystan/issues/142

**Comment by PaulSorenson** [comment]
And my python is 3.4.3 on Fedora 21.  Thomas that link seems to indicate it is a Python 2 issue (contrary to my experience).

**Comment by PaulSorenson** [comment]
It worked without incident just now with progressbar=False and njobs=3.  With progressbar=True and no other changes it crashes, right around where the progress bar would have appeared.

**Comment by twiecki** [comment]
Interesting, can anyone confirm that it works without the progressbar?

**Comment by PaulSorenson** [comment]
I just ran latest github theano and pymc3 and updated ipython with "pip3.4 install --update ipython[notebook]".

Notebook doesn't crash with the progress bar when njobs > 1 although the progress bar doesn't show until it reaches 100% (except when njobs=1 which works as before).

The version of the notebook server is 3.1.0-cbccb68 and is running on:
Python 3.4.3 (default, Mar 22 2015, 11:46:05) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]

**Comment by twiecki** [comment]
Great, thanks. We should just disable the progress bar if `njobs != 1`.

**Comment by PaulSorenson** [comment]
I think this is all that is required ...

index 7f66987..c48afdc 100644
--- a/pymc3/sampling.py
+++ b/pymc3/sampling.py
@@ -68,7 +68,8 @@ def sample(draws, step, start=None, trace=None, chain=0, njobs

         chains = list(range(chain, chain + njobs))

-        pbars = [progressbar] + [False] * (njobs - 1)
+        pbars = [False] * njobs
+

         argset = zip([draws] * njobs,
                      [step] * njobs,

**Comment by PaulSorenson** [comment]
I think this could do the trick since there is already an if njobs > 1 block:

```
diff --git a/pymc3/sampling.py b/pymc3/sampling.py
index 7f66987..6c2c63f 100644
--- a/pymc3/sampling.py
+++ b/pymc3/sampling.py
@@ -68,7 +68,7 @@ def sample(draws, step, start=None, trace=None, chain=0, njobs

         chains = list(range(chain, chain + njobs))

-        pbars = [progressbar] + [False] * (njobs - 1)
+        pbars = [False] * njobs

         argset = zip([draws] * njobs,
                      [step] * njobs,
```

I can make a pull request if people are happy with that.

**Comment by kyleam** [comment]
I think we should work toward a solution for displaying progress
information for multiple chains.  For many analyses, people are going
to use multiple chains, and sampling will take a substantial chunk of
time, so there should be some way to monitor the status.

The current hack is based on the idea that having information about
one chain is better than no information at all, but of course the
chains can get into different states and one chain is not always very
representative of the other ones.  Although this hack is now pretty
useless in the notebook (since the complete bar just pops up at the
end), it still works for programs that aren't run in a notebook (to
the extent that information from just one chain is useful).

It'd be great if someone works out a way display progress for all jobs
in the notebook.  Outside of the notebook, this could be as simple as
each chain spitting out "N / M" every so many iterations (similar to
CmdStan).

Perhaps we could have a few different methods for displaying sampling
progress and choose based on the whether the code's being run in a notebook (is this
easy to know?).

**Comment by twiecki** [comment]
@kyleam I agree, it would definitely be a nice feature.
I think a way to check whether in an IPython NB is:

``` python
try:
   get_ipython()
except NameError:
   # not in IPython
```

**Comment by datnamer** [comment]
Wonder if dask by @mrocklin can be of any assistance here or for any more involved parallelization.  It would be a pure python dependency. http://dask.pydata.org/en/latest/ 

@kyleabeauchamp might be interested in this for #610 and #659

**Comment by mrocklin** [comment]
Sorry for the late reply.  Looking at this issue it seems like it's about a particular issue in reporting on your current parallelism solution.  

If there is any interest in leveraging the dask schedulers within `pymc3` let me know and I'll start an issue for discussion.  Also happy to have informal video/email chats if that's better for seeing if there is a good interaction point.

**Comment by fonnesbeck** [comment]
I have not seen this behavior for awhile. Closing this, but feel free to reopen if the need arises.
