### ISSUE TITLE
Show `Implementing a RandomVariable` as the last entry in `How-to`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7099]
### Description

![image](https://github.com/pymc-devs/pymc/assets/28983449/7c696837-33fb-4274-b965-5488fa23adaf)

Or even move it to another section. Right now it will be the first thing suggested after the PR step-by-step guide

**Comment by OmGhadge** [comment]
Hi , I fixed the issue but since building docs is not supported on windows I am trying to run pymc in docker but I'm facing some issue . I've provided details about the problem in a post on the PyMC discussion forum, and I would greatly appreciate your  guidance. -https://discourse.pymc.io/t/trouble-building-pymc-docker-image-on-windows/13654?u=omghadge.

**Comment by ricardoV94** [comment]
@OmGhadge if you open a PR there will be a preview, so maybe it will just work out of the box and you will be able to check on the preview
