### ISSUE TITLE
ENH: Customizable plate labels

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#7319]
### Before

```python
# Currently would have to create graphviz instance
graph = pm.model_to_graphviz(model)
# Save output to .dot file and manually modify subgraph labels
print(graph)
# Resave as pdf using dot cli 
```

### After

```python
# Might be similar to that of where the entry point to the change would be in `pm.model_to_graphviz`

def named_vars_plate_label(
    var: TensorVariable, 
    named_vars_to_dims: dict[str, Sequence[str]], 
    dim_lengths: dict[str, int],
) -> str: 
    dims = named_vars_to_dims[var.name]
    return " x ".join(str(dim) for dim in dims)
    
plate_formatters = {
    "Named Vars": named_vars_plate_label,
}
pm.model_to_graphviz(model, plate_formatters=plate_formatters)
```

### Context for the issue:

I am interested in making graphviz diagraphs with a bit more customization of the plate labels than currently supported. Specifically, I would like to allow for labels without the shape size to provide a more abstract representation of the model. My specific example might look like this:
![example-graph](https://github.com/pymc-devs/pymc/assets/57733339/7d0ef911-a96c-4ac7-ac76-88b7163f771c)

I am willing to take up this issue. Wondering if there are any preferences on the implementation details? My idea would involve extracting this logic [here](https://github.com/pymc-devs/pymc/blob/main/pymc/model_graph.py#L311-L327) and providing some logic based on: 
- var : TensorVariable
- named_vars_to_dims : var.name mapping to coord names
- dim_lengths : coord names mapping to either TensorVariable or pre-evaluated shapes (addressing [this TODO](https://github.com/pymc-devs/pymc/blob/43b40de8ee84d7ad9813c83824a850b4dce8f924/pymc/model_graph.py#L305-L307))

Related to #6716

**Comment by ricardoV94** [comment]
How does this differ from https://github.com/pymc-devs/pymc/pull/7302 ?

**Comment by wd60622** [comment]
> How does this differ from https://github.com/pymc-devs/pymc/pull/7302 ?

7302 is styling of the nodes and this is name of the labels for each plate (label in bottom of each rectangle)

**Comment by ricardoV94** [comment]
I feel that may be going too far? Can it be done after a canonical graph was created by PyMC from the outside?

**Comment by ricardoV94** [comment]
Regarding shape size specifically we can disable that with a boolean flag, if that's all you need?

**Comment by ricardoV94** [comment]
The networkx path may not be too crazy?

**Comment by wd60622** [comment]
I explore this a bit and I wasn't able to get the result that I wanted. 

The cons of it: 
- `networkx` converts to `pygraphviz` instead of `graphviz` which requires an additional dependency
- Plate information seems to be lost after it is converted via `networkx`
- Also, parsing of labels would have to happen regardless

I think an `include_shape_size` boolean flag would be the easiest way to go. What are your thoughts on this? @ricardoV94

**Comment by ricardoV94** [comment]
Ideally we would have a very bare bones utility that gives users the model tree structure and let them do whatever they want with it.

Our graphviz gen could use this utility, but the code would be Simple enough for someone to just copy and tweak without we having to offer customization for all the visual elements that accidentally became the default?

If that feels like too much work, that's fair and we can add one more kwarg. But since people are becoming interested in this I worry about the next feature requests that come after.

WDYT?

**Comment by wd60622** [comment]
> Ideally we would have a very bare bones utility that gives users the model tree structure and meta info and let them do whatever they want with it.
> 
> Our graphviz gen could use this utility, but the code would be simple enough for someone to just copy and tweak without we having to offer customization for all the visual elements that accidentally became the default?
> 
> If that feels like too much work, that's fair and we can add one more kwarg. But since people are becoming interested in this I worry about the next round of feature requests.
> 
> WDYT?

Yeah, this is a bit of what I had in mind with the initial solution and where I was headed with the #7302 PR. That there would be some underlying generator(s) that could just provide the people with the information that they'd like. Also, that would be used to support the current methods (seems like the graphviz and networkx methods are a bit intertwined and might have some consolidation).

I can think about the implementation a bit. Do you have any thoughts on how you'd like it implemented?

**Comment by ricardoV94** [comment]
> I can think about the implementation a bit. Do you have any thoughts on how you'd like it implemented?

No, but very curious what you can come up with!
