### ISSUE TITLE
What are your pymc3 priorities? 

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#749]
What do you think are the most important things to add/fix and why? 

I figure its a good idea to see what everyone prioritizes. 

I'll put my own priorities below.

**Comment by jsalvatier** [comment]
- PyMC3 is kind of slow right now, even with metropolis (https://github.com/pymc-devs/pymc3/issues/739). 
- I'm not sure if people are still having issues with starting finding reasonable starting points and getting NUTS not to stall out, but these are important to fix (https://github.com/pymc-devs/pymc3/issues/555). 
- Fixing other usability issues that make using pymc require more expertise.

**Comment by fonnesbeck** [comment]
Depends on whether we are talking long- or short-term priorities. The first two on your list are big ones for me in the short term, now that missing data has been taken care of. I still get a lot of linear algebra errors (particularly singular matrix issues).

Putting a friendly face on `scan` and `map` will be important, as many models will require looping over other variables or data. Just a nice functional interface on these functions would make them friendlier and less error-prone.

Some other things are more long-term (post-beta):
- random number generators, so that methods like particle filtering and approximate Bayesian computing can be implemented
- non-parametrics
- approximation-based fitting methods (e.g. variational Bayes and expectation propagation)

**Comment by jsalvatier** [comment]
I'm mostly thinking short term priorities. Curious which models are giving you singular matrix issues.

**Comment by fonnesbeck** [comment]
@jsalvatier well, [since you asked](http://nbviewer.ipython.org/gist/fonnesbeck/ac400c96e1d4c9014662)

**Comment by fonnesbeck** [comment]
And if I substitute the `GaussianRandomWalk` (a la the GHME example) for the GP, the model churns away for a long time (>20 min) before slowly starting to sample.

**Comment by fonnesbeck** [comment]
Here is an example of a PyMC 2.3 node that is difficult to implement in PyMC 3. Its a deterministic that calculates the remaining number of susceptibles in a disease model by subtracting the cumulative number of infected individuals, looped over time and space. So, `I` is a rectangular stochastic that represent the number of infections, and `S_0` is a vector of initial susceptibles.

```
@deterministic
def S(I=I, S_0=S_0):
    return np.array([S_0[d] - np.array([I[d,:t].sum() 
                    for t in range(t_obs+1)])
                        for d in range(n_districts)])
```

These sorts of nested loops present a challenge for Theano, as it seems to require a complicated `scan` call (or two). As noted in #788 using an `as_op` returns a function, so that's not a viable alternative for nodes that are non-terminal in the DAG.

**Comment by aflaxman** [comment]
There is definitely some mind-bending for those of us too familiar with PyMC2, but I think that the PyMC3 equivalent of this deterministic is simply

```
with pm.Model() as m:
    I = pm.Uniform('I', lower=0, upper=1000, shape=(3,10))
    S_0 = pm.Uniform('S_0', lower=0, upper=1000, shape=(3,))

    S = np.array([S_0[d] - np.array([I[d,:t].sum() 
                    for t in range(10)])
                        for d in range(3)])
```

I guess `S` is a bit weird to deal with in this case, though, but it has the right values in it somewhere:

```
m.fn(S[0][9])({'I':np.ones((3,10)), 'S_0':np.array([20.,21.,22.])})
Out[4]: array(11.0)
```

**Comment by jsalvatier** [comment]
I am again surprised at numpy working on theano when I would expect it not to. 

Instead of np.array I would do `theano.tensor.concatenate`.

**Comment by fonnesbeck** [comment]
Closing as an issue. Perhaps create a Wiki page or roadmap document for goals?
