### ISSUE TITLE
Import Error (Using Canopy)

### ISSUE THREAD

**Issue by Gouryella91** [pymc-devs/pymc#837]
I'm trying to install pymc2 (I'm a beginner), and I used the GitHub Desktop to clone the files... but when I try to run the test code "import pymc", I get an import error that looks like this:

```
import pymc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

ImportError: No module named pymc 
```

P.S. I have no clue what to do, or whether I should be opening/installing other software. Any help is appreciated, thanks!

**Comment by fonnesbeck** [comment]
This report belongs on the [PyMC tracker](https://github.com/pymc-devs/pymc/issues) rather than here on PyMC3. In any case, this means that you have not installed PyMC. Pulling the code from GitHub doesn't install the software, it just gets you the source code. Try running: `pip install pymc` instead.

See the [PyMC documentation](http://pymcmc.readthedocs.org/en/latest/) for details.
