### ISSUE TITLE
getting_started notebook indefinite hang

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#849]
The [`getting_started` notebook](https://github.com/pymc-devs/pymc3/blob/master/docs/notebooks/getting_started.ipynb) in the docs is currently not able to run to completion. Even overnight runs on a new machine do not see the models through to completion. It hangs either on the S&P500 example or on the GLM example. In particular, I've never gotten past `model_lm_logistic`. Can anyone else replicate this?

**Comment by twiecki** [comment]
This happens even with the reduced length of s&p 500 data?

**Comment by fonnesbeck** [comment]
Correct

**Comment by bjmacdonald** [comment]
I've been trying to work my way through the getting_started notebook, current from git on friday. Latest Anaconda python 3.4 on Windows x64, theano-cache cleared.

The stochastic volatility example runs with "njobs=4" commented out on the sample() call.  Otherwise it either hangs when you add it back in or throws "RuntimeError: maximum recursion depth exceeded while pickling an object". 

The coal mining switchpoint sample throws "TypeError: expected type_num 9 (NPY_INT64) got 7".

The GLM example runs fine for me.  I didn't try the Backend examples.

**Comment by fonnesbeck** [comment]
When the model actually completes (in almost 100 hours!), the results are pretty grim:

![](http://dsh.re/0655c)

**Comment by twiecki** [comment]
I'll investigate.

**Comment by twiecki** [comment]
Should be fixed with https://github.com/pymc-devs/pymc3/commit/2e134e3f29b159848d8e87aad94ba30ffead6b94
Also updated the tutorial: http://pymc-devs.github.io/pymc3/getting_started/
